<?php
/**
 * ENGLISH language file: please UTF-8 encoding only, so use UTF-8 compliant editor only
 ****************************************************************************************/

$GLOBALS['L'] = array (
	'Forums Index' => 'Forums Index',
	'Forums' => 'Forums',
	'Forum' => 'Forum',
	'Topics' => 'Topics',	
	'Topic' => 'Topic',
	'Orca Forum' => ':: Orca Forum',
	'Logged in as' => 'Logged in as',
	'Manage Forum' => 'Manage Forum',
	'Reported Posts' => 'Reported Posts',
	'Logout' => 'Logout',
	'My Flags' => 'My Flags',
	'My Topics' => 'My Topics',
	'Login' => 'Login',
	'Search' => 'Search',
    'Copyright' => 'Copyright 2008 My Company',
    'New Group' => 'New Group',
	'New Topic' => 'New Topic',
	'Post Reply' => 'Post Reply',
	'Flag/Unflag' => 'Flag/Unflag',
	'Lock/Unlock' => 'Lock/Unlock',
	'Author' => 'Author',
	'Message' => 'Message',
	'posts:' => 'posts:',
	'Delete' => 'Delete',
	'Edit' => 'Edit',
	'Quote' => 'Quote',
	'post is hidden' => 'post is hidden',
	'hide post' => 'hide post',
	'show post' => 'show post',
	'Points:' => 'Points:',
	'Vote' => 'Vote',
	'Access denied' => 'Access denied. You must have special permissions to access this area or you are not logged in.',
	'New topic created' => 'New topic has been successfully created',
	'return to forum index' => 'return to forum index',
	'Edit group' => 'Edit group',
	'New group' => 'New group',
	'Cancel' => 'Cancel',
	'Submit' => 'Submit',
	'Submit' => 'Submit',
	'New forum' => 'New forum',
	'Forum title:' => 'Forum title:',
	'Forum description:' => 'Forum description:',
	'Forum type:' => 'Forum type:',
	'public' => 'public',
	'private' => 'private',
	'Latest Reply' => 'Latest Reply',
	'Latest Post' => 'Latest Post',	
	'Posts' => 'Posts',
	'Pages:' => 'Pages:',
	'Join' => 'Join',
	'Forums Spy' => 'Forums Spy <span>(a real-time view of activity)</span>',
	'said in' => 'said in',
	'Topic subject:' => 'Topic subject:',
	'Topic subject Error' => 'Please enter from 5 to 50 symbols', 
	'Sticky' => 'Sticky',
	'Topic text:' => 'Topic text:',
	'Topic text Error' => 'Please enter from 5 to 640000 symbols',
	'Post Reply:' => 'Post Reply:',
	'Special Member' => 'Special Member',
	'Standard Member' => 'Standard Member',
	'Member Info' => 'Member Info',
	'Joined:' => 'Joined:',
	'Last Online:' => 'Last Online:',
	'Posts:' => 'Posts:',
	'Last Post:' => 'Last Post:',
	'never' => 'never',
	'Find all posts by' => 'Find all posts by',
	'New Search' => 'New Search',
	'Search Results For:' => 'Search Results For:',
	'There are no search results.' => 'There are no search results.',
	'Please try search again.' => 'Please <a href="javascript:void(0);" onclick="return f.showSearch()" >try again</a>.',
	'Date' => 'Date',
	'Search The Forum' => 'Search The Forum',
	'Search for:' => 'Search for:',
	'Where to Search:' => 'Where to Search:',
	'Topic Titles' => 'Topic Titles',
	'Messages' => 'Messages',
	'Forum:' => 'Forum:',
	'Whole Forum' => 'Whole Forum',
	'Author:' => 'Author:',
    'Display:' => 'Display:',	

    'Site is unavailable' => 'Sorry, site is unavailable now, please try again later.',
    'Join Login Username Error' => 'Username must be from 4 to 12 characters',
    'Join Email Error' => 'Email must be valid', 
    'Username must be uniq' => 'Username must be uniq',
    'Login Password Error' => 'Password must be valid', 
    'Email must be uniq' => 'Email must be uniq',
    'Database error' => 'Database error',
    'Send mail failed' => 'Send mail failed',
    'password or login is incorrect' => 'password or login is incorrect',
    'Cookies must be enabled to process login' => 'Cookies must be enabled to process login',

    'Username' => 'Username',
    'Password' => 'Password',
    'Email' => 'Email',
    'Wrong search type' => 'Wrong search type',
    'Topics you participate in' => 'Topics you participate in',
    'Flagged topics' => 'Flagged topics',
    'Topics you have flagged' => 'Topics you have flagged',
    '%s\'s forum posts' => '%s\'s forum posts',
    'Forum Posts' => 'Forum Posts',
    'Minute Ago' => 'Minute Ago',
    'Minutes Ago' => 'Minutes Ago',
    'Hour Ago' => 'Hour Ago',
    'Hours Ago' => 'Hours Ago',
    'Day Ago' => 'Day Ago',
    'Days Ago' => 'Days Ago',
    'Mail Subj Registration' => 'Orca Forum Registration Details',  
    'Mail Body Registration' => "
<p>Dear {username},</p>

<p>
Your username: {username} <br />
Your password: {pwd} <br />
Site URL: {site_url} <br />
</p>

<p>
Thank you for joining.
</p>
<p>
Best Regards, Orca Forum.
</p>
",
    'xml serialization failed' => 'xml serialization failed',
    'please upgrade your browser' => 'please upgrade your browser',
    'XML read failed:' => 'XML read failed:',
    'There was a problem retrieving the XML data:' => 'There was a problem retrieving the XML data:',
    'httpxml object creation failed' => 'httpxml object creation failed',

    'LOADING LOGIN FORM' => 'LOADING LOGIN FORM',
    'LOADING JOIN FORM' => 'LOADING JOIN FORM',
    'SEARCHING' => 'SEARCHING',
    'LOADING FORUMS' => 'LOADING FORUMS',
    'LOADING FORUM TOPICS' => 'LOADING FORUM TOPICS',
    'LOADING FORUM INDEX' => 'LOADING FORUM INDEX',
    'LOADING PROFILE PAGE' => 'LOADING PROFILE PAGE',
    'LOADING TOPIC POSTS' => 'LOADING TOPIC POSTS',
    'LOADING POST TOPIC PAGE' => 'LOADING POST TOPIC PAGE',
    'LOADING' => 'LOADING',
    'LOADING SEARCH PAGE' => 'LOADING SEARCH PAGE',
    'LOADING POST REPLY PAGE' => 'LOADING POST REPLY PAGE',     
    'SENDING MESSAGE' => 'SENDING MESSAGE',
    'POST IS LOADING' => 'POST IS LOADING',

    'Thank you! You Joined! Your login and password have been sent to your email.' => 'Thank you! You Joined! Your login and password have been sent to your email.',
    'Join failed' => 'Join failed',
    'Login failed' => 'Login failed',
    'orca_main div is not defined' => 'orca_main div is not defined',
    'please name orca_main content container' => 'please name orca_main content container',
    'category id is not defined' => 'category id is not defined',
    'please set category ids' => 'please set category ids',
    'Please login to view topics you participate in' => 'Please login to view topics you participate in',
    'Please login to view flagged topics' => 'Please login to view flagged topics',
    'Are you sure ?' => 'Are you sure ?',
    'Post was successfully deleted' => 'Post was successfully deleted',
    'Topic and post were successfully deleted' => 'Topic and post were successfully deleted',
    'Post was successfully edited' => 'Post was successfully edited',
    'Message body empty' => 'Message body empty',
    'Valid chars:' => 'Valid chars:',
    'Topic has been successfully added to your flagged topics' => 'Topic has been successfully added to your flagged topics',
    'Topic has been successfully removed from your flagged topics' => 'Topic has been successfully removed from your flagged topics',
    'Please login to flag topics' => 'Please login to flag topics',
    'Post has been reported' => 'Post has been reported',
    'Report error' => 'Report error',
    'add this to title' => ' :: Orca Forum ',
    'Are you sure to delete category with all forums, topics and post?' => 'Are you sure to delete category with all forums, topics and post?',
    'Category has been successfully deleted' => 'Category has been successfully deleted',
    'Can not delete category' => 'Can not delete category',
    'Are you sure to delete forum with topics and posts' => 'Are you sure to delete forum with topics and posts',
    'Forum has been successfully deleted' => 'Forum has been successfully deleted',
    'Can not delete forum' => 'Can not delete forum',
    'Group has been successfully modified' => 'Group has been successfully modified',
    'New group has been successfully added' => 'New group has been successfully added',
    'Can not modify group' => 'Can not modify group',
    'Can not add new group' => 'Can not add new group',
    'Forum has been successfully modified' => 'Forum has been successfully modified',
    'New forum has been successfully added' => 'New forum has been successfully added',
    'Can not modify forum' => 'Can not modify forum',
    'Can not add new forum' => 'Can not add new forum',
    'Topic has been successfully locked' => 'Topic has been successfully locked',
    'Topic has been successfully unlocked' => 'Topic has been successfully unlocked',
    'Only admin can lock/unlock topics' => 'Only admin can lock/unlock topics',
    'new group' => 'new group',
    'edit' => 'edit',
    'delete' => 'delete',
    'new forum' => 'new forum',
    'move up' => 'move up',
    'move down' => 'move down',
    'permalink' => 'permalink',
    'report this post' => 'report this post',
    'Compile Langs' => 'Compile Languages',
    'Language files compilation have been failed' => 'Language files compilation have been failed. Please check folders permissions.',
    'Language files have been successfully compiled' => 'Language files have been successfully compiled',
);

?>
