INSERT INTO `PageCompose` VALUES(64, 'profile', '960px', 'Member polls block', '_Polls', 1, 4, 'ProfilePolls', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(65, 'profile', '960px', 'Actions that other members can do', '_Actions', 1, 0, 'ActionsMenu', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(66, 'profile', '960px', 'Profile rating form', '_rate profile', 2, 4, 'RateProfile', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(67, 'profile', '960px', 'Member friends list', '_Friends', 2, 6, 'Friends', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(68, 'profile', '960px', 'Comments on member profile', '_profile_comments', 2, 10, 'Cmts', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(69, 'profile', '960px', 'Member blog block', '_Blog', 2, 5, 'Blog', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(70, 'profile', '960px', 'Profile Mp3 Player', '_ProfileMp3', 2, 8, 'Mp3', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(71, 'profile', '960px', 'Last posts of a member in the forum', '_Forum Posts', 2, 9, 'RSS', '{SiteUrl}orca/?action=rss_user&user={NickName}#4', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(72, 'profile', '960px', '', '_BoonEx News', 0, 0, 'RSS', 'http://www.boonex.com/unity/blog/featured_posts/?rss=1#4', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(73, 'profile', '960px', 'Classifieds', '_Classifieds', 1, 1, 'Classifieds', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(74, 'profile', '960px', 'Events', '_Events', 1, 2, 'Events', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(75, 'profile', '960px', 'Groups', '_Groups', 1, 3, 'Groups', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(76, 'profile', '960px', 'Music Shared By The Member', '_Music Gallery', 1, 5, 'ShareMusic', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(77, 'profile', '960px', 'Photos Shared By The Member', '_Photo Gallery', 1, 6, 'SharePhotos', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(78, 'profile', '960px', 'Videos Shared By The Member', '_Video Gallery', 1, 7, 'ShareVideos', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(79, 'profile', '960px', 'Mutual friends of viewing and viewed members', '_Mutual Friends', 2, 7, 'MutualFriends', '', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(80, 'profile', '960px', 'Profile Fields Block', '_FieldCaption_General Info_View', 2, 1, 'PFBlock', '17', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(81, 'profile', '960px', 'Profile Fields Block', '_FieldCaption_Misc Info_View', 2, 2, 'PFBlock', '20', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(82, 'profile', '960px', 'Profile Fields Block', '_FieldCaption_Admin Controls_View', 2, 0, 'PFBlock', '21', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(83, 'profile', '960px', 'Profile Fields Block', '_FieldCaption_Description_View', 2, 3, 'PFBlock', '22', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(84, 'profile', '960px', 'Profile Fields Block', '_FieldCaption_Security Image_View', 0, 0, 'PFBlock', '25', 1, 50, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(85, 'profile', '960px', 'Profile Fields Block', '_FieldCaption_Profile Type_View', 0, 0, 'PFBlock', '30', 1, 50, 'non,memb', 0);
