package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdminBanListId generated by hbm2java
 */
@Embeddable
public class AdminBanListId implements java.io.Serializable {

	private int profId;
	private int time;
	private Date dateTime;

	public AdminBanListId() {
	}

	public AdminBanListId(int profId, int time, Date dateTime) {
		this.profId = profId;
		this.time = time;
		this.dateTime = dateTime;
	}

	@Column(name = "ProfID", nullable = false)
	public int getProfId() {
		return this.profId;
	}

	public void setProfId(int profId) {
		this.profId = profId;
	}

	@Column(name = "Time", nullable = false)
	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	@Column(name = "DateTime", nullable = false, length = 0)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdminBanListId))
			return false;
		AdminBanListId castOther = (AdminBanListId) other;

		return (this.getProfId() == castOther.getProfId())
				&& (this.getTime() == castOther.getTime())
				&& ((this.getDateTime() == castOther.getDateTime()) || (this
						.getDateTime() != null
						&& castOther.getDateTime() != null && this
						.getDateTime().equals(castOther.getDateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProfId();
		result = 37 * result + this.getTime();
		result = 37 * result
				+ (getDateTime() == null ? 0 : this.getDateTime().hashCode());
		return result;
	}

}
