package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdminLinksId generated by hbm2java
 */
@Embeddable
public class AdminLinksId implements java.io.Serializable {

	private String title;
	private String url;

	public AdminLinksId() {
	}

	public AdminLinksId(String title, String url) {
		this.title = title;
		this.url = url;
	}

	@Column(name = "Title", nullable = false, length = 30)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Url", nullable = false, length = 150)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdminLinksId))
			return false;
		AdminLinksId castOther = (AdminLinksId) other;

		return ((this.getTitle() == castOther.getTitle()) || (this.getTitle() != null
				&& castOther.getTitle() != null && this.getTitle().equals(
				castOther.getTitle())))
				&& ((this.getUrl() == castOther.getUrl()) || (this.getUrl() != null
						&& castOther.getUrl() != null && this.getUrl().equals(
						castOther.getUrl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37 * result
				+ (getUrl() == null ? 0 : this.getUrl().hashCode());
		return result;
	}

}
