package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Banners generated by hbm2java
 */
@Entity
@Table(name = "Banners", catalog = "dolphin")
public class Banners implements java.io.Serializable {

	private Integer id;
	private String title;
	private String url;
	private String text;
	private byte active;
	private Date created;
	private Date campaignStart;
	private Date campaignEnd;
	private int position;
	private int lhshift;
	private int lvshift;
	private int rhshift;
	private int rvshift;

	public Banners() {
	}

	public Banners(String title, String url, String text, byte active,
			Date created, Date campaignStart, Date campaignEnd, int position,
			int lhshift, int lvshift, int rhshift, int rvshift) {
		this.title = title;
		this.url = url;
		this.text = text;
		this.active = active;
		this.created = created;
		this.campaignStart = campaignStart;
		this.campaignEnd = campaignEnd;
		this.position = position;
		this.lhshift = lhshift;
		this.lvshift = lvshift;
		this.rhshift = rhshift;
		this.rvshift = rvshift;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Title", nullable = false, length = 32)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "Text", nullable = false, length = 16777215)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "Active", nullable = false)
	public byte getActive() {
		return this.active;
	}

	public void setActive(byte active) {
		this.active = active;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "campaign_start", nullable = false, length = 0)
	public Date getCampaignStart() {
		return this.campaignStart;
	}

	public void setCampaignStart(Date campaignStart) {
		this.campaignStart = campaignStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "campaign_end", nullable = false, length = 0)
	public Date getCampaignEnd() {
		return this.campaignEnd;
	}

	public void setCampaignEnd(Date campaignEnd) {
		this.campaignEnd = campaignEnd;
	}

	@Column(name = "Position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	@Column(name = "lhshift", nullable = false)
	public int getLhshift() {
		return this.lhshift;
	}

	public void setLhshift(int lhshift) {
		this.lhshift = lhshift;
	}

	@Column(name = "lvshift", nullable = false)
	public int getLvshift() {
		return this.lvshift;
	}

	public void setLvshift(int lvshift) {
		this.lvshift = lvshift;
	}

	@Column(name = "rhshift", nullable = false)
	public int getRhshift() {
		return this.rhshift;
	}

	public void setRhshift(int rhshift) {
		this.rhshift = rhshift;
	}

	@Column(name = "rvshift", nullable = false)
	public int getRvshift() {
		return this.rvshift;
	}

	public void setRvshift(int rvshift) {
		this.rvshift = rvshift;
	}

}
