package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BlogPosts generated by hbm2java
 */
@Entity
@Table(name = "BlogPosts", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "PostUri"))
public class BlogPosts implements java.io.Serializable {

	private Integer postId;
	private Integer categoryId;
	private String postCaption;
	private String postUri;
	private String postText;
	private Date postDate;
	private String postReadPermission;
	private String postCommentPermission;
	private String postStatus;
	private String postPhoto;
	private String tags;

	public BlogPosts() {
	}

	public BlogPosts(String postCaption, String postUri, String postText,
			Date postDate, String postReadPermission,
			String postCommentPermission, String postStatus, String tags) {
		this.postCaption = postCaption;
		this.postUri = postUri;
		this.postText = postText;
		this.postDate = postDate;
		this.postReadPermission = postReadPermission;
		this.postCommentPermission = postCommentPermission;
		this.postStatus = postStatus;
		this.tags = tags;
	}

	public BlogPosts(Integer categoryId, String postCaption, String postUri,
			String postText, Date postDate, String postReadPermission,
			String postCommentPermission, String postStatus, String postPhoto,
			String tags) {
		this.categoryId = categoryId;
		this.postCaption = postCaption;
		this.postUri = postUri;
		this.postText = postText;
		this.postDate = postDate;
		this.postReadPermission = postReadPermission;
		this.postCommentPermission = postCommentPermission;
		this.postStatus = postStatus;
		this.postPhoto = postPhoto;
		this.tags = tags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PostID", unique = true, nullable = false)
	public Integer getPostId() {
		return this.postId;
	}

	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	@Column(name = "CategoryID")
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "PostCaption", nullable = false)
	public String getPostCaption() {
		return this.postCaption;
	}

	public void setPostCaption(String postCaption) {
		this.postCaption = postCaption;
	}

	@Column(name = "PostUri", unique = true, nullable = false)
	public String getPostUri() {
		return this.postUri;
	}

	public void setPostUri(String postUri) {
		this.postUri = postUri;
	}

	@Column(name = "PostText", nullable = false, length = 65535)
	public String getPostText() {
		return this.postText;
	}

	public void setPostText(String postText) {
		this.postText = postText;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PostDate", nullable = false, length = 0)
	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

	@Column(name = "PostReadPermission", nullable = false, length = 7)
	public String getPostReadPermission() {
		return this.postReadPermission;
	}

	public void setPostReadPermission(String postReadPermission) {
		this.postReadPermission = postReadPermission;
	}

	@Column(name = "PostCommentPermission", nullable = false, length = 7)
	public String getPostCommentPermission() {
		return this.postCommentPermission;
	}

	public void setPostCommentPermission(String postCommentPermission) {
		this.postCommentPermission = postCommentPermission;
	}

	@Column(name = "PostStatus", nullable = false, length = 11)
	public String getPostStatus() {
		return this.postStatus;
	}

	public void setPostStatus(String postStatus) {
		this.postStatus = postStatus;
	}

	@Column(name = "PostPhoto", length = 50)
	public String getPostPhoto() {
		return this.postPhoto;
	}

	public void setPostPhoto(String postPhoto) {
		this.postPhoto = postPhoto;
	}

	@Column(name = "Tags", nullable = false)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

}
