package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BlogCategories generated by hbm2java
 */
@Entity
@Table(name = "BlogCategories", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "CategoryUri"))
public class BlogCategories implements java.io.Serializable {

	private Integer categoryId;
	private Integer ownerId;
	private String categoryName;
	private String categoryUri;
	private int categoryType;
	private String categoryPhoto;
	private Date date;

	public BlogCategories() {
	}

	public BlogCategories(String categoryUri, int categoryType, Date date) {
		this.categoryUri = categoryUri;
		this.categoryType = categoryType;
		this.date = date;
	}

	public BlogCategories(Integer ownerId, String categoryName,
			String categoryUri, int categoryType, String categoryPhoto,
			Date date) {
		this.ownerId = ownerId;
		this.categoryName = categoryName;
		this.categoryUri = categoryUri;
		this.categoryType = categoryType;
		this.categoryPhoto = categoryPhoto;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "CategoryID", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "OwnerID")
	public Integer getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	@Column(name = "CategoryName", length = 150)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "CategoryUri", unique = true, nullable = false, length = 150)
	public String getCategoryUri() {
		return this.categoryUri;
	}

	public void setCategoryUri(String categoryUri) {
		this.categoryUri = categoryUri;
	}

	@Column(name = "CategoryType", nullable = false)
	public int getCategoryType() {
		return this.categoryType;
	}

	public void setCategoryType(int categoryType) {
		this.categoryType = categoryType;
	}

	@Column(name = "CategoryPhoto", length = 150)
	public String getCategoryPhoto() {
		return this.categoryPhoto;
	}

	public void setCategoryPhoto(String categoryPhoto) {
		this.categoryPhoto = categoryPhoto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
