package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CmtsTrackId generated by hbm2java
 */
@Embeddable
public class CmtsTrackId implements java.io.Serializable {

	private int cmtSystemId;
	private int cmtId;
	private int cmtRateAuthorNip;

	public CmtsTrackId() {
	}

	public CmtsTrackId(int cmtSystemId, int cmtId, int cmtRateAuthorNip) {
		this.cmtSystemId = cmtSystemId;
		this.cmtId = cmtId;
		this.cmtRateAuthorNip = cmtRateAuthorNip;
	}

	@Column(name = "cmt_system_id", nullable = false)
	public int getCmtSystemId() {
		return this.cmtSystemId;
	}

	public void setCmtSystemId(int cmtSystemId) {
		this.cmtSystemId = cmtSystemId;
	}

	@Column(name = "cmt_id", nullable = false)
	public int getCmtId() {
		return this.cmtId;
	}

	public void setCmtId(int cmtId) {
		this.cmtId = cmtId;
	}

	@Column(name = "cmt_rate_author_nip", nullable = false)
	public int getCmtRateAuthorNip() {
		return this.cmtRateAuthorNip;
	}

	public void setCmtRateAuthorNip(int cmtRateAuthorNip) {
		this.cmtRateAuthorNip = cmtRateAuthorNip;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CmtsTrackId))
			return false;
		CmtsTrackId castOther = (CmtsTrackId) other;

		return (this.getCmtSystemId() == castOther.getCmtSystemId())
				&& (this.getCmtId() == castOther.getCmtId())
				&& (this.getCmtRateAuthorNip() == castOther
						.getCmtRateAuthorNip());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCmtSystemId();
		result = 37 * result + this.getCmtId();
		result = 37 * result + this.getCmtRateAuthorNip();
		return result;
	}

}
