package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CmtsTrack generated by hbm2java
 */
@Entity
@Table(name = "CmtsTrack", catalog = "dolphin")
public class CmtsTrack implements java.io.Serializable {

	private CmtsTrackId id;
	private byte cmtRate;
	private int cmtRateAuthorId;
	private int cmtRateTs;

	public CmtsTrack() {
	}

	public CmtsTrack(CmtsTrackId id, byte cmtRate, int cmtRateAuthorId,
			int cmtRateTs) {
		this.id = id;
		this.cmtRate = cmtRate;
		this.cmtRateAuthorId = cmtRateAuthorId;
		this.cmtRateTs = cmtRateTs;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "cmtSystemId", column = @Column(name = "cmt_system_id", nullable = false)),
			@AttributeOverride(name = "cmtId", column = @Column(name = "cmt_id", nullable = false)),
			@AttributeOverride(name = "cmtRateAuthorNip", column = @Column(name = "cmt_rate_author_nip", nullable = false)) })
	public CmtsTrackId getId() {
		return this.id;
	}

	public void setId(CmtsTrackId id) {
		this.id = id;
	}

	@Column(name = "cmt_rate", nullable = false)
	public byte getCmtRate() {
		return this.cmtRate;
	}

	public void setCmtRate(byte cmtRate) {
		this.cmtRate = cmtRate;
	}

	@Column(name = "cmt_rate_author_id", nullable = false)
	public int getCmtRateAuthorId() {
		return this.cmtRateAuthorId;
	}

	public void setCmtRateAuthorId(int cmtRateAuthorId) {
		this.cmtRateAuthorId = cmtRateAuthorId;
	}

	@Column(name = "cmt_rate_ts", nullable = false)
	public int getCmtRateTs() {
		return this.cmtRateTs;
	}

	public void setCmtRateTs(int cmtRateTs) {
		this.cmtRateTs = cmtRateTs;
	}

}
