package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ColorBase generated by hbm2java
 */
@Entity
@Table(name = "ColorBase", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "ColorName"))
public class ColorBase implements java.io.Serializable {

	private ColorBaseId id;

	public ColorBase() {
	}

	public ColorBase(ColorBaseId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "colorName", column = @Column(name = "ColorName", unique = true, nullable = false, length = 20)),
			@AttributeOverride(name = "colorCode", column = @Column(name = "ColorCode", nullable = false, length = 10)) })
	public ColorBaseId getId() {
		return this.id;
	}

	public void setId(ColorBaseId id) {
		this.id = id;
	}

}
