package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "Countries", catalog = "dolphin")
public class Countries implements java.io.Serializable {

	private String iso2;
	private String iso3;
	private short isono;
	private String country;
	private String region;
	private String currency;
	private String currencyCode;

	public Countries() {
	}

	public Countries(String iso2, String iso3, short isono, String country) {
		this.iso2 = iso2;
		this.iso3 = iso3;
		this.isono = isono;
		this.country = country;
	}

	public Countries(String iso2, String iso3, short isono, String country,
			String region, String currency, String currencyCode) {
		this.iso2 = iso2;
		this.iso3 = iso3;
		this.isono = isono;
		this.country = country;
		this.region = region;
		this.currency = currency;
		this.currencyCode = currencyCode;
	}

	@Id
	@Column(name = "ISO2", unique = true, nullable = false, length = 2)
	public String getIso2() {
		return this.iso2;
	}

	public void setIso2(String iso2) {
		this.iso2 = iso2;
	}

	@Column(name = "ISO3", nullable = false, length = 3)
	public String getIso3() {
		return this.iso3;
	}

	public void setIso3(String iso3) {
		this.iso3 = iso3;
	}

	@Column(name = "ISONo", nullable = false)
	public short getIsono() {
		return this.isono;
	}

	public void setIsono(short isono) {
		this.isono = isono;
	}

	@Column(name = "Country", nullable = false, length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "Region", length = 100)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "Currency", length = 100)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "CurrencyCode", length = 3)
	public String getCurrencyCode() {
		return this.currencyCode;
	}

	public void setCurrencyCode(String currencyCode) {
		this.currencyCode = currencyCode;
	}

}
