package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GmusicRating generated by hbm2java
 */
@Entity
@Table(name = "gmusic_rating", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "gal_id"))
public class GmusicRating implements java.io.Serializable {

	private GmusicRatingId id;

	public GmusicRating() {
	}

	public GmusicRating(GmusicRatingId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "galId", column = @Column(name = "gal_id", unique = true, nullable = false)),
			@AttributeOverride(name = "galRatingCount", column = @Column(name = "gal_rating_count", nullable = false)),
			@AttributeOverride(name = "galRatingSum", column = @Column(name = "gal_rating_sum", nullable = false)) })
	public GmusicRatingId getId() {
		return this.id;
	}

	public void setId(GmusicRatingId id) {
		this.id = id;
	}

}
