package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GroupsGallery generated by hbm2java
 */
@Entity
@Table(name = "GroupsGallery", catalog = "dolphin")
public class GroupsGallery implements java.io.Serializable {

	private Integer id;
	private int groupId;
	private String ext;
	private int width;
	private int height;
	private int width_1;
	private int height_1;
	private int by;
	private String seed;

	public GroupsGallery() {
	}

	public GroupsGallery(int groupId, String ext, int width, int height,
			int width_1, int height_1, int by, String seed) {
		this.groupId = groupId;
		this.ext = ext;
		this.width = width;
		this.height = height;
		this.width_1 = width_1;
		this.height_1 = height_1;
		this.by = by;
		this.seed = seed;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "groupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "ext", nullable = false, length = 4)
	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	@Column(name = "width", nullable = false)
	public int getWidth() {
		return this.width;
	}

	public void setWidth(int width) {
		this.width = width;
	}

	@Column(name = "height", nullable = false)
	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	@Column(name = "width_", nullable = false)
	public int getWidth_1() {
		return this.width_1;
	}

	public void setWidth_1(int width_1) {
		this.width_1 = width_1;
	}

	@Column(name = "height_", nullable = false)
	public int getHeight_1() {
		return this.height_1;
	}

	public void setHeight_1(int height_1) {
		this.height_1 = height_1;
	}

	@Column(name = "by", nullable = false)
	public int getBy() {
		return this.by;
	}

	public void setBy(int by) {
		this.by = by;
	}

	@Column(name = "seed", nullable = false, length = 10)
	public String getSeed() {
		return this.seed;
	}

	public void setSeed(String seed) {
		this.seed = seed;
	}

}
