package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GrpForumUserStat generated by hbm2java
 */
@Entity
@Table(name = "grp_forum_user_stat", catalog = "dolphin")
public class GrpForumUserStat implements java.io.Serializable {

	private GrpForumUserStatId id;

	public GrpForumUserStat() {
	}

	public GrpForumUserStat(GrpForumUserStatId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "user", column = @Column(name = "user", nullable = false, length = 16)),
			@AttributeOverride(name = "posts", column = @Column(name = "posts", nullable = false)),
			@AttributeOverride(name = "userLastPost", column = @Column(name = "user_last_post", nullable = false)) })
	public GrpForumUserStatId getId() {
		return this.id;
	}

	public void setId(GrpForumUserStatId id) {
		this.id = id;
	}

}
