package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GrpForumReport generated by hbm2java
 */
@Entity
@Table(name = "grp_forum_report", catalog = "dolphin")
public class GrpForumReport implements java.io.Serializable {

	private GrpForumReportId id;

	public GrpForumReport() {
	}

	public GrpForumReport(GrpForumReportId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", nullable = false, length = 16)),
			@AttributeOverride(name = "postId", column = @Column(name = "post_id", nullable = false)) })
	public GrpForumReportId getId() {
		return this.id;
	}

	public void setId(GrpForumReportId id) {
		this.id = id;
	}

}
