package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GrpForumReportId generated by hbm2java
 */
@Embeddable
public class GrpForumReportId implements java.io.Serializable {

	private String userName;
	private int postId;

	public GrpForumReportId() {
	}

	public GrpForumReportId(String userName, int postId) {
		this.userName = userName;
		this.postId = postId;
	}

	@Column(name = "user_name", nullable = false, length = 16)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "post_id", nullable = false)
	public int getPostId() {
		return this.postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GrpForumReportId))
			return false;
		GrpForumReportId castOther = (GrpForumReportId) other;

		return ((this.getUserName() == castOther.getUserName()) || (this
				.getUserName() != null
				&& castOther.getUserName() != null && this.getUserName()
				.equals(castOther.getUserName())))
				&& (this.getPostId() == castOther.getPostId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + this.getPostId();
		return result;
	}

}
