package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocalizationStringParamsId generated by hbm2java
 */
@Embeddable
public class LocalizationStringParamsId implements java.io.Serializable {

	private short idkey;
	private byte idparam;

	public LocalizationStringParamsId() {
	}

	public LocalizationStringParamsId(short idkey, byte idparam) {
		this.idkey = idkey;
		this.idparam = idparam;
	}

	@Column(name = "IDKey", nullable = false)
	public short getIdkey() {
		return this.idkey;
	}

	public void setIdkey(short idkey) {
		this.idkey = idkey;
	}

	@Column(name = "IDParam", nullable = false)
	public byte getIdparam() {
		return this.idparam;
	}

	public void setIdparam(byte idparam) {
		this.idparam = idparam;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocalizationStringParamsId))
			return false;
		LocalizationStringParamsId castOther = (LocalizationStringParamsId) other;

		return (this.getIdkey() == castOther.getIdkey())
				&& (this.getIdparam() == castOther.getIdparam());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdkey();
		result = 37 * result + this.getIdparam();
		return result;
	}

}
