package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LocalizationStrings generated by hbm2java
 */
@Entity
@Table(name = "LocalizationStrings", catalog = "dolphin")
public class LocalizationStrings implements java.io.Serializable {

	private LocalizationStringsId id;
	private String string;

	public LocalizationStrings() {
	}

	public LocalizationStrings(LocalizationStringsId id, String string) {
		this.id = id;
		this.string = string;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idkey", column = @Column(name = "IDKey", nullable = false)),
			@AttributeOverride(name = "idlanguage", column = @Column(name = "IDLanguage", nullable = false)) })
	public LocalizationStringsId getId() {
		return this.id;
	}

	public void setId(LocalizationStringsId id) {
		this.id = id;
	}

	@Column(name = "String", nullable = false, length = 16777215)
	public String getString() {
		return this.string;
	}

	public void setString(String string) {
		this.string = string;
	}

}
