package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LocalizationStringParams generated by hbm2java
 */
@Entity
@Table(name = "LocalizationStringParams", catalog = "dolphin")
public class LocalizationStringParams implements java.io.Serializable {

	private LocalizationStringParamsId id;
	private String description;

	public LocalizationStringParams() {
	}

	public LocalizationStringParams(LocalizationStringParamsId id,
			String description) {
		this.id = id;
		this.description = description;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idkey", column = @Column(name = "IDKey", nullable = false)),
			@AttributeOverride(name = "idparam", column = @Column(name = "IDParam", nullable = false)) })
	public LocalizationStringParamsId getId() {
		return this.id;
	}

	public void setId(LocalizationStringParamsId id) {
		this.id = id;
	}

	@Column(name = "Description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
