package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LocalizationStringsId generated by hbm2java
 */
@Embeddable
public class LocalizationStringsId implements java.io.Serializable {

	private short idkey;
	private byte idlanguage;

	public LocalizationStringsId() {
	}

	public LocalizationStringsId(short idkey, byte idlanguage) {
		this.idkey = idkey;
		this.idlanguage = idlanguage;
	}

	@Column(name = "IDKey", nullable = false)
	public short getIdkey() {
		return this.idkey;
	}

	public void setIdkey(short idkey) {
		this.idkey = idkey;
	}

	@Column(name = "IDLanguage", nullable = false)
	public byte getIdlanguage() {
		return this.idlanguage;
	}

	public void setIdlanguage(byte idlanguage) {
		this.idlanguage = idlanguage;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LocalizationStringsId))
			return false;
		LocalizationStringsId castOther = (LocalizationStringsId) other;

		return (this.getIdkey() == castOther.getIdkey())
				&& (this.getIdlanguage() == castOther.getIdlanguage());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdkey();
		result = 37 * result + this.getIdlanguage();
		return result;
	}

}
