package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MediaVotingTrack generated by hbm2java
 */
@Entity
@Table(name = "media_voting_track", catalog = "dolphin")
public class MediaVotingTrack implements java.io.Serializable {

	private MediaVotingTrackId id;

	public MediaVotingTrack() {
	}

	public MediaVotingTrack(MediaVotingTrackId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "medId", column = @Column(name = "med_id", nullable = false)),
			@AttributeOverride(name = "medIp", column = @Column(name = "med_ip", length = 20)),
			@AttributeOverride(name = "medDate", column = @Column(name = "med_date", length = 0)) })
	public MediaVotingTrackId getId() {
		return this.id;
	}

	public void setId(MediaVotingTrackId id) {
		this.id = id;
	}

}
