package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name = "media", catalog = "dolphin")
public class Media implements java.io.Serializable {

	private Integer medId;
	private Integer medProfId;
	private String medType;
	private String medFile;
	private String medTitle;
	private String medStatus;
	private Date medDate;
	private int rateAble;

	public Media() {
	}

	public Media(String medType, String medStatus, int rateAble) {
		this.medType = medType;
		this.medStatus = medStatus;
		this.rateAble = rateAble;
	}

	public Media(Integer medProfId, String medType, String medFile,
			String medTitle, String medStatus, Date medDate, int rateAble) {
		this.medProfId = medProfId;
		this.medType = medType;
		this.medFile = medFile;
		this.medTitle = medTitle;
		this.medStatus = medStatus;
		this.medDate = medDate;
		this.rateAble = rateAble;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "med_id", unique = true, nullable = false)
	public Integer getMedId() {
		return this.medId;
	}

	public void setMedId(Integer medId) {
		this.medId = medId;
	}

	@Column(name = "med_prof_id")
	public Integer getMedProfId() {
		return this.medProfId;
	}

	public void setMedProfId(Integer medProfId) {
		this.medProfId = medProfId;
	}

	@Column(name = "med_type", nullable = false, length = 6)
	public String getMedType() {
		return this.medType;
	}

	public void setMedType(String medType) {
		this.medType = medType;
	}

	@Column(name = "med_file", length = 50)
	public String getMedFile() {
		return this.medFile;
	}

	public void setMedFile(String medFile) {
		this.medFile = medFile;
	}

	@Column(name = "med_title", length = 150)
	public String getMedTitle() {
		return this.medTitle;
	}

	public void setMedTitle(String medTitle) {
		this.medTitle = medTitle;
	}

	@Column(name = "med_status", nullable = false, length = 7)
	public String getMedStatus() {
		return this.medStatus;
	}

	public void setMedStatus(String medStatus) {
		this.medStatus = medStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "med_date", length = 0)
	public Date getMedDate() {
		return this.medDate;
	}

	public void setMedDate(Date medDate) {
		this.medDate = medDate;
	}

	@Column(name = "rate_able", nullable = false)
	public int getRateAble() {
		return this.rateAble;
	}

	public void setRateAble(int rateAble) {
		this.rateAble = rateAble;
	}

}
