package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MediaRating generated by hbm2java
 */
@Entity
@Table(name = "media_rating", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "med_id"))
public class MediaRating implements java.io.Serializable {

	private MediaRatingId id;

	public MediaRating() {
	}

	public MediaRating(MediaRatingId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "medId", column = @Column(name = "med_id", unique = true, nullable = false)),
			@AttributeOverride(name = "medRatingCount", column = @Column(name = "med_rating_count", nullable = false)),
			@AttributeOverride(name = "medRatingSum", column = @Column(name = "med_rating_sum", nullable = false)) })
	public MediaRatingId getId() {
		return this.id;
	}

	public void setId(MediaRatingId id) {
		this.id = id;
	}

}
