package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemActionsTrack generated by hbm2java
 */
@Entity
@Table(name = "MemActionsTrack", catalog = "dolphin")
public class MemActionsTrack implements java.io.Serializable {

	private MemActionsTrackId id;
	private short actionsLeft;
	private Date validSince;

	public MemActionsTrack() {
	}

	public MemActionsTrack(MemActionsTrackId id, short actionsLeft) {
		this.id = id;
		this.actionsLeft = actionsLeft;
	}

	public MemActionsTrack(MemActionsTrackId id, short actionsLeft,
			Date validSince) {
		this.id = id;
		this.actionsLeft = actionsLeft;
		this.validSince = validSince;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idaction", column = @Column(name = "IDAction", nullable = false)),
			@AttributeOverride(name = "idmember", column = @Column(name = "IDMember", nullable = false)) })
	public MemActionsTrackId getId() {
		return this.id;
	}

	public void setId(MemActionsTrackId id) {
		this.id = id;
	}

	@Column(name = "ActionsLeft", nullable = false)
	public short getActionsLeft() {
		return this.actionsLeft;
	}

	public void setActionsLeft(short actionsLeft) {
		this.actionsLeft = actionsLeft;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ValidSince", length = 0)
	public Date getValidSince() {
		return this.validSince;
	}

	public void setValidSince(Date validSince) {
		this.validSince = validSince;
	}

}
