package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MembersAsAff generated by hbm2java
 */
@Entity
@Table(name = "members_as_aff", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "ID"))
public class MembersAsAff implements java.io.Serializable {

	private MembersAsAffId id;

	public MembersAsAff() {
	}

	public MembersAsAff(MembersAsAffId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "id", column = @Column(name = "ID", unique = true, nullable = false)),
			@AttributeOverride(name = "numOfMem", column = @Column(name = "num_of_mem", nullable = false)),
			@AttributeOverride(name = "numOfDays", column = @Column(name = "num_of_days", nullable = false)),
			@AttributeOverride(name = "mid", column = @Column(name = "MID", nullable = false)) })
	public MembersAsAffId getId() {
		return this.id;
	}

	public void setId(MembersAsAffId id) {
		this.id = id;
	}

}
