package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MembersAsAffId generated by hbm2java
 */
@Embeddable
public class MembersAsAffId implements java.io.Serializable {

	private long id;
	private int numOfMem;
	private int numOfDays;
	private int mid;

	public MembersAsAffId() {
	}

	public MembersAsAffId(long id, int numOfMem, int numOfDays, int mid) {
		this.id = id;
		this.numOfMem = numOfMem;
		this.numOfDays = numOfDays;
		this.mid = mid;
	}

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "num_of_mem", nullable = false)
	public int getNumOfMem() {
		return this.numOfMem;
	}

	public void setNumOfMem(int numOfMem) {
		this.numOfMem = numOfMem;
	}

	@Column(name = "num_of_days", nullable = false)
	public int getNumOfDays() {
		return this.numOfDays;
	}

	public void setNumOfDays(int numOfDays) {
		this.numOfDays = numOfDays;
	}

	@Column(name = "MID", nullable = false)
	public int getMid() {
		return this.mid;
	}

	public void setMid(int mid) {
		this.mid = mid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MembersAsAffId))
			return false;
		MembersAsAffId castOther = (MembersAsAffId) other;

		return (this.getId() == castOther.getId())
				&& (this.getNumOfMem() == castOther.getNumOfMem())
				&& (this.getNumOfDays() == castOther.getNumOfDays())
				&& (this.getMid() == castOther.getMid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + this.getNumOfMem();
		result = 37 * result + this.getNumOfDays();
		result = 37 * result + this.getMid();
		return result;
	}

}
