package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MemLevelPricesId generated by hbm2java
 */
@Embeddable
public class MemLevelPricesId implements java.io.Serializable {

	private short idlevel;
	private int days;

	public MemLevelPricesId() {
	}

	public MemLevelPricesId(short idlevel, int days) {
		this.idlevel = idlevel;
		this.days = days;
	}

	@Column(name = "IDLevel", nullable = false)
	public short getIdlevel() {
		return this.idlevel;
	}

	public void setIdlevel(short idlevel) {
		this.idlevel = idlevel;
	}

	@Column(name = "Days", nullable = false)
	public int getDays() {
		return this.days;
	}

	public void setDays(int days) {
		this.days = days;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MemLevelPricesId))
			return false;
		MemLevelPricesId castOther = (MemLevelPricesId) other;

		return (this.getIdlevel() == castOther.getIdlevel())
				&& (this.getDays() == castOther.getDays());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdlevel();
		result = 37 * result + this.getDays();
		return result;
	}

}
