package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MemLevelPrices generated by hbm2java
 */
@Entity
@Table(name = "MemLevelPrices", catalog = "dolphin")
public class MemLevelPrices implements java.io.Serializable {

	private MemLevelPricesId id;
	private float price;

	public MemLevelPrices() {
	}

	public MemLevelPrices(MemLevelPricesId id, float price) {
		this.id = id;
		this.price = price;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idlevel", column = @Column(name = "IDLevel", nullable = false)),
			@AttributeOverride(name = "days", column = @Column(name = "Days", nullable = false)) })
	public MemLevelPricesId getId() {
		return this.id;
	}

	public void setId(MemLevelPricesId id) {
		this.id = id;
	}

	@Column(name = "Price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

}
