package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MemLevelActions generated by hbm2java
 */
@Entity
@Table(name = "MemLevelActions", catalog = "dolphin")
public class MemLevelActions implements java.io.Serializable {

	private MemLevelActionsId id;
	private Short allowedCount;
	private Short allowedPeriodLen;
	private Date allowedPeriodStart;
	private Date allowedPeriodEnd;
	private String additionalParamValue;

	public MemLevelActions() {
	}

	public MemLevelActions(MemLevelActionsId id) {
		this.id = id;
	}

	public MemLevelActions(MemLevelActionsId id, Short allowedCount,
			Short allowedPeriodLen, Date allowedPeriodStart,
			Date allowedPeriodEnd, String additionalParamValue) {
		this.id = id;
		this.allowedCount = allowedCount;
		this.allowedPeriodLen = allowedPeriodLen;
		this.allowedPeriodStart = allowedPeriodStart;
		this.allowedPeriodEnd = allowedPeriodEnd;
		this.additionalParamValue = additionalParamValue;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idlevel", column = @Column(name = "IDLevel", nullable = false)),
			@AttributeOverride(name = "idaction", column = @Column(name = "IDAction", nullable = false)) })
	public MemLevelActionsId getId() {
		return this.id;
	}

	public void setId(MemLevelActionsId id) {
		this.id = id;
	}

	@Column(name = "AllowedCount")
	public Short getAllowedCount() {
		return this.allowedCount;
	}

	public void setAllowedCount(Short allowedCount) {
		this.allowedCount = allowedCount;
	}

	@Column(name = "AllowedPeriodLen")
	public Short getAllowedPeriodLen() {
		return this.allowedPeriodLen;
	}

	public void setAllowedPeriodLen(Short allowedPeriodLen) {
		this.allowedPeriodLen = allowedPeriodLen;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AllowedPeriodStart", length = 0)
	public Date getAllowedPeriodStart() {
		return this.allowedPeriodStart;
	}

	public void setAllowedPeriodStart(Date allowedPeriodStart) {
		this.allowedPeriodStart = allowedPeriodStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AllowedPeriodEnd", length = 0)
	public Date getAllowedPeriodEnd() {
		return this.allowedPeriodEnd;
	}

	public void setAllowedPeriodEnd(Date allowedPeriodEnd) {
		this.allowedPeriodEnd = allowedPeriodEnd;
	}

	@Column(name = "AdditionalParamValue")
	public String getAdditionalParamValue() {
		return this.additionalParamValue;
	}

	public void setAdditionalParamValue(String additionalParamValue) {
		this.additionalParamValue = additionalParamValue;
	}

}
