package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "News", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "NewsUri"))
public class News implements java.io.Serializable {

	private Integer id;
	private Date date;
	private String header;
	private String newsUri;
	private String snippet;
	private String text;

	public News() {
	}

	public News(Date date, String header, String newsUri, String snippet,
			String text) {
		this.date = date;
		this.header = header;
		this.newsUri = newsUri;
		this.snippet = snippet;
		this.text = text;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Header", nullable = false, length = 50)
	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	@Column(name = "NewsUri", unique = true, nullable = false, length = 50)
	public String getNewsUri() {
		return this.newsUri;
	}

	public void setNewsUri(String newsUri) {
		this.newsUri = newsUri;
	}

	@Column(name = "Snippet", nullable = false)
	public String getSnippet() {
		return this.snippet;
	}

	public void setSnippet(String snippet) {
		this.snippet = snippet;
	}

	@Column(name = "Text", nullable = false, length = 65535)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
