package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NotifyMsgs generated by hbm2java
 */
@Entity
@Table(name = "NotifyMsgs", catalog = "dolphin")
public class NotifyMsgs implements java.io.Serializable {

	private Integer id;
	private String subj;
	private String text;
	private String html;

	public NotifyMsgs() {
	}

	public NotifyMsgs(String subj, String text, String html) {
		this.subj = subj;
		this.text = text;
		this.html = html;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Subj", nullable = false, length = 128)
	public String getSubj() {
		return this.subj;
	}

	public void setSubj(String subj) {
		this.subj = subj;
	}

	@Column(name = "Text", nullable = false, length = 16777215)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "HTML", nullable = false, length = 16777215)
	public String getHtml() {
		return this.html;
	}

	public void setHtml(String html) {
		this.html = html;
	}

}
