package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * NotifyQueue generated by hbm2java
 */
@Entity
@Table(name = "NotifyQueue", catalog = "dolphin")
public class NotifyQueue implements java.io.Serializable {

	private NotifyQueueId id;

	public NotifyQueue() {
	}

	public NotifyQueue(NotifyQueueId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "email", column = @Column(name = "Email", nullable = false)),
			@AttributeOverride(name = "msg", column = @Column(name = "Msg", nullable = false)),
			@AttributeOverride(name = "creation", column = @Column(name = "Creation", nullable = false, length = 0)),
			@AttributeOverride(name = "from", column = @Column(name = "From", nullable = false, length = 15)),
			@AttributeOverride(name = "msgText", column = @Column(name = "MsgText", nullable = false, length = 16777215)),
			@AttributeOverride(name = "msgSubj", column = @Column(name = "MsgSubj", nullable = false)) })
	public NotifyQueueId getId() {
		return this.id;
	}

	public void setId(NotifyQueueId id) {
		this.id = id;
	}

}
