package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentSubscriptions generated by hbm2java
 */
@Entity
@Table(name = "PaymentSubscriptions", catalog = "dolphin")
public class PaymentSubscriptions implements java.io.Serializable {

	private long transactionId;
	private Date startDate;
	private short period;
	private int chargesNumber;

	public PaymentSubscriptions() {
	}

	public PaymentSubscriptions(long transactionId, Date startDate,
			short period, int chargesNumber) {
		this.transactionId = transactionId;
		this.startDate = startDate;
		this.period = period;
		this.chargesNumber = chargesNumber;
	}

	@Id
	@Column(name = "TransactionID", unique = true, nullable = false)
	public long getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(long transactionId) {
		this.transactionId = transactionId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "StartDate", nullable = false, length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "Period", nullable = false)
	public short getPeriod() {
		return this.period;
	}

	public void setPeriod(short period) {
		this.period = period;
	}

	@Column(name = "ChargesNumber", nullable = false)
	public int getChargesNumber() {
		return this.chargesNumber;
	}

	public void setChargesNumber(int chargesNumber) {
		this.chargesNumber = chargesNumber;
	}

}
