package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PreForumUser generated by hbm2java
 */
@Entity
@Table(name = "pre_forum_user", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "user_email"))
public class PreForumUser implements java.io.Serializable {

	private String userName;
	private String userPwd;
	private String userEmail;
	private int userJoinDate;

	public PreForumUser() {
	}

	public PreForumUser(String userName, String userPwd, String userEmail,
			int userJoinDate) {
		this.userName = userName;
		this.userPwd = userPwd;
		this.userEmail = userEmail;
		this.userJoinDate = userJoinDate;
	}

	@Id
	@Column(name = "user_name", unique = true, nullable = false, length = 16)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_pwd", nullable = false, length = 32)
	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	@Column(name = "user_email", unique = true, nullable = false, length = 128)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_join_date", nullable = false)
	public int getUserJoinDate() {
		return this.userJoinDate;
	}

	public void setUserJoinDate(int userJoinDate) {
		this.userJoinDate = userJoinDate;
	}

}
