package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PreForumUserStat generated by hbm2java
 */
@Entity
@Table(name = "pre_forum_user_stat", catalog = "dolphin")
public class PreForumUserStat implements java.io.Serializable {

	private PreForumUserStatId id;

	public PreForumUserStat() {
	}

	public PreForumUserStat(PreForumUserStatId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "user", column = @Column(name = "user", nullable = false, length = 16)),
			@AttributeOverride(name = "posts", column = @Column(name = "posts", nullable = false)),
			@AttributeOverride(name = "userLastPost", column = @Column(name = "user_last_post", nullable = false)) })
	public PreForumUserStatId getId() {
		return this.id;
	}

	public void setId(PreForumUserStatId id) {
		this.id = id;
	}

}
