package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PreForumPost generated by hbm2java
 */
@Entity
@Table(name = "pre_forum_post", catalog = "dolphin")
public class PreForumPost implements java.io.Serializable {

	private Integer postId;
	private int topicId;
	private int forumId;
	private String user;
	private String postText;
	private int when;
	private int votes;
	private int reports;

	public PreForumPost() {
	}

	public PreForumPost(int topicId, int forumId, String user, String postText,
			int when, int votes, int reports) {
		this.topicId = topicId;
		this.forumId = forumId;
		this.user = user;
		this.postText = postText;
		this.when = when;
		this.votes = votes;
		this.reports = reports;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "post_id", unique = true, nullable = false)
	public Integer getPostId() {
		return this.postId;
	}

	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	@Column(name = "topic_id", nullable = false)
	public int getTopicId() {
		return this.topicId;
	}

	public void setTopicId(int topicId) {
		this.topicId = topicId;
	}

	@Column(name = "forum_id", nullable = false)
	public int getForumId() {
		return this.forumId;
	}

	public void setForumId(int forumId) {
		this.forumId = forumId;
	}

	@Column(name = "user", nullable = false, length = 32)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "post_text", nullable = false, length = 16777215)
	public String getPostText() {
		return this.postText;
	}

	public void setPostText(String postText) {
		this.postText = postText;
	}

	@Column(name = "when", nullable = false)
	public int getWhen() {
		return this.when;
	}

	public void setWhen(int when) {
		this.when = when;
	}

	@Column(name = "votes", nullable = false)
	public int getVotes() {
		return this.votes;
	}

	public void setVotes(int votes) {
		this.votes = votes;
	}

	@Column(name = "reports", nullable = false)
	public int getReports() {
		return this.reports;
	}

	public void setReports(int reports) {
		this.reports = reports;
	}

}
