package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PreForumUserStatId generated by hbm2java
 */
@Embeddable
public class PreForumUserStatId implements java.io.Serializable {

	private String user;
	private int posts;
	private int userLastPost;

	public PreForumUserStatId() {
	}

	public PreForumUserStatId(String user, int posts, int userLastPost) {
		this.user = user;
		this.posts = posts;
		this.userLastPost = userLastPost;
	}

	@Column(name = "user", nullable = false, length = 16)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "posts", nullable = false)
	public int getPosts() {
		return this.posts;
	}

	public void setPosts(int posts) {
		this.posts = posts;
	}

	@Column(name = "user_last_post", nullable = false)
	public int getUserLastPost() {
		return this.userLastPost;
	}

	public void setUserLastPost(int userLastPost) {
		this.userLastPost = userLastPost;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PreForumUserStatId))
			return false;
		PreForumUserStatId castOther = (PreForumUserStatId) other;

		return ((this.getUser() == castOther.getUser()) || (this.getUser() != null
				&& castOther.getUser() != null && this.getUser().equals(
				castOther.getUser())))
				&& (this.getPosts() == castOther.getPosts())
				&& (this.getUserLastPost() == castOther.getUserLastPost());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUser() == null ? 0 : this.getUser().hashCode());
		result = 37 * result + this.getPosts();
		result = 37 * result + this.getUserLastPost();
		return result;
	}

}
