package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PreValues generated by hbm2java
 */
@Entity
@Table(name = "PreValues", catalog = "dolphin")
public class PreValues implements java.io.Serializable {

	private PreValuesId id;

	public PreValues() {
	}

	public PreValues(PreValuesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "key", column = @Column(name = "Key", nullable = false)),
			@AttributeOverride(name = "value", column = @Column(name = "Value", nullable = false)),
			@AttributeOverride(name = "order", column = @Column(name = "Order", nullable = false)),
			@AttributeOverride(name = "lkey", column = @Column(name = "LKey", nullable = false)),
			@AttributeOverride(name = "lkey2", column = @Column(name = "LKey2", nullable = false)),
			@AttributeOverride(name = "lkey3", column = @Column(name = "LKey3", nullable = false)),
			@AttributeOverride(name = "extra", column = @Column(name = "Extra", nullable = false)),
			@AttributeOverride(name = "extra2", column = @Column(name = "Extra2", nullable = false)),
			@AttributeOverride(name = "extra3", column = @Column(name = "Extra3", nullable = false)) })
	public PreValuesId getId() {
		return this.id;
	}

	public void setId(PreValuesId id) {
		this.id = id;
	}

}
