package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PreValuesId generated by hbm2java
 */
@Embeddable
public class PreValuesId implements java.io.Serializable {

	private String key;
	private String value;
	private int order;
	private String lkey;
	private String lkey2;
	private String lkey3;
	private String extra;
	private String extra2;
	private String extra3;

	public PreValuesId() {
	}

	public PreValuesId(String key, String value, int order, String lkey,
			String lkey2, String lkey3, String extra, String extra2,
			String extra3) {
		this.key = key;
		this.value = value;
		this.order = order;
		this.lkey = lkey;
		this.lkey2 = lkey2;
		this.lkey3 = lkey3;
		this.extra = extra;
		this.extra2 = extra2;
		this.extra3 = extra3;
	}

	@Column(name = "Key", nullable = false)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "Value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "Order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "LKey", nullable = false)
	public String getLkey() {
		return this.lkey;
	}

	public void setLkey(String lkey) {
		this.lkey = lkey;
	}

	@Column(name = "LKey2", nullable = false)
	public String getLkey2() {
		return this.lkey2;
	}

	public void setLkey2(String lkey2) {
		this.lkey2 = lkey2;
	}

	@Column(name = "LKey3", nullable = false)
	public String getLkey3() {
		return this.lkey3;
	}

	public void setLkey3(String lkey3) {
		this.lkey3 = lkey3;
	}

	@Column(name = "Extra", nullable = false)
	public String getExtra() {
		return this.extra;
	}

	public void setExtra(String extra) {
		this.extra = extra;
	}

	@Column(name = "Extra2", nullable = false)
	public String getExtra2() {
		return this.extra2;
	}

	public void setExtra2(String extra2) {
		this.extra2 = extra2;
	}

	@Column(name = "Extra3", nullable = false)
	public String getExtra3() {
		return this.extra3;
	}

	public void setExtra3(String extra3) {
		this.extra3 = extra3;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PreValuesId))
			return false;
		PreValuesId castOther = (PreValuesId) other;

		return ((this.getKey() == castOther.getKey()) || (this.getKey() != null
				&& castOther.getKey() != null && this.getKey().equals(
				castOther.getKey())))
				&& ((this.getValue() == castOther.getValue()) || (this
						.getValue() != null
						&& castOther.getValue() != null && this.getValue()
						.equals(castOther.getValue())))
				&& (this.getOrder() == castOther.getOrder())
				&& ((this.getLkey() == castOther.getLkey()) || (this.getLkey() != null
						&& castOther.getLkey() != null && this.getLkey()
						.equals(castOther.getLkey())))
				&& ((this.getLkey2() == castOther.getLkey2()) || (this
						.getLkey2() != null
						&& castOther.getLkey2() != null && this.getLkey2()
						.equals(castOther.getLkey2())))
				&& ((this.getLkey3() == castOther.getLkey3()) || (this
						.getLkey3() != null
						&& castOther.getLkey3() != null && this.getLkey3()
						.equals(castOther.getLkey3())))
				&& ((this.getExtra() == castOther.getExtra()) || (this
						.getExtra() != null
						&& castOther.getExtra() != null && this.getExtra()
						.equals(castOther.getExtra())))
				&& ((this.getExtra2() == castOther.getExtra2()) || (this
						.getExtra2() != null
						&& castOther.getExtra2() != null && this.getExtra2()
						.equals(castOther.getExtra2())))
				&& ((this.getExtra3() == castOther.getExtra3()) || (this
						.getExtra3() != null
						&& castOther.getExtra3() != null && this.getExtra3()
						.equals(castOther.getExtra3())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKey() == null ? 0 : this.getKey().hashCode());
		result = 37 * result
				+ (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result + this.getOrder();
		result = 37 * result
				+ (getLkey() == null ? 0 : this.getLkey().hashCode());
		result = 37 * result
				+ (getLkey2() == null ? 0 : this.getLkey2().hashCode());
		result = 37 * result
				+ (getLkey3() == null ? 0 : this.getLkey3().hashCode());
		result = 37 * result
				+ (getExtra() == null ? 0 : this.getExtra().hashCode());
		result = 37 * result
				+ (getExtra2() == null ? 0 : this.getExtra2().hashCode());
		result = 37 * result
				+ (getExtra3() == null ? 0 : this.getExtra3().hashCode());
		return result;
	}

}
