package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrivPhotosRequests generated by hbm2java
 */
@Entity
@Table(name = "PrivPhotosRequests", catalog = "dolphin")
public class PrivPhotosRequests implements java.io.Serializable {

	private Integer idauto;
	private long idfrom;
	private long idto;
	private int grant;
	private byte hide;
	private Date arrived;

	public PrivPhotosRequests() {
	}

	public PrivPhotosRequests(long idfrom, long idto, int grant, byte hide,
			Date arrived) {
		this.idfrom = idfrom;
		this.idto = idto;
		this.grant = grant;
		this.hide = hide;
		this.arrived = arrived;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "IDauto", unique = true, nullable = false)
	public Integer getIdauto() {
		return this.idauto;
	}

	public void setIdauto(Integer idauto) {
		this.idauto = idauto;
	}

	@Column(name = "IDFrom", nullable = false)
	public long getIdfrom() {
		return this.idfrom;
	}

	public void setIdfrom(long idfrom) {
		this.idfrom = idfrom;
	}

	@Column(name = "IDTo", nullable = false)
	public long getIdto() {
		return this.idto;
	}

	public void setIdto(long idto) {
		this.idto = idto;
	}

	@Column(name = "Grant", nullable = false)
	public int getGrant() {
		return this.grant;
	}

	public void setGrant(int grant) {
		this.grant = grant;
	}

	@Column(name = "Hide", nullable = false)
	public byte getHide() {
		return this.hide;
	}

	public void setHide(byte hide) {
		this.hide = hide;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Arrived", nullable = false, length = 0)
	public Date getArrived() {
		return this.arrived;
	}

	public void setArrived(Date arrived) {
		this.arrived = arrived;
	}

}
