package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProfileMemLevels generated by hbm2java
 */
@Entity
@Table(name = "ProfileMemLevels", catalog = "dolphin")
public class ProfileMemLevels implements java.io.Serializable {

	private ProfileMemLevelsId id;
	private Date dateExpires;
	private Long transactionId;

	public ProfileMemLevels() {
	}

	public ProfileMemLevels(ProfileMemLevelsId id) {
		this.id = id;
	}

	public ProfileMemLevels(ProfileMemLevelsId id, Date dateExpires,
			Long transactionId) {
		this.id = id;
		this.dateExpires = dateExpires;
		this.transactionId = transactionId;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idmember", column = @Column(name = "IDMember", nullable = false)),
			@AttributeOverride(name = "idlevel", column = @Column(name = "IDLevel", nullable = false)),
			@AttributeOverride(name = "dateStarts", column = @Column(name = "DateStarts", nullable = false, length = 0)) })
	public ProfileMemLevelsId getId() {
		return this.id;
	}

	public void setId(ProfileMemLevelsId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateExpires", length = 0)
	public Date getDateExpires() {
		return this.dateExpires;
	}

	public void setDateExpires(Date dateExpires) {
		this.dateExpires = dateExpires;
	}

	@Column(name = "TransactionID")
	public Long getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Long transactionId) {
		this.transactionId = transactionId;
	}

}
