package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProfilesSettingsId generated by hbm2java
 */
@Embeddable
public class ProfilesSettingsId implements java.io.Serializable {

	private int idmember;
	private String backgroundFilename;
	private String backgroundColor;
	private String fontColor;
	private String fontSize;
	private String fontFamily;
	private String status;

	public ProfilesSettingsId() {
	}

	public ProfilesSettingsId(int idmember) {
		this.idmember = idmember;
	}

	public ProfilesSettingsId(int idmember, String backgroundFilename,
			String backgroundColor, String fontColor, String fontSize,
			String fontFamily, String status) {
		this.idmember = idmember;
		this.backgroundFilename = backgroundFilename;
		this.backgroundColor = backgroundColor;
		this.fontColor = fontColor;
		this.fontSize = fontSize;
		this.fontFamily = fontFamily;
		this.status = status;
	}

	@Column(name = "IDMember", unique = true, nullable = false)
	public int getIdmember() {
		return this.idmember;
	}

	public void setIdmember(int idmember) {
		this.idmember = idmember;
	}

	@Column(name = "BackgroundFilename", length = 40)
	public String getBackgroundFilename() {
		return this.backgroundFilename;
	}

	public void setBackgroundFilename(String backgroundFilename) {
		this.backgroundFilename = backgroundFilename;
	}

	@Column(name = "BackgroundColor", length = 60)
	public String getBackgroundColor() {
		return this.backgroundColor;
	}

	public void setBackgroundColor(String backgroundColor) {
		this.backgroundColor = backgroundColor;
	}

	@Column(name = "FontColor", length = 60)
	public String getFontColor() {
		return this.fontColor;
	}

	public void setFontColor(String fontColor) {
		this.fontColor = fontColor;
	}

	@Column(name = "FontSize", length = 60)
	public String getFontSize() {
		return this.fontSize;
	}

	public void setFontSize(String fontSize) {
		this.fontSize = fontSize;
	}

	@Column(name = "FontFamily", length = 60)
	public String getFontFamily() {
		return this.fontFamily;
	}

	public void setFontFamily(String fontFamily) {
		this.fontFamily = fontFamily;
	}

	@Column(name = "Status", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProfilesSettingsId))
			return false;
		ProfilesSettingsId castOther = (ProfilesSettingsId) other;

		return (this.getIdmember() == castOther.getIdmember())
				&& ((this.getBackgroundFilename() == castOther
						.getBackgroundFilename()) || (this
						.getBackgroundFilename() != null
						&& castOther.getBackgroundFilename() != null && this
						.getBackgroundFilename().equals(
								castOther.getBackgroundFilename())))
				&& ((this.getBackgroundColor() == castOther
						.getBackgroundColor()) || (this.getBackgroundColor() != null
						&& castOther.getBackgroundColor() != null && this
						.getBackgroundColor().equals(
								castOther.getBackgroundColor())))
				&& ((this.getFontColor() == castOther.getFontColor()) || (this
						.getFontColor() != null
						&& castOther.getFontColor() != null && this
						.getFontColor().equals(castOther.getFontColor())))
				&& ((this.getFontSize() == castOther.getFontSize()) || (this
						.getFontSize() != null
						&& castOther.getFontSize() != null && this
						.getFontSize().equals(castOther.getFontSize())))
				&& ((this.getFontFamily() == castOther.getFontFamily()) || (this
						.getFontFamily() != null
						&& castOther.getFontFamily() != null && this
						.getFontFamily().equals(castOther.getFontFamily())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus()
						.equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdmember();
		result = 37
				* result
				+ (getBackgroundFilename() == null ? 0 : this
						.getBackgroundFilename().hashCode());
		result = 37
				* result
				+ (getBackgroundColor() == null ? 0 : this.getBackgroundColor()
						.hashCode());
		result = 37 * result
				+ (getFontColor() == null ? 0 : this.getFontColor().hashCode());
		result = 37 * result
				+ (getFontSize() == null ? 0 : this.getFontSize().hashCode());
		result = 37
				* result
				+ (getFontFamily() == null ? 0 : this.getFontFamily()
						.hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
