package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProfileVotingTrackId generated by hbm2java
 */
@Embeddable
public class ProfileVotingTrackId implements java.io.Serializable {

	private long prId;
	private String prIp;
	private Date prDate;

	public ProfileVotingTrackId() {
	}

	public ProfileVotingTrackId(long prId) {
		this.prId = prId;
	}

	public ProfileVotingTrackId(long prId, String prIp, Date prDate) {
		this.prId = prId;
		this.prIp = prIp;
		this.prDate = prDate;
	}

	@Column(name = "pr_id", nullable = false)
	public long getPrId() {
		return this.prId;
	}

	public void setPrId(long prId) {
		this.prId = prId;
	}

	@Column(name = "pr_ip", length = 20)
	public String getPrIp() {
		return this.prIp;
	}

	public void setPrIp(String prIp) {
		this.prIp = prIp;
	}

	@Column(name = "pr_date", length = 0)
	public Date getPrDate() {
		return this.prDate;
	}

	public void setPrDate(Date prDate) {
		this.prDate = prDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProfileVotingTrackId))
			return false;
		ProfileVotingTrackId castOther = (ProfileVotingTrackId) other;

		return (this.getPrId() == castOther.getPrId())
				&& ((this.getPrIp() == castOther.getPrIp()) || (this.getPrIp() != null
						&& castOther.getPrIp() != null && this.getPrIp()
						.equals(castOther.getPrIp())))
				&& ((this.getPrDate() == castOther.getPrDate()) || (this
						.getPrDate() != null
						&& castOther.getPrDate() != null && this.getPrDate()
						.equals(castOther.getPrDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPrId();
		result = 37 * result
				+ (getPrIp() == null ? 0 : this.getPrIp().hashCode());
		result = 37 * result
				+ (getPrDate() == null ? 0 : this.getPrDate().hashCode());
		return result;
	}

}
