package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProfilesPolls generated by hbm2java
 */
@Entity
@Table(name = "ProfilesPolls", catalog = "dolphin")
public class ProfilesPolls implements java.io.Serializable {

	private Integer idPoll;
	private int idProfile;
	private String pollQuestion;
	private String pollAnswers;
	private String pollResults;
	private int pollTotalVotes;
	private String pollStatus;
	private byte pollApproval;

	public ProfilesPolls() {
	}

	public ProfilesPolls(int idProfile, String pollQuestion,
			String pollAnswers, String pollResults, int pollTotalVotes,
			String pollStatus, byte pollApproval) {
		this.idProfile = idProfile;
		this.pollQuestion = pollQuestion;
		this.pollAnswers = pollAnswers;
		this.pollResults = pollResults;
		this.pollTotalVotes = pollTotalVotes;
		this.pollStatus = pollStatus;
		this.pollApproval = pollApproval;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_poll", unique = true, nullable = false)
	public Integer getIdPoll() {
		return this.idPoll;
	}

	public void setIdPoll(Integer idPoll) {
		this.idPoll = idPoll;
	}

	@Column(name = "id_profile", nullable = false)
	public int getIdProfile() {
		return this.idProfile;
	}

	public void setIdProfile(int idProfile) {
		this.idProfile = idProfile;
	}

	@Column(name = "poll_question", nullable = false)
	public String getPollQuestion() {
		return this.pollQuestion;
	}

	public void setPollQuestion(String pollQuestion) {
		this.pollQuestion = pollQuestion;
	}

	@Column(name = "poll_answers", nullable = false, length = 65535)
	public String getPollAnswers() {
		return this.pollAnswers;
	}

	public void setPollAnswers(String pollAnswers) {
		this.pollAnswers = pollAnswers;
	}

	@Column(name = "poll_results", nullable = false, length = 60)
	public String getPollResults() {
		return this.pollResults;
	}

	public void setPollResults(String pollResults) {
		this.pollResults = pollResults;
	}

	@Column(name = "poll_total_votes", nullable = false)
	public int getPollTotalVotes() {
		return this.pollTotalVotes;
	}

	public void setPollTotalVotes(int pollTotalVotes) {
		this.pollTotalVotes = pollTotalVotes;
	}

	@Column(name = "poll_status", nullable = false, length = 20)
	public String getPollStatus() {
		return this.pollStatus;
	}

	public void setPollStatus(String pollStatus) {
		this.pollStatus = pollStatus;
	}

	@Column(name = "poll_approval", nullable = false)
	public byte getPollApproval() {
		return this.pollApproval;
	}

	public void setPollApproval(byte pollApproval) {
		this.pollApproval = pollApproval;
	}

}
