package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProfileVotingTrack generated by hbm2java
 */
@Entity
@Table(name = "profile_voting_track", catalog = "dolphin")
public class ProfileVotingTrack implements java.io.Serializable {

	private ProfileVotingTrackId id;

	public ProfileVotingTrack() {
	}

	public ProfileVotingTrack(ProfileVotingTrackId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "prId", column = @Column(name = "pr_id", nullable = false)),
			@AttributeOverride(name = "prIp", column = @Column(name = "pr_ip", length = 20)),
			@AttributeOverride(name = "prDate", column = @Column(name = "pr_date", length = 0)) })
	public ProfileVotingTrackId getId() {
		return this.id;
	}

	public void setId(ProfileVotingTrackId id) {
		this.id = id;
	}

}
