package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProfileRatingId generated by hbm2java
 */
@Embeddable
public class ProfileRatingId implements java.io.Serializable {

	private long prId;
	private int prRatingCount;
	private int prRatingSum;

	public ProfileRatingId() {
	}

	public ProfileRatingId(long prId, int prRatingCount, int prRatingSum) {
		this.prId = prId;
		this.prRatingCount = prRatingCount;
		this.prRatingSum = prRatingSum;
	}

	@Column(name = "pr_id", unique = true, nullable = false)
	public long getPrId() {
		return this.prId;
	}

	public void setPrId(long prId) {
		this.prId = prId;
	}

	@Column(name = "pr_rating_count", nullable = false)
	public int getPrRatingCount() {
		return this.prRatingCount;
	}

	public void setPrRatingCount(int prRatingCount) {
		this.prRatingCount = prRatingCount;
	}

	@Column(name = "pr_rating_sum", nullable = false)
	public int getPrRatingSum() {
		return this.prRatingSum;
	}

	public void setPrRatingSum(int prRatingSum) {
		this.prRatingSum = prRatingSum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProfileRatingId))
			return false;
		ProfileRatingId castOther = (ProfileRatingId) other;

		return (this.getPrId() == castOther.getPrId())
				&& (this.getPrRatingCount() == castOther.getPrRatingCount())
				&& (this.getPrRatingSum() == castOther.getPrRatingSum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPrId();
		result = 37 * result + this.getPrRatingCount();
		result = 37 * result + this.getPrRatingSum();
		return result;
	}

}
