package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProfileRating generated by hbm2java
 */
@Entity
@Table(name = "profile_rating", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "pr_id"))
public class ProfileRating implements java.io.Serializable {

	private ProfileRatingId id;

	public ProfileRating() {
	}

	public ProfileRating(ProfileRatingId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "prId", column = @Column(name = "pr_id", unique = true, nullable = false)),
			@AttributeOverride(name = "prRatingCount", column = @Column(name = "pr_rating_count", nullable = false)),
			@AttributeOverride(name = "prRatingSum", column = @Column(name = "pr_rating_sum", nullable = false)) })
	public ProfileRatingId getId() {
		return this.id;
	}

	public void setId(ProfileRatingId id) {
		this.id = id;
	}

}
