package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RayBoardBoards generated by hbm2java
 */
@Entity
@Table(name = "RayBoardBoards", catalog = "dolphin")
public class RayBoardBoards implements java.io.Serializable {

	private Integer id;
	private String userId;
	private String title;
	private int track;

	public RayBoardBoards() {
	}

	public RayBoardBoards(String userId, String title, int track) {
		this.userId = userId;
		this.title = title;
		this.track = track;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "UserID", nullable = false, length = 64)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "Title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Track", nullable = false)
	public int getTrack() {
		return this.track;
	}

	public void setTrack(int track) {
		this.track = track;
	}

}
