package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RayChatRoomsUsers generated by hbm2java
 */
@Entity
@Table(name = "RayChatRoomsUsers", catalog = "dolphin")
public class RayChatRoomsUsers implements java.io.Serializable {

	private Integer id;
	private int room;
	private String user;
	private Integer when;
	private String status;

	public RayChatRoomsUsers() {
	}

	public RayChatRoomsUsers(int room, String user, String status) {
		this.room = room;
		this.user = user;
		this.status = status;
	}

	public RayChatRoomsUsers(int room, String user, Integer when, String status) {
		this.room = room;
		this.user = user;
		this.when = when;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Room", nullable = false)
	public int getRoom() {
		return this.room;
	}

	public void setRoom(int room) {
		this.room = room;
	}

	@Column(name = "User", nullable = false, length = 20)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "When")
	public Integer getWhen() {
		return this.when;
	}

	public void setWhen(Integer when) {
		this.when = when;
	}

	@Column(name = "Status", nullable = false, length = 7)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
