package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RayMoviePlayListsId generated by hbm2java
 */
@Embeddable
public class RayMoviePlayListsId implements java.io.Serializable {

	private int fileId;
	private String owner;
	private byte order;

	public RayMoviePlayListsId() {
	}

	public RayMoviePlayListsId(int fileId, String owner, byte order) {
		this.fileId = fileId;
		this.owner = owner;
		this.order = order;
	}

	@Column(name = "FileId", nullable = false)
	public int getFileId() {
		return this.fileId;
	}

	public void setFileId(int fileId) {
		this.fileId = fileId;
	}

	@Column(name = "Owner", nullable = false, length = 64)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "Order", nullable = false)
	public byte getOrder() {
		return this.order;
	}

	public void setOrder(byte order) {
		this.order = order;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RayMoviePlayListsId))
			return false;
		RayMoviePlayListsId castOther = (RayMoviePlayListsId) other;

		return (this.getFileId() == castOther.getFileId())
				&& ((this.getOwner() == castOther.getOwner()) || (this
						.getOwner() != null
						&& castOther.getOwner() != null && this.getOwner()
						.equals(castOther.getOwner())))
				&& (this.getOrder() == castOther.getOrder());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFileId();
		result = 37 * result
				+ (getOwner() == null ? 0 : this.getOwner().hashCode());
		result = 37 * result + this.getOrder();
		return result;
	}

}
