package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RayMp3playLists generated by hbm2java
 */
@Entity
@Table(name = "RayMp3PlayLists", catalog = "dolphin")
public class RayMp3playLists implements java.io.Serializable {

	private RayMp3playListsId id;

	public RayMp3playLists() {
	}

	public RayMp3playLists(RayMp3playListsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "fileId", column = @Column(name = "FileId", nullable = false)),
			@AttributeOverride(name = "owner", column = @Column(name = "Owner", nullable = false, length = 64)),
			@AttributeOverride(name = "order", column = @Column(name = "Order", nullable = false)) })
	public RayMp3playListsId getId() {
		return this.id;
	}

	public void setId(RayMp3playListsId id) {
		this.id = id;
	}

}
