package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RayMovieFiles generated by hbm2java
 */
@Entity
@Table(name = "RayMovieFiles", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "Uri"))
public class RayMovieFiles implements java.io.Serializable {

	private Integer id;
	private int categoryId;
	private String title;
	private String uri;
	private String tags;
	private String description;
	private int time;
	private int date;
	private int reports;
	private String owner;
	private Integer views;
	private String approved;

	public RayMovieFiles() {
	}

	public RayMovieFiles(int categoryId, String title, String uri, String tags,
			String description, int time, int date, int reports, String owner,
			String approved) {
		this.categoryId = categoryId;
		this.title = title;
		this.uri = uri;
		this.tags = tags;
		this.description = description;
		this.time = time;
		this.date = date;
		this.reports = reports;
		this.owner = owner;
		this.approved = approved;
	}

	public RayMovieFiles(int categoryId, String title, String uri, String tags,
			String description, int time, int date, int reports, String owner,
			Integer views, String approved) {
		this.categoryId = categoryId;
		this.title = title;
		this.uri = uri;
		this.tags = tags;
		this.description = description;
		this.time = time;
		this.date = date;
		this.reports = reports;
		this.owner = owner;
		this.views = views;
		this.approved = approved;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "CategoryId", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "Title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Uri", unique = true, nullable = false)
	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	@Column(name = "Tags", nullable = false, length = 65535)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@Column(name = "Description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Time", nullable = false)
	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	@Column(name = "Date", nullable = false)
	public int getDate() {
		return this.date;
	}

	public void setDate(int date) {
		this.date = date;
	}

	@Column(name = "Reports", nullable = false)
	public int getReports() {
		return this.reports;
	}

	public void setReports(int reports) {
		this.reports = reports;
	}

	@Column(name = "Owner", nullable = false, length = 64)
	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	@Column(name = "Views")
	public Integer getViews() {
		return this.views;
	}

	public void setViews(Integer views) {
		this.views = views;
	}

	@Column(name = "Approved", nullable = false, length = 5)
	public String getApproved() {
		return this.approved;
	}

	public void setApproved(String approved) {
		this.approved = approved;
	}

}
