package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SdatingMatches generated by hbm2java
 */
@Entity
@Table(name = "SDatingMatches", catalog = "dolphin")
public class SdatingMatches implements java.io.Serializable {

	private SdatingMatchesId id;

	public SdatingMatches() {
	}

	public SdatingMatches(SdatingMatchesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idchooser", column = @Column(name = "IDChooser", nullable = false)),
			@AttributeOverride(name = "idchosen", column = @Column(name = "IDChosen", nullable = false)) })
	public SdatingMatchesId getId() {
		return this.id;
	}

	public void setId(SdatingMatchesId id) {
		this.id = id;
	}

}
