package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Shoutbox generated by hbm2java
 */
@Entity
@Table(name = "shoutbox", catalog = "dolphin")
public class Shoutbox implements java.io.Serializable {

	private Date date;
	private long id;
	private String text;
	private String class_;

	public Shoutbox() {
	}

	public Shoutbox(Date date, long id, String text, String class_) {
		this.date = date;
		this.id = id;
		this.text = text;
		this.class_ = class_;
	}

	@Id
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", unique = true, nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "id", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "text", nullable = false, length = 120)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "class", nullable = false, length = 16)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

}
