package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Smiles generated by hbm2java
 */
@Entity
@Table(name = "smiles", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Smiles implements java.io.Serializable {

	private int id;
	private String code;
	private String smileUrl;
	private String emoticon;

	public Smiles() {
	}

	public Smiles(int id, String code, String smileUrl, String emoticon) {
		this.id = id;
		this.code = code;
		this.smileUrl = smileUrl;
		this.emoticon = emoticon;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, nullable = false, length = 8)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "smile_url", nullable = false)
	public String getSmileUrl() {
		return this.smileUrl;
	}

	public void setSmileUrl(String smileUrl) {
		this.smileUrl = smileUrl;
	}

	@Column(name = "emoticon", nullable = false)
	public String getEmoticon() {
		return this.emoticon;
	}

	public void setEmoticon(String emoticon) {
		this.emoticon = emoticon;
	}

}
