package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stories generated by hbm2java
 */
@Entity
@Table(name = "Stories", catalog = "dolphin")
public class Stories implements java.io.Serializable {

	private Integer id;
	private Date date;
	private long sender;
	private String header;
	private String text;
	private String active;

	public Stories() {
	}

	public Stories(Date date, long sender, String header, String text,
			String active) {
		this.date = date;
		this.sender = sender;
		this.header = header;
		this.text = text;
		this.active = active;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Sender", nullable = false)
	public long getSender() {
		return this.sender;
	}

	public void setSender(long sender) {
		this.sender = sender;
	}

	@Column(name = "Header", nullable = false, length = 50)
	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	@Column(name = "Text", nullable = false)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "active", nullable = false, length = 4)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

}
