package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TagsId generated by hbm2java
 */
@Embeddable
public class TagsId implements java.io.Serializable {

	private String tag;
	private long id;
	private String type;

	public TagsId() {
	}

	public TagsId(String tag, long id, String type) {
		this.tag = tag;
		this.id = id;
		this.type = type;
	}

	@Column(name = "Tag", nullable = false, length = 32)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "ID", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "Type", nullable = false, length = 8)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TagsId))
			return false;
		TagsId castOther = (TagsId) other;

		return ((this.getTag() == castOther.getTag()) || (this.getTag() != null
				&& castOther.getTag() != null && this.getTag().equals(
				castOther.getTag())))
				&& (this.getId() == castOther.getId())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTag() == null ? 0 : this.getTag().hashCode());
		result = 37 * result + (int) this.getId();
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		return result;
	}

}
