package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VotesId generated by hbm2java
 */
@Embeddable
public class VotesId implements java.io.Serializable {

	private long member;
	private int mark;
	private String ip;
	private Date date;

	public VotesId() {
	}

	public VotesId(long member, int mark, String ip, Date date) {
		this.member = member;
		this.mark = mark;
		this.ip = ip;
		this.date = date;
	}

	@Column(name = "Member", nullable = false)
	public long getMember() {
		return this.member;
	}

	public void setMember(long member) {
		this.member = member;
	}

	@Column(name = "Mark", nullable = false)
	public int getMark() {
		return this.mark;
	}

	public void setMark(int mark) {
		this.mark = mark;
	}

	@Column(name = "IP", nullable = false, length = 18)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "Date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VotesId))
			return false;
		VotesId castOther = (VotesId) other;

		return (this.getMember() == castOther.getMember())
				&& (this.getMark() == castOther.getMark())
				&& ((this.getIp() == castOther.getIp()) || (this.getIp() != null
						&& castOther.getIp() != null && this.getIp().equals(
						castOther.getIp())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMember();
		result = 37 * result + this.getMark();
		result = 37 * result + (getIp() == null ? 0 : this.getIp().hashCode());
		result = 37 * result
				+ (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
