package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AdminBanList generated by hbm2java
 */
@Entity
@Table(name = "AdminBanList", catalog = "dolphin")
public class AdminBanList implements java.io.Serializable {

	private AdminBanListId id;

	public AdminBanList() {
	}

	public AdminBanList(AdminBanListId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "profId", column = @Column(name = "ProfID", nullable = false)),
			@AttributeOverride(name = "time", column = @Column(name = "Time", nullable = false)),
			@AttributeOverride(name = "dateTime", column = @Column(name = "DateTime", nullable = false, length = 0)) })
	public AdminBanListId getId() {
		return this.id;
	}

	public void setId(AdminBanListId id) {
		this.id = id;
	}

}
