package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AdminMenuCateg generated by hbm2java
 */
@Entity
@Table(name = "AdminMenuCateg", catalog = "dolphin")
public class AdminMenuCateg implements java.io.Serializable {

	private Integer id;
	private String title;
	private int order;
	private String icon;
	private String iconThumb;
	private String user;

	public AdminMenuCateg() {
	}

	public AdminMenuCateg(String title, int order, String icon,
			String iconThumb, String user) {
		this.title = title;
		this.order = order;
		this.icon = icon;
		this.iconThumb = iconThumb;
		this.user = user;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Title", nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "Order", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

	@Column(name = "Icon", nullable = false, length = 50)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "Icon_thumb", nullable = false, length = 50)
	public String getIconThumb() {
		return this.iconThumb;
	}

	public void setIconThumb(String iconThumb) {
		this.iconThumb = iconThumb;
	}

	@Column(name = "User", nullable = false, length = 9)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
