package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AffBanners generated by hbm2java
 */
@Entity
@Table(name = "aff_banners", catalog = "dolphin")
public class AffBanners implements java.io.Serializable {

	private Integer id;
	private short xsize;
	private short ysize;
	private String banner;
	private String bannerName;
	private String text;
	private byte added;
	private String status;

	public AffBanners() {
	}

	public AffBanners(short xsize, short ysize, String banner,
			String bannerName, String text, byte added, String status) {
		this.xsize = xsize;
		this.ysize = ysize;
		this.banner = banner;
		this.bannerName = bannerName;
		this.text = text;
		this.added = added;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "XSize", nullable = false)
	public short getXsize() {
		return this.xsize;
	}

	public void setXsize(short xsize) {
		this.xsize = xsize;
	}

	@Column(name = "YSize", nullable = false)
	public short getYsize() {
		return this.ysize;
	}

	public void setYsize(short ysize) {
		this.ysize = ysize;
	}

	@Column(name = "Banner", nullable = false, length = 32)
	public String getBanner() {
		return this.banner;
	}

	public void setBanner(String banner) {
		this.banner = banner;
	}

	@Column(name = "BannerName", nullable = false, length = 32)
	public String getBannerName() {
		return this.bannerName;
	}

	public void setBannerName(String bannerName) {
		this.bannerName = bannerName;
	}

	@Column(name = "Text", nullable = false, length = 65535)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "Added", nullable = false)
	public byte getAdded() {
		return this.added;
	}

	public void setAdded(byte added) {
		this.added = added;
	}

	@Column(name = "Status", nullable = false, length = 9)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
