package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AffMembers generated by hbm2java
 */
@Entity
@Table(name = "aff_members", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "idProfile"))
public class AffMembers implements java.io.Serializable {

	private AffMembersId id;

	public AffMembers() {
	}

	public AffMembers(AffMembersId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idAff", column = @Column(name = "idAff", nullable = false)),
			@AttributeOverride(name = "idProfile", column = @Column(name = "idProfile", unique = true, nullable = false)) })
	public AffMembersId getId() {
		return this.id;
	}

	public void setId(AffMembersId id) {
		this.id = id;
	}

}
