package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AffMembersId generated by hbm2java
 */
@Embeddable
public class AffMembersId implements java.io.Serializable {

	private long idAff;
	private long idProfile;

	public AffMembersId() {
	}

	public AffMembersId(long idAff, long idProfile) {
		this.idAff = idAff;
		this.idProfile = idProfile;
	}

	@Column(name = "idAff", nullable = false)
	public long getIdAff() {
		return this.idAff;
	}

	public void setIdAff(long idAff) {
		this.idAff = idAff;
	}

	@Column(name = "idProfile", unique = true, nullable = false)
	public long getIdProfile() {
		return this.idProfile;
	}

	public void setIdProfile(long idProfile) {
		this.idProfile = idProfile;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AffMembersId))
			return false;
		AffMembersId castOther = (AffMembersId) other;

		return (this.getIdAff() == castOther.getIdAff())
				&& (this.getIdProfile() == castOther.getIdProfile());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdAff();
		result = 37 * result + (int) this.getIdProfile();
		return result;
	}

}
