package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BlockListId generated by hbm2java
 */
@Embeddable
public class BlockListId implements java.io.Serializable {

	private long id;
	private long profile;

	public BlockListId() {
	}

	public BlockListId(long id, long profile) {
		this.id = id;
		this.profile = profile;
	}

	@Column(name = "ID", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "Profile", nullable = false)
	public long getProfile() {
		return this.profile;
	}

	public void setProfile(long profile) {
		this.profile = profile;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BlockListId))
			return false;
		BlockListId castOther = (BlockListId) other;

		return (this.getId() == castOther.getId())
				&& (this.getProfile() == castOther.getProfile());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (int) this.getProfile();
		return result;
	}

}
