package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BoughtContacts generated by hbm2java
 */
@Entity
@Table(name = "BoughtContacts", catalog = "dolphin")
public class BoughtContacts implements java.io.Serializable {

	private BoughtContactsId id;
	private Long transactionId;
	private boolean hideFromBuyer;
	private boolean hideFromContact;

	public BoughtContacts() {
	}

	public BoughtContacts(BoughtContactsId id, boolean hideFromBuyer,
			boolean hideFromContact) {
		this.id = id;
		this.hideFromBuyer = hideFromBuyer;
		this.hideFromContact = hideFromContact;
	}

	public BoughtContacts(BoughtContactsId id, Long transactionId,
			boolean hideFromBuyer, boolean hideFromContact) {
		this.id = id;
		this.transactionId = transactionId;
		this.hideFromBuyer = hideFromBuyer;
		this.hideFromContact = hideFromContact;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idbuyer", column = @Column(name = "IDBuyer", nullable = false)),
			@AttributeOverride(name = "idcontact", column = @Column(name = "IDContact", nullable = false)) })
	public BoughtContactsId getId() {
		return this.id;
	}

	public void setId(BoughtContactsId id) {
		this.id = id;
	}

	@Column(name = "TransactionID")
	public Long getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Long transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "HideFromBuyer", nullable = false)
	public boolean isHideFromBuyer() {
		return this.hideFromBuyer;
	}

	public void setHideFromBuyer(boolean hideFromBuyer) {
		this.hideFromBuyer = hideFromBuyer;
	}

	@Column(name = "HideFromContact", nullable = false)
	public boolean isHideFromContact() {
		return this.hideFromContact;
	}

	public void setHideFromContact(boolean hideFromContact) {
		this.hideFromContact = hideFromContact;
	}

}
