package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Classifieds generated by hbm2java
 */
@Entity
@Table(name = "Classifieds", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "CEntryUri"))
public class Classifieds implements java.io.Serializable {

	private Integer id;
	private String name;
	private String centryUri;
	private String description;
	private String customFieldName1;
	private String customFieldName2;
	private String customAction1;
	private String customAction2;
	private String unit;

	public Classifieds() {
	}

	public Classifieds(String name, String centryUri, String unit) {
		this.name = name;
		this.centryUri = centryUri;
		this.unit = unit;
	}

	public Classifieds(String name, String centryUri, String description,
			String customFieldName1, String customFieldName2,
			String customAction1, String customAction2, String unit) {
		this.name = name;
		this.centryUri = centryUri;
		this.description = description;
		this.customFieldName1 = customFieldName1;
		this.customFieldName2 = customFieldName2;
		this.customAction1 = customAction1;
		this.customAction2 = customAction2;
		this.unit = unit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "CEntryUri", unique = true, nullable = false, length = 64)
	public String getCentryUri() {
		return this.centryUri;
	}

	public void setCentryUri(String centryUri) {
		this.centryUri = centryUri;
	}

	@Column(name = "Description", length = 128)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CustomFieldName1", length = 50)
	public String getCustomFieldName1() {
		return this.customFieldName1;
	}

	public void setCustomFieldName1(String customFieldName1) {
		this.customFieldName1 = customFieldName1;
	}

	@Column(name = "CustomFieldName2", length = 50)
	public String getCustomFieldName2() {
		return this.customFieldName2;
	}

	public void setCustomFieldName2(String customFieldName2) {
		this.customFieldName2 = customFieldName2;
	}

	@Column(name = "CustomAction1", length = 10)
	public String getCustomAction1() {
		return this.customAction1;
	}

	public void setCustomAction1(String customAction1) {
		this.customAction1 = customAction1;
	}

	@Column(name = "CustomAction2", length = 10)
	public String getCustomAction2() {
		return this.customAction2;
	}

	public void setCustomAction2(String customAction2) {
		this.customAction2 = customAction2;
	}

	@Column(name = "Unit", nullable = false, length = 8)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

}
