package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ClassifiedsAdvertisements generated by hbm2java
 */
@Entity
@Table(name = "ClassifiedsAdvertisements", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "EntryUri"))
public class ClassifiedsAdvertisements implements java.io.Serializable {

	private Integer id;
	private int idprofile;
	private int idclassifiedsSubs;
	private Date dateTime;
	private String subject;
	private String entryUri;
	private String message;
	private String status;
	private String customFieldValue1;
	private String customFieldValue2;
	private int lifeTime;
	private String media;
	private String tags;

	public ClassifiedsAdvertisements() {
	}

	public ClassifiedsAdvertisements(int idprofile, int idclassifiedsSubs,
			Date dateTime, String subject, String entryUri, String message,
			String status, int lifeTime, String tags) {
		this.idprofile = idprofile;
		this.idclassifiedsSubs = idclassifiedsSubs;
		this.dateTime = dateTime;
		this.subject = subject;
		this.entryUri = entryUri;
		this.message = message;
		this.status = status;
		this.lifeTime = lifeTime;
		this.tags = tags;
	}

	public ClassifiedsAdvertisements(int idprofile, int idclassifiedsSubs,
			Date dateTime, String subject, String entryUri, String message,
			String status, String customFieldValue1, String customFieldValue2,
			int lifeTime, String media, String tags) {
		this.idprofile = idprofile;
		this.idclassifiedsSubs = idclassifiedsSubs;
		this.dateTime = dateTime;
		this.subject = subject;
		this.entryUri = entryUri;
		this.message = message;
		this.status = status;
		this.customFieldValue1 = customFieldValue1;
		this.customFieldValue2 = customFieldValue2;
		this.lifeTime = lifeTime;
		this.media = media;
		this.tags = tags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "IDProfile", nullable = false)
	public int getIdprofile() {
		return this.idprofile;
	}

	public void setIdprofile(int idprofile) {
		this.idprofile = idprofile;
	}

	@Column(name = "IDClassifiedsSubs", nullable = false)
	public int getIdclassifiedsSubs() {
		return this.idclassifiedsSubs;
	}

	public void setIdclassifiedsSubs(int idclassifiedsSubs) {
		this.idclassifiedsSubs = idclassifiedsSubs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateTime", nullable = false, length = 0)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "Subject", nullable = false, length = 50)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "EntryUri", unique = true, nullable = false, length = 50)
	public String getEntryUri() {
		return this.entryUri;
	}

	public void setEntryUri(String entryUri) {
		this.entryUri = entryUri;
	}

	@Column(name = "Message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "Status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "CustomFieldValue1", length = 50)
	public String getCustomFieldValue1() {
		return this.customFieldValue1;
	}

	public void setCustomFieldValue1(String customFieldValue1) {
		this.customFieldValue1 = customFieldValue1;
	}

	@Column(name = "CustomFieldValue2", length = 50)
	public String getCustomFieldValue2() {
		return this.customFieldValue2;
	}

	public void setCustomFieldValue2(String customFieldValue2) {
		this.customFieldValue2 = customFieldValue2;
	}

	@Column(name = "LifeTime", nullable = false)
	public int getLifeTime() {
		return this.lifeTime;
	}

	public void setLifeTime(int lifeTime) {
		this.lifeTime = lifeTime;
	}

	@Column(name = "Media", length = 50)
	public String getMedia() {
		return this.media;
	}

	public void setMedia(String media) {
		this.media = media;
	}

	@Column(name = "Tags", nullable = false, length = 65535)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

}
