package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ClassifiedsSubs generated by hbm2java
 */
@Entity
@Table(name = "ClassifiedsSubs", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "SEntryUri"))
public class ClassifiedsSubs implements java.io.Serializable {

	private Integer id;
	private Integer idclassified;
	private String nameSub;
	private String sentryUri;
	private String description;

	public ClassifiedsSubs() {
	}

	public ClassifiedsSubs(String nameSub, String sentryUri) {
		this.nameSub = nameSub;
		this.sentryUri = sentryUri;
	}

	public ClassifiedsSubs(Integer idclassified, String nameSub,
			String sentryUri, String description) {
		this.idclassified = idclassified;
		this.nameSub = nameSub;
		this.sentryUri = sentryUri;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "IDClassified")
	public Integer getIdclassified() {
		return this.idclassified;
	}

	public void setIdclassified(Integer idclassified) {
		this.idclassified = idclassified;
	}

	@Column(name = "NameSub", nullable = false, length = 128)
	public String getNameSub() {
		return this.nameSub;
	}

	public void setNameSub(String nameSub) {
		this.nameSub = nameSub;
	}

	@Column(name = "SEntryUri", unique = true, nullable = false, length = 128)
	public String getSentryUri() {
		return this.sentryUri;
	}

	public void setSentryUri(String sentryUri) {
		this.sentryUri = sentryUri;
	}

	@Column(name = "Description", length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
