package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmtsSharedVideo generated by hbm2java
 */
@Entity
@Table(name = "CmtsSharedVideo", catalog = "dolphin")
public class CmtsSharedVideo implements java.io.Serializable {

	private Integer cmtId;
	private int cmtParentId;
	private int cmtObjectId;
	private int cmtAuthorId;
	private String cmtText;
	private int cmtRate;
	private int cmtRateCount;
	private Date cmtTime;
	private int cmtReplies;

	public CmtsSharedVideo() {
	}

	public CmtsSharedVideo(int cmtParentId, int cmtObjectId, int cmtAuthorId,
			String cmtText, int cmtRate, int cmtRateCount, Date cmtTime,
			int cmtReplies) {
		this.cmtParentId = cmtParentId;
		this.cmtObjectId = cmtObjectId;
		this.cmtAuthorId = cmtAuthorId;
		this.cmtText = cmtText;
		this.cmtRate = cmtRate;
		this.cmtRateCount = cmtRateCount;
		this.cmtTime = cmtTime;
		this.cmtReplies = cmtReplies;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cmt_id", unique = true, nullable = false)
	public Integer getCmtId() {
		return this.cmtId;
	}

	public void setCmtId(Integer cmtId) {
		this.cmtId = cmtId;
	}

	@Column(name = "cmt_parent_id", nullable = false)
	public int getCmtParentId() {
		return this.cmtParentId;
	}

	public void setCmtParentId(int cmtParentId) {
		this.cmtParentId = cmtParentId;
	}

	@Column(name = "cmt_object_id", nullable = false)
	public int getCmtObjectId() {
		return this.cmtObjectId;
	}

	public void setCmtObjectId(int cmtObjectId) {
		this.cmtObjectId = cmtObjectId;
	}

	@Column(name = "cmt_author_id", nullable = false)
	public int getCmtAuthorId() {
		return this.cmtAuthorId;
	}

	public void setCmtAuthorId(int cmtAuthorId) {
		this.cmtAuthorId = cmtAuthorId;
	}

	@Column(name = "cmt_text", nullable = false, length = 65535)
	public String getCmtText() {
		return this.cmtText;
	}

	public void setCmtText(String cmtText) {
		this.cmtText = cmtText;
	}

	@Column(name = "cmt_rate", nullable = false)
	public int getCmtRate() {
		return this.cmtRate;
	}

	public void setCmtRate(int cmtRate) {
		this.cmtRate = cmtRate;
	}

	@Column(name = "cmt_rate_count", nullable = false)
	public int getCmtRateCount() {
		return this.cmtRateCount;
	}

	public void setCmtRateCount(int cmtRateCount) {
		this.cmtRateCount = cmtRateCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cmt_time", nullable = false, length = 0)
	public Date getCmtTime() {
		return this.cmtTime;
	}

	public void setCmtTime(Date cmtTime) {
		this.cmtTime = cmtTime;
	}

	@Column(name = "cmt_replies", nullable = false)
	public int getCmtReplies() {
		return this.cmtReplies;
	}

	public void setCmtReplies(int cmtReplies) {
		this.cmtReplies = cmtReplies;
	}

}
