package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ColorBaseId generated by hbm2java
 */
@Embeddable
public class ColorBaseId implements java.io.Serializable {

	private String colorName;
	private String colorCode;

	public ColorBaseId() {
	}

	public ColorBaseId(String colorName, String colorCode) {
		this.colorName = colorName;
		this.colorCode = colorCode;
	}

	@Column(name = "ColorName", unique = true, nullable = false, length = 20)
	public String getColorName() {
		return this.colorName;
	}

	public void setColorName(String colorName) {
		this.colorName = colorName;
	}

	@Column(name = "ColorCode", nullable = false, length = 10)
	public String getColorCode() {
		return this.colorCode;
	}

	public void setColorCode(String colorCode) {
		this.colorCode = colorCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ColorBaseId))
			return false;
		ColorBaseId castOther = (ColorBaseId) other;

		return ((this.getColorName() == castOther.getColorName()) || (this
				.getColorName() != null
				&& castOther.getColorName() != null && this.getColorName()
				.equals(castOther.getColorName())))
				&& ((this.getColorCode() == castOther.getColorCode()) || (this
						.getColorCode() != null
						&& castOther.getColorCode() != null && this
						.getColorCode().equals(castOther.getColorCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getColorName() == null ? 0 : this.getColorName().hashCode());
		result = 37 * result
				+ (getColorCode() == null ? 0 : this.getColorCode().hashCode());
		return result;
	}

}
