package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FriendListId generated by hbm2java
 */
@Embeddable
public class FriendListId implements java.io.Serializable {

	private long id;
	private long profile;
	private byte check;

	public FriendListId() {
	}

	public FriendListId(long id, long profile, byte check) {
		this.id = id;
		this.profile = profile;
		this.check = check;
	}

	@Column(name = "ID", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "Profile", nullable = false)
	public long getProfile() {
		return this.profile;
	}

	public void setProfile(long profile) {
		this.profile = profile;
	}

	@Column(name = "Check", nullable = false)
	public byte getCheck() {
		return this.check;
	}

	public void setCheck(byte check) {
		this.check = check;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FriendListId))
			return false;
		FriendListId castOther = (FriendListId) other;

		return (this.getId() == castOther.getId())
				&& (this.getProfile() == castOther.getProfile())
				&& (this.getCheck() == castOther.getCheck());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (int) this.getProfile();
		result = 37 * result + this.getCheck();
		return result;
	}

}
