package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GalleryObjects generated by hbm2java
 */
@Entity
@Table(name = "GalleryObjects", catalog = "dolphin")
public class GalleryObjects implements java.io.Serializable {

	private Long id;
	private int idalbum;
	private String filename;
	private String thumbFilename;
	private String objectType;
	private String comment;
	private Date created;
	private Date modified;
	private int orderInAlbum;
	private boolean approved;

	public GalleryObjects() {
	}

	public GalleryObjects(int idalbum, String filename, String objectType,
			Date created, Date modified, int orderInAlbum, boolean approved) {
		this.idalbum = idalbum;
		this.filename = filename;
		this.objectType = objectType;
		this.created = created;
		this.modified = modified;
		this.orderInAlbum = orderInAlbum;
		this.approved = approved;
	}

	public GalleryObjects(int idalbum, String filename, String thumbFilename,
			String objectType, String comment, Date created, Date modified,
			int orderInAlbum, boolean approved) {
		this.idalbum = idalbum;
		this.filename = filename;
		this.thumbFilename = thumbFilename;
		this.objectType = objectType;
		this.comment = comment;
		this.created = created;
		this.modified = modified;
		this.orderInAlbum = orderInAlbum;
		this.approved = approved;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "IDAlbum", nullable = false)
	public int getIdalbum() {
		return this.idalbum;
	}

	public void setIdalbum(int idalbum) {
		this.idalbum = idalbum;
	}

	@Column(name = "Filename", nullable = false)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "ThumbFilename")
	public String getThumbFilename() {
		return this.thumbFilename;
	}

	public void setThumbFilename(String thumbFilename) {
		this.thumbFilename = thumbFilename;
	}

	@Column(name = "ObjectType", nullable = false, length = 6)
	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	@Column(name = "Comment")
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Modified", nullable = false, length = 0)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "OrderInAlbum", nullable = false)
	public int getOrderInAlbum() {
		return this.orderInAlbum;
	}

	public void setOrderInAlbum(int orderInAlbum) {
		this.orderInAlbum = orderInAlbum;
	}

	@Column(name = "Approved", nullable = false)
	public boolean isApproved() {
		return this.approved;
	}

	public void setApproved(boolean approved) {
		this.approved = approved;
	}

}
