package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GlParams generated by hbm2java
 */
@Entity
@Table(name = "GlParams", catalog = "dolphin")
public class GlParams implements java.io.Serializable {

	private String name;
	private String value;
	private int kateg;
	private String desc;
	private String type;
	private String check;
	private String errText;
	private Float orderInKateg;

	public GlParams() {
	}

	public GlParams(String name, String value, int kateg, String desc,
			String type, String check, String errText) {
		this.name = name;
		this.value = value;
		this.kateg = kateg;
		this.desc = desc;
		this.type = type;
		this.check = check;
		this.errText = errText;
	}

	public GlParams(String name, String value, int kateg, String desc,
			String type, String check, String errText, Float orderInKateg) {
		this.name = name;
		this.value = value;
		this.kateg = kateg;
		this.desc = desc;
		this.type = type;
		this.check = check;
		this.errText = errText;
		this.orderInKateg = orderInKateg;
	}

	@Id
	@Column(name = "Name", unique = true, nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "VALUE", nullable = false, length = 16777215)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "kateg", nullable = false)
	public int getKateg() {
		return this.kateg;
	}

	public void setKateg(int kateg) {
		this.kateg = kateg;
	}

	@Column(name = "desc", nullable = false)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "Type", nullable = false, length = 8)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "check", nullable = false, length = 65535)
	public String getCheck() {
		return this.check;
	}

	public void setCheck(String check) {
		this.check = check;
	}

	@Column(name = "err_text", nullable = false)
	public String getErrText() {
		return this.errText;
	}

	public void setErrText(String errText) {
		this.errText = errText;
	}

	@Column(name = "order_in_kateg", precision = 12, scale = 0)
	public Float getOrderInKateg() {
		return this.orderInKateg;
	}

	public void setOrderInKateg(Float orderInKateg) {
		this.orderInKateg = orderInKateg;
	}

}
