package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GmusicVotingTrack generated by hbm2java
 */
@Entity
@Table(name = "gmusic_voting_track", catalog = "dolphin")
public class GmusicVotingTrack implements java.io.Serializable {

	private GmusicVotingTrackId id;

	public GmusicVotingTrack() {
	}

	public GmusicVotingTrack(GmusicVotingTrackId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "galId", column = @Column(name = "gal_id", nullable = false)),
			@AttributeOverride(name = "galIp", column = @Column(name = "gal_ip", length = 20)),
			@AttributeOverride(name = "galDate", column = @Column(name = "gal_date", length = 0)) })
	public GmusicVotingTrackId getId() {
		return this.id;
	}

	public void setId(GmusicVotingTrackId id) {
		this.id = id;
	}

}
