package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GroupsMembers generated by hbm2java
 */
@Entity
@Table(name = "GroupsMembers", catalog = "dolphin")
public class GroupsMembers implements java.io.Serializable {

	private GroupsMembersId id;

	public GroupsMembers() {
	}

	public GroupsMembers(GroupsMembersId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "memberId", column = @Column(name = "memberID", nullable = false)),
			@AttributeOverride(name = "groupId", column = @Column(name = "groupID", nullable = false)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false, length = 25)),
			@AttributeOverride(name = "date", column = @Column(name = "Date", nullable = false, length = 0)) })
	public GroupsMembersId getId() {
		return this.id;
	}

	public void setId(GroupsMembersId id) {
		this.id = id;
	}

}
