package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GroupsCateg generated by hbm2java
 */
@Entity
@Table(name = "GroupsCateg", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "Uri"))
public class GroupsCateg implements java.io.Serializable {

	private Integer id;
	private String name;
	private String uri;

	public GroupsCateg() {
	}

	public GroupsCateg(String name, String uri) {
		this.name = name;
		this.uri = uri;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Uri", unique = true, nullable = false)
	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

}
