package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "Groups", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "Uri"))
public class Groups implements java.io.Serializable {

	private Integer id;
	private int categId;
	private String name;
	private String uri;
	private boolean openJoin;
	private boolean hiddenGroup;
	private boolean membersPostImages;
	private boolean membersInvite;
	private String country;
	private String city;
	private String about;
	private String desc;
	private int thumb;
	private int creatorId;
	private Date created;
	private String status;

	public Groups() {
	}

	public Groups(int categId, String name, String uri, boolean openJoin,
			boolean hiddenGroup, boolean membersPostImages,
			boolean membersInvite, String country, String city, String about,
			String desc, int thumb, int creatorId, Date created, String status) {
		this.categId = categId;
		this.name = name;
		this.uri = uri;
		this.openJoin = openJoin;
		this.hiddenGroup = hiddenGroup;
		this.membersPostImages = membersPostImages;
		this.membersInvite = membersInvite;
		this.country = country;
		this.city = city;
		this.about = about;
		this.desc = desc;
		this.thumb = thumb;
		this.creatorId = creatorId;
		this.created = created;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "categID", nullable = false)
	public int getCategId() {
		return this.categId;
	}

	public void setCategId(int categId) {
		this.categId = categId;
	}

	@Column(name = "Name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Uri", unique = true, nullable = false, length = 64)
	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	@Column(name = "open_join", nullable = false)
	public boolean isOpenJoin() {
		return this.openJoin;
	}

	public void setOpenJoin(boolean openJoin) {
		this.openJoin = openJoin;
	}

	@Column(name = "hidden_group", nullable = false)
	public boolean isHiddenGroup() {
		return this.hiddenGroup;
	}

	public void setHiddenGroup(boolean hiddenGroup) {
		this.hiddenGroup = hiddenGroup;
	}

	@Column(name = "members_post_images", nullable = false)
	public boolean isMembersPostImages() {
		return this.membersPostImages;
	}

	public void setMembersPostImages(boolean membersPostImages) {
		this.membersPostImages = membersPostImages;
	}

	@Column(name = "members_invite", nullable = false)
	public boolean isMembersInvite() {
		return this.membersInvite;
	}

	public void setMembersInvite(boolean membersInvite) {
		this.membersInvite = membersInvite;
	}

	@Column(name = "Country", nullable = false, length = 2)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "City", nullable = false, length = 64)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "About", nullable = false)
	public String getAbout() {
		return this.about;
	}

	public void setAbout(String about) {
		this.about = about;
	}

	@Column(name = "Desc", nullable = false, length = 65535)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "thumb", nullable = false)
	public int getThumb() {
		return this.thumb;
	}

	public void setThumb(int thumb) {
		this.thumb = thumb;
	}

	@Column(name = "creatorID", nullable = false)
	public int getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(int creatorId) {
		this.creatorId = creatorId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 0)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "status", nullable = false, length = 9)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
