package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GroupsMembersId generated by hbm2java
 */
@Embeddable
public class GroupsMembersId implements java.io.Serializable {

	private int memberId;
	private int groupId;
	private String status;
	private Date date;

	public GroupsMembersId() {
	}

	public GroupsMembersId(int memberId, int groupId, String status, Date date) {
		this.memberId = memberId;
		this.groupId = groupId;
		this.status = status;
		this.date = date;
	}

	@Column(name = "memberID", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "groupID", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "status", nullable = false, length = 25)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GroupsMembersId))
			return false;
		GroupsMembersId castOther = (GroupsMembersId) other;

		return (this.getMemberId() == castOther.getMemberId())
				&& (this.getGroupId() == castOther.getGroupId())
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus()
						.equals(castOther.getStatus())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null
						&& castOther.getDate() != null && this.getDate()
						.equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemberId();
		result = 37 * result + this.getGroupId();
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result
				+ (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
