package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GrpForumCat generated by hbm2java
 */
@Entity
@Table(name = "grp_forum_cat", catalog = "dolphin")
public class GrpForumCat implements java.io.Serializable {

	private Integer catId;
	private String catUri;
	private String catName;
	private String catIcon;
	private float catOrder;

	public GrpForumCat() {
	}

	public GrpForumCat(String catUri, String catIcon, float catOrder) {
		this.catUri = catUri;
		this.catIcon = catIcon;
		this.catOrder = catOrder;
	}

	public GrpForumCat(String catUri, String catName, String catIcon,
			float catOrder) {
		this.catUri = catUri;
		this.catName = catName;
		this.catIcon = catIcon;
		this.catOrder = catOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cat_id", unique = true, nullable = false)
	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	@Column(name = "cat_uri", nullable = false)
	public String getCatUri() {
		return this.catUri;
	}

	public void setCatUri(String catUri) {
		this.catUri = catUri;
	}

	@Column(name = "cat_name")
	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	@Column(name = "cat_icon", nullable = false, length = 32)
	public String getCatIcon() {
		return this.catIcon;
	}

	public void setCatIcon(String catIcon) {
		this.catIcon = catIcon;
	}

	@Column(name = "cat_order", nullable = false, precision = 12, scale = 0)
	public float getCatOrder() {
		return this.catOrder;
	}

	public void setCatOrder(float catOrder) {
		this.catOrder = catOrder;
	}

}
