package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GrpForumTopic generated by hbm2java
 */
@Entity
@Table(name = "grp_forum_topic", catalog = "dolphin")
public class GrpForumTopic implements java.io.Serializable {

	private Integer topicId;
	private String topicUri;
	private int forumId;
	private String topicTitle;
	private int when;
	private int topicPosts;
	private String firstPostUser;
	private int firstPostWhen;
	private String lastPostUser;
	private int lastPostWhen;
	private int topicSticky;
	private byte topicLocked;

	public GrpForumTopic() {
	}

	public GrpForumTopic(String topicUri, int forumId, String topicTitle,
			int when, int topicPosts, String firstPostUser, int firstPostWhen,
			String lastPostUser, int lastPostWhen, int topicSticky,
			byte topicLocked) {
		this.topicUri = topicUri;
		this.forumId = forumId;
		this.topicTitle = topicTitle;
		this.when = when;
		this.topicPosts = topicPosts;
		this.firstPostUser = firstPostUser;
		this.firstPostWhen = firstPostWhen;
		this.lastPostUser = lastPostUser;
		this.lastPostWhen = lastPostWhen;
		this.topicSticky = topicSticky;
		this.topicLocked = topicLocked;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "topic_id", unique = true, nullable = false)
	public Integer getTopicId() {
		return this.topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	@Column(name = "topic_uri", nullable = false)
	public String getTopicUri() {
		return this.topicUri;
	}

	public void setTopicUri(String topicUri) {
		this.topicUri = topicUri;
	}

	@Column(name = "forum_id", nullable = false)
	public int getForumId() {
		return this.forumId;
	}

	public void setForumId(int forumId) {
		this.forumId = forumId;
	}

	@Column(name = "topic_title", nullable = false)
	public String getTopicTitle() {
		return this.topicTitle;
	}

	public void setTopicTitle(String topicTitle) {
		this.topicTitle = topicTitle;
	}

	@Column(name = "when", nullable = false)
	public int getWhen() {
		return this.when;
	}

	public void setWhen(int when) {
		this.when = when;
	}

	@Column(name = "topic_posts", nullable = false)
	public int getTopicPosts() {
		return this.topicPosts;
	}

	public void setTopicPosts(int topicPosts) {
		this.topicPosts = topicPosts;
	}

	@Column(name = "first_post_user", nullable = false, length = 32)
	public String getFirstPostUser() {
		return this.firstPostUser;
	}

	public void setFirstPostUser(String firstPostUser) {
		this.firstPostUser = firstPostUser;
	}

	@Column(name = "first_post_when", nullable = false)
	public int getFirstPostWhen() {
		return this.firstPostWhen;
	}

	public void setFirstPostWhen(int firstPostWhen) {
		this.firstPostWhen = firstPostWhen;
	}

	@Column(name = "last_post_user", nullable = false, length = 32)
	public String getLastPostUser() {
		return this.lastPostUser;
	}

	public void setLastPostUser(String lastPostUser) {
		this.lastPostUser = lastPostUser;
	}

	@Column(name = "last_post_when", nullable = false)
	public int getLastPostWhen() {
		return this.lastPostWhen;
	}

	public void setLastPostWhen(int lastPostWhen) {
		this.lastPostWhen = lastPostWhen;
	}

	@Column(name = "topic_sticky", nullable = false)
	public int getTopicSticky() {
		return this.topicSticky;
	}

	public void setTopicSticky(int topicSticky) {
		this.topicSticky = topicSticky;
	}

	@Column(name = "topic_locked", nullable = false)
	public byte getTopicLocked() {
		return this.topicLocked;
	}

	public void setTopicLocked(byte topicLocked) {
		this.topicLocked = topicLocked;
	}

}
