package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GvideoRating generated by hbm2java
 */
@Entity
@Table(name = "gvideo_rating", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "gal_id"))
public class GvideoRating implements java.io.Serializable {

	private GvideoRatingId id;

	public GvideoRating() {
	}

	public GvideoRating(GvideoRatingId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "galId", column = @Column(name = "gal_id", unique = true, nullable = false)),
			@AttributeOverride(name = "galRatingCount", column = @Column(name = "gal_rating_count", nullable = false)),
			@AttributeOverride(name = "galRatingSum", column = @Column(name = "gal_rating_sum", nullable = false)) })
	public GvideoRatingId getId() {
		return this.id;
	}

	public void setId(GvideoRatingId id) {
		this.id = id;
	}

}
