package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GvideoVotingTrackId generated by hbm2java
 */
@Embeddable
public class GvideoVotingTrackId implements java.io.Serializable {

	private int galId;
	private String galIp;
	private Date galDate;

	public GvideoVotingTrackId() {
	}

	public GvideoVotingTrackId(int galId) {
		this.galId = galId;
	}

	public GvideoVotingTrackId(int galId, String galIp, Date galDate) {
		this.galId = galId;
		this.galIp = galIp;
		this.galDate = galDate;
	}

	@Column(name = "gal_id", nullable = false)
	public int getGalId() {
		return this.galId;
	}

	public void setGalId(int galId) {
		this.galId = galId;
	}

	@Column(name = "gal_ip", length = 20)
	public String getGalIp() {
		return this.galIp;
	}

	public void setGalIp(String galIp) {
		this.galIp = galIp;
	}

	@Column(name = "gal_date", length = 0)
	public Date getGalDate() {
		return this.galDate;
	}

	public void setGalDate(Date galDate) {
		this.galDate = galDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GvideoVotingTrackId))
			return false;
		GvideoVotingTrackId castOther = (GvideoVotingTrackId) other;

		return (this.getGalId() == castOther.getGalId())
				&& ((this.getGalIp() == castOther.getGalIp()) || (this
						.getGalIp() != null
						&& castOther.getGalIp() != null && this.getGalIp()
						.equals(castOther.getGalIp())))
				&& ((this.getGalDate() == castOther.getGalDate()) || (this
						.getGalDate() != null
						&& castOther.getGalDate() != null && this.getGalDate()
						.equals(castOther.getGalDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGalId();
		result = 37 * result
				+ (getGalIp() == null ? 0 : this.getGalIp().hashCode());
		result = 37 * result
				+ (getGalDate() == null ? 0 : this.getGalDate().hashCode());
		return result;
	}

}
