package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MediaVotingTrackId generated by hbm2java
 */
@Embeddable
public class MediaVotingTrackId implements java.io.Serializable {

	private int medId;
	private String medIp;
	private Date medDate;

	public MediaVotingTrackId() {
	}

	public MediaVotingTrackId(int medId) {
		this.medId = medId;
	}

	public MediaVotingTrackId(int medId, String medIp, Date medDate) {
		this.medId = medId;
		this.medIp = medIp;
		this.medDate = medDate;
	}

	@Column(name = "med_id", nullable = false)
	public int getMedId() {
		return this.medId;
	}

	public void setMedId(int medId) {
		this.medId = medId;
	}

	@Column(name = "med_ip", length = 20)
	public String getMedIp() {
		return this.medIp;
	}

	public void setMedIp(String medIp) {
		this.medIp = medIp;
	}

	@Column(name = "med_date", length = 0)
	public Date getMedDate() {
		return this.medDate;
	}

	public void setMedDate(Date medDate) {
		this.medDate = medDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MediaVotingTrackId))
			return false;
		MediaVotingTrackId castOther = (MediaVotingTrackId) other;

		return (this.getMedId() == castOther.getMedId())
				&& ((this.getMedIp() == castOther.getMedIp()) || (this
						.getMedIp() != null
						&& castOther.getMedIp() != null && this.getMedIp()
						.equals(castOther.getMedIp())))
				&& ((this.getMedDate() == castOther.getMedDate()) || (this
						.getMedDate() != null
						&& castOther.getMedDate() != null && this.getMedDate()
						.equals(castOther.getMedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMedId();
		result = 37 * result
				+ (getMedIp() == null ? 0 : this.getMedIp().hashCode());
		result = 37 * result
				+ (getMedDate() == null ? 0 : this.getMedDate().hashCode());
		return result;
	}

}
