package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MediaRatingId generated by hbm2java
 */
@Embeddable
public class MediaRatingId implements java.io.Serializable {

	private int medId;
	private int medRatingCount;
	private int medRatingSum;

	public MediaRatingId() {
	}

	public MediaRatingId(int medId, int medRatingCount, int medRatingSum) {
		this.medId = medId;
		this.medRatingCount = medRatingCount;
		this.medRatingSum = medRatingSum;
	}

	@Column(name = "med_id", unique = true, nullable = false)
	public int getMedId() {
		return this.medId;
	}

	public void setMedId(int medId) {
		this.medId = medId;
	}

	@Column(name = "med_rating_count", nullable = false)
	public int getMedRatingCount() {
		return this.medRatingCount;
	}

	public void setMedRatingCount(int medRatingCount) {
		this.medRatingCount = medRatingCount;
	}

	@Column(name = "med_rating_sum", nullable = false)
	public int getMedRatingSum() {
		return this.medRatingSum;
	}

	public void setMedRatingSum(int medRatingSum) {
		this.medRatingSum = medRatingSum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MediaRatingId))
			return false;
		MediaRatingId castOther = (MediaRatingId) other;

		return (this.getMedId() == castOther.getMedId())
				&& (this.getMedRatingCount() == castOther.getMedRatingCount())
				&& (this.getMedRatingSum() == castOther.getMedRatingSum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMedId();
		result = 37 * result + this.getMedRatingCount();
		result = 37 * result + this.getMedRatingSum();
		return result;
	}

}
