package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MemActions generated by hbm2java
 */
@Entity
@Table(name = "MemActions", catalog = "dolphin")
public class MemActions implements java.io.Serializable {

	private Short id;
	private String name;
	private String additionalParamName;

	public MemActions() {
	}

	public MemActions(String name) {
		this.name = name;
	}

	public MemActions(String name, String additionalParamName) {
		this.name = name;
		this.additionalParamName = additionalParamName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "AdditionalParamName", length = 80)
	public String getAdditionalParamName() {
		return this.additionalParamName;
	}

	public void setAdditionalParamName(String additionalParamName) {
		this.additionalParamName = additionalParamName;
	}

}
