package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MemActionsTrackId generated by hbm2java
 */
@Embeddable
public class MemActionsTrackId implements java.io.Serializable {

	private short idaction;
	private long idmember;

	public MemActionsTrackId() {
	}

	public MemActionsTrackId(short idaction, long idmember) {
		this.idaction = idaction;
		this.idmember = idmember;
	}

	@Column(name = "IDAction", nullable = false)
	public short getIdaction() {
		return this.idaction;
	}

	public void setIdaction(short idaction) {
		this.idaction = idaction;
	}

	@Column(name = "IDMember", nullable = false)
	public long getIdmember() {
		return this.idmember;
	}

	public void setIdmember(long idmember) {
		this.idmember = idmember;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MemActionsTrackId))
			return false;
		MemActionsTrackId castOther = (MemActionsTrackId) other;

		return (this.getIdaction() == castOther.getIdaction())
				&& (this.getIdmember() == castOther.getIdmember());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdaction();
		result = 37 * result + (int) this.getIdmember();
		return result;
	}

}
