package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MemLevels generated by hbm2java
 */
@Entity
@Table(name = "MemLevels", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "Name"))
public class MemLevels implements java.io.Serializable {

	private Short id;
	private String name;
	private String active;
	private String purchasable;
	private String removable;

	public MemLevels() {
	}

	public MemLevels(String name, String active, String purchasable,
			String removable) {
		this.name = name;
		this.active = active;
		this.purchasable = purchasable;
		this.removable = removable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	@Column(name = "Name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Active", nullable = false, length = 4)
	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	@Column(name = "Purchasable", nullable = false, length = 4)
	public String getPurchasable() {
		return this.purchasable;
	}

	public void setPurchasable(String purchasable) {
		this.purchasable = purchasable;
	}

	@Column(name = "Removable", nullable = false, length = 4)
	public String getRemovable() {
		return this.removable;
	}

	public void setRemovable(String removable) {
		this.removable = removable;
	}

}
