package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MemLevelActionsId generated by hbm2java
 */
@Embeddable
public class MemLevelActionsId implements java.io.Serializable {

	private short idlevel;
	private short idaction;

	public MemLevelActionsId() {
	}

	public MemLevelActionsId(short idlevel, short idaction) {
		this.idlevel = idlevel;
		this.idaction = idaction;
	}

	@Column(name = "IDLevel", nullable = false)
	public short getIdlevel() {
		return this.idlevel;
	}

	public void setIdlevel(short idlevel) {
		this.idlevel = idlevel;
	}

	@Column(name = "IDAction", nullable = false)
	public short getIdaction() {
		return this.idaction;
	}

	public void setIdaction(short idaction) {
		this.idaction = idaction;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MemLevelActionsId))
			return false;
		MemLevelActionsId castOther = (MemLevelActionsId) other;

		return (this.getIdlevel() == castOther.getIdlevel())
				&& (this.getIdaction() == castOther.getIdaction());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdlevel();
		result = 37 * result + this.getIdaction();
		return result;
	}

}
