package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Modules generated by hbm2java
 */
@Entity
@Table(name = "Modules", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "Name"))
public class Modules implements java.io.Serializable {

	private Integer id;
	private String name;
	private String conf;
	private String funcAdd;
	private String funcDel;
	private String funcUpdate;
	private String funcBlock;
	private String funcUnblock;
	private String help;
	private String logIn;
	private String type;
	private String readableName;

	public Modules() {
	}

	public Modules(String name, String conf, String funcAdd, String funcDel,
			String funcUpdate, String funcBlock, String funcUnblock,
			String help, String logIn, String type, String readableName) {
		this.name = name;
		this.conf = conf;
		this.funcAdd = funcAdd;
		this.funcDel = funcDel;
		this.funcUpdate = funcUpdate;
		this.funcBlock = funcBlock;
		this.funcUnblock = funcUnblock;
		this.help = help;
		this.logIn = logIn;
		this.type = type;
		this.readableName = readableName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", unique = true, nullable = false, length = 32)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Conf", nullable = false, length = 16777215)
	public String getConf() {
		return this.conf;
	}

	public void setConf(String conf) {
		this.conf = conf;
	}

	@Column(name = "FuncAdd", nullable = false, length = 16777215)
	public String getFuncAdd() {
		return this.funcAdd;
	}

	public void setFuncAdd(String funcAdd) {
		this.funcAdd = funcAdd;
	}

	@Column(name = "FuncDel", nullable = false, length = 16777215)
	public String getFuncDel() {
		return this.funcDel;
	}

	public void setFuncDel(String funcDel) {
		this.funcDel = funcDel;
	}

	@Column(name = "FuncUpdate", nullable = false, length = 16777215)
	public String getFuncUpdate() {
		return this.funcUpdate;
	}

	public void setFuncUpdate(String funcUpdate) {
		this.funcUpdate = funcUpdate;
	}

	@Column(name = "FuncBlock", nullable = false, length = 16777215)
	public String getFuncBlock() {
		return this.funcBlock;
	}

	public void setFuncBlock(String funcBlock) {
		this.funcBlock = funcBlock;
	}

	@Column(name = "FuncUnblock", nullable = false, length = 16777215)
	public String getFuncUnblock() {
		return this.funcUnblock;
	}

	public void setFuncUnblock(String funcUnblock) {
		this.funcUnblock = funcUnblock;
	}

	@Column(name = "Help", nullable = false, length = 16777215)
	public String getHelp() {
		return this.help;
	}

	public void setHelp(String help) {
		this.help = help;
	}

	@Column(name = "LogIn", nullable = false, length = 16777215)
	public String getLogIn() {
		return this.logIn;
	}

	public void setLogIn(String logIn) {
		this.logIn = logIn;
	}

	@Column(name = "Type", nullable = false, length = 5)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "ReadableName", nullable = false, length = 15)
	public String getReadableName() {
		return this.readableName;
	}

	public void setReadableName(String readableName) {
		this.readableName = readableName;
	}

}
