package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NotifyQueueId generated by hbm2java
 */
@Embeddable
public class NotifyQueueId implements java.io.Serializable {

	private int email;
	private int msg;
	private Date creation;
	private String from;
	private String msgText;
	private String msgSubj;

	public NotifyQueueId() {
	}

	public NotifyQueueId(int email, int msg, Date creation, String from,
			String msgText, String msgSubj) {
		this.email = email;
		this.msg = msg;
		this.creation = creation;
		this.from = from;
		this.msgText = msgText;
		this.msgSubj = msgSubj;
	}

	@Column(name = "Email", nullable = false)
	public int getEmail() {
		return this.email;
	}

	public void setEmail(int email) {
		this.email = email;
	}

	@Column(name = "Msg", nullable = false)
	public int getMsg() {
		return this.msg;
	}

	public void setMsg(int msg) {
		this.msg = msg;
	}

	@Column(name = "Creation", nullable = false, length = 0)
	public Date getCreation() {
		return this.creation;
	}

	public void setCreation(Date creation) {
		this.creation = creation;
	}

	@Column(name = "From", nullable = false, length = 15)
	public String getFrom() {
		return this.from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	@Column(name = "MsgText", nullable = false, length = 16777215)
	public String getMsgText() {
		return this.msgText;
	}

	public void setMsgText(String msgText) {
		this.msgText = msgText;
	}

	@Column(name = "MsgSubj", nullable = false)
	public String getMsgSubj() {
		return this.msgSubj;
	}

	public void setMsgSubj(String msgSubj) {
		this.msgSubj = msgSubj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotifyQueueId))
			return false;
		NotifyQueueId castOther = (NotifyQueueId) other;

		return (this.getEmail() == castOther.getEmail())
				&& (this.getMsg() == castOther.getMsg())
				&& ((this.getCreation() == castOther.getCreation()) || (this
						.getCreation() != null
						&& castOther.getCreation() != null && this
						.getCreation().equals(castOther.getCreation())))
				&& ((this.getFrom() == castOther.getFrom()) || (this.getFrom() != null
						&& castOther.getFrom() != null && this.getFrom()
						.equals(castOther.getFrom())))
				&& ((this.getMsgText() == castOther.getMsgText()) || (this
						.getMsgText() != null
						&& castOther.getMsgText() != null && this.getMsgText()
						.equals(castOther.getMsgText())))
				&& ((this.getMsgSubj() == castOther.getMsgSubj()) || (this
						.getMsgSubj() != null
						&& castOther.getMsgSubj() != null && this.getMsgSubj()
						.equals(castOther.getMsgSubj())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEmail();
		result = 37 * result + this.getMsg();
		result = 37 * result
				+ (getCreation() == null ? 0 : this.getCreation().hashCode());
		result = 37 * result
				+ (getFrom() == null ? 0 : this.getFrom().hashCode());
		result = 37 * result
				+ (getMsgText() == null ? 0 : this.getMsgText().hashCode());
		result = 37 * result
				+ (getMsgSubj() == null ? 0 : this.getMsgSubj().hashCode());
		return result;
	}

}
