package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PreForumUserActivity generated by hbm2java
 */
@Entity
@Table(name = "pre_forum_user_activity", catalog = "dolphin")
public class PreForumUserActivity implements java.io.Serializable {

	private String user;
	private int actCurrent;
	private int actLast;

	public PreForumUserActivity() {
	}

	public PreForumUserActivity(String user, int actCurrent, int actLast) {
		this.user = user;
		this.actCurrent = actCurrent;
		this.actLast = actLast;
	}

	@Id
	@Column(name = "user", unique = true, nullable = false, length = 16)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "act_current", nullable = false)
	public int getActCurrent() {
		return this.actCurrent;
	}

	public void setActCurrent(int actCurrent) {
		this.actCurrent = actCurrent;
	}

	@Column(name = "act_last", nullable = false)
	public int getActLast() {
		return this.actLast;
	}

	public void setActLast(int actLast) {
		this.actLast = actLast;
	}

}
