package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProfilesTrackId generated by hbm2java
 */
@Embeddable
public class ProfilesTrackId implements java.io.Serializable {

	private long member;
	private long profile;
	private Date arrived;
	private byte hide;

	public ProfilesTrackId() {
	}

	public ProfilesTrackId(long member, long profile, Date arrived, byte hide) {
		this.member = member;
		this.profile = profile;
		this.arrived = arrived;
		this.hide = hide;
	}

	@Column(name = "Member", nullable = false)
	public long getMember() {
		return this.member;
	}

	public void setMember(long member) {
		this.member = member;
	}

	@Column(name = "Profile", nullable = false)
	public long getProfile() {
		return this.profile;
	}

	public void setProfile(long profile) {
		this.profile = profile;
	}

	@Column(name = "Arrived", nullable = false, length = 0)
	public Date getArrived() {
		return this.arrived;
	}

	public void setArrived(Date arrived) {
		this.arrived = arrived;
	}

	@Column(name = "Hide", nullable = false)
	public byte getHide() {
		return this.hide;
	}

	public void setHide(byte hide) {
		this.hide = hide;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProfilesTrackId))
			return false;
		ProfilesTrackId castOther = (ProfilesTrackId) other;

		return (this.getMember() == castOther.getMember())
				&& (this.getProfile() == castOther.getProfile())
				&& ((this.getArrived() == castOther.getArrived()) || (this
						.getArrived() != null
						&& castOther.getArrived() != null && this.getArrived()
						.equals(castOther.getArrived())))
				&& (this.getHide() == castOther.getHide());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMember();
		result = 37 * result + (int) this.getProfile();
		result = 37 * result
				+ (getArrived() == null ? 0 : this.getArrived().hashCode());
		result = 37 * result + this.getHide();
		return result;
	}

}
