package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Profiles generated by hbm2java
 */
@Entity
@Table(name = "Profiles", catalog = "dolphin")
public class Profiles implements java.io.Serializable {

	private Integer id;
	private String nickName;
	private String email;
	private String password;
	private String status;
	private int couple;
	private String sex;
	private String lookingFor;
	private String headline;
	private String descriptionMe;
	private String country;
	private String city;
	private Date dateOfBirth;
	private boolean featured;
	private Date dateReg;
	private Date dateLastEdit;
	private Date dateLastLogin;
	private Date dateLastNav;
	private int primPhoto;
	private boolean picture;
	private int affNum;
	private String tags;
	private String zip;
	private boolean emailNotify;

	public Profiles() {
	}

	public Profiles(String nickName, String email, String password,
			String status, int couple, String sex, String lookingFor,
			String headline, String descriptionMe, String country, String city,
			Date dateOfBirth, boolean featured, Date dateReg,
			Date dateLastEdit, Date dateLastLogin, Date dateLastNav,
			int primPhoto, boolean picture, int affNum, String tags,
			String zip, boolean emailNotify) {
		this.nickName = nickName;
		this.email = email;
		this.password = password;
		this.status = status;
		this.couple = couple;
		this.sex = sex;
		this.lookingFor = lookingFor;
		this.headline = headline;
		this.descriptionMe = descriptionMe;
		this.country = country;
		this.city = city;
		this.dateOfBirth = dateOfBirth;
		this.featured = featured;
		this.dateReg = dateReg;
		this.dateLastEdit = dateLastEdit;
		this.dateLastLogin = dateLastLogin;
		this.dateLastNav = dateLastNav;
		this.primPhoto = primPhoto;
		this.picture = picture;
		this.affNum = affNum;
		this.tags = tags;
		this.zip = zip;
		this.emailNotify = emailNotify;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NickName", nullable = false)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "Email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Password", nullable = false, length = 32)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Status", nullable = false, length = 12)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Couple", nullable = false)
	public int getCouple() {
		return this.couple;
	}

	public void setCouple(int couple) {
		this.couple = couple;
	}

	@Column(name = "Sex", nullable = false)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "LookingFor", nullable = false, length = 13)
	public String getLookingFor() {
		return this.lookingFor;
	}

	public void setLookingFor(String lookingFor) {
		this.lookingFor = lookingFor;
	}

	@Column(name = "Headline", nullable = false)
	public String getHeadline() {
		return this.headline;
	}

	public void setHeadline(String headline) {
		this.headline = headline;
	}

	@Column(name = "DescriptionMe", nullable = false, length = 65535)
	public String getDescriptionMe() {
		return this.descriptionMe;
	}

	public void setDescriptionMe(String descriptionMe) {
		this.descriptionMe = descriptionMe;
	}

	@Column(name = "Country", nullable = false)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "City", nullable = false)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DateOfBirth", nullable = false, length = 0)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "Featured", nullable = false)
	public boolean isFeatured() {
		return this.featured;
	}

	public void setFeatured(boolean featured) {
		this.featured = featured;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateReg", nullable = false, length = 0)
	public Date getDateReg() {
		return this.dateReg;
	}

	public void setDateReg(Date dateReg) {
		this.dateReg = dateReg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateLastEdit", nullable = false, length = 0)
	public Date getDateLastEdit() {
		return this.dateLastEdit;
	}

	public void setDateLastEdit(Date dateLastEdit) {
		this.dateLastEdit = dateLastEdit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateLastLogin", nullable = false, length = 0)
	public Date getDateLastLogin() {
		return this.dateLastLogin;
	}

	public void setDateLastLogin(Date dateLastLogin) {
		this.dateLastLogin = dateLastLogin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateLastNav", nullable = false, length = 0)
	public Date getDateLastNav() {
		return this.dateLastNav;
	}

	public void setDateLastNav(Date dateLastNav) {
		this.dateLastNav = dateLastNav;
	}

	@Column(name = "PrimPhoto", nullable = false)
	public int getPrimPhoto() {
		return this.primPhoto;
	}

	public void setPrimPhoto(int primPhoto) {
		this.primPhoto = primPhoto;
	}

	@Column(name = "Picture", nullable = false)
	public boolean isPicture() {
		return this.picture;
	}

	public void setPicture(boolean picture) {
		this.picture = picture;
	}

	@Column(name = "aff_num", nullable = false)
	public int getAffNum() {
		return this.affNum;
	}

	public void setAffNum(int affNum) {
		this.affNum = affNum;
	}

	@Column(name = "Tags", nullable = false)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@Column(name = "zip", nullable = false)
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Column(name = "EmailNotify", nullable = false)
	public boolean isEmailNotify() {
		return this.emailNotify;
	}

	public void setEmailNotify(boolean emailNotify) {
		this.emailNotify = emailNotify;
	}

}
