package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProfileFields generated by hbm2java
 */
@Entity
@Table(name = "ProfileFields", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "Name"))
public class ProfileFields implements java.io.Serializable {

	private Integer id;
	private String name;
	private String type;
	private String control;
	private String extra;
	private Float min;
	private Float max;
	private String values;
	private String useLkey;
	private String check;
	private boolean unique;
	private String default_;
	private boolean mandatory;
	private boolean deletable;
	private int joinPage;
	private int joinBlock;
	private Float joinOrder;
	private int editOwnBlock;
	private Float editOwnOrder;
	private int editAdmBlock;
	private Float editAdmOrder;
	private int editModBlock;
	private Float editModOrder;
	private int viewMembBlock;
	private Float viewMembOrder;
	private int viewAdmBlock;
	private Float viewAdmOrder;
	private int viewModBlock;
	private Float viewModOrder;
	private int viewVisBlock;
	private Float viewVisOrder;
	private String searchParams;
	private int searchSimpleBlock;
	private Float searchSimpleOrder;
	private int searchQuickBlock;
	private Float searchQuickOrder;
	private int searchAdvBlock;
	private Float searchAdvOrder;
	private int matchField;
	private byte matchPercent;

	public ProfileFields() {
	}

	public ProfileFields(String name, String type, String control,
			String extra, String values, String useLkey, String check,
			boolean unique, String default_, boolean mandatory,
			boolean deletable, int joinPage, int joinBlock, int editOwnBlock,
			int editAdmBlock, int editModBlock, int viewMembBlock,
			int viewAdmBlock, int viewModBlock, int viewVisBlock,
			String searchParams, int searchSimpleBlock, int searchQuickBlock,
			int searchAdvBlock, int matchField, byte matchPercent) {
		this.name = name;
		this.type = type;
		this.control = control;
		this.extra = extra;
		this.values = values;
		this.useLkey = useLkey;
		this.check = check;
		this.unique = unique;
		this.default_ = default_;
		this.mandatory = mandatory;
		this.deletable = deletable;
		this.joinPage = joinPage;
		this.joinBlock = joinBlock;
		this.editOwnBlock = editOwnBlock;
		this.editAdmBlock = editAdmBlock;
		this.editModBlock = editModBlock;
		this.viewMembBlock = viewMembBlock;
		this.viewAdmBlock = viewAdmBlock;
		this.viewModBlock = viewModBlock;
		this.viewVisBlock = viewVisBlock;
		this.searchParams = searchParams;
		this.searchSimpleBlock = searchSimpleBlock;
		this.searchQuickBlock = searchQuickBlock;
		this.searchAdvBlock = searchAdvBlock;
		this.matchField = matchField;
		this.matchPercent = matchPercent;
	}

	public ProfileFields(String name, String type, String control,
			String extra, Float min, Float max, String values, String useLkey,
			String check, boolean unique, String default_, boolean mandatory,
			boolean deletable, int joinPage, int joinBlock, Float joinOrder,
			int editOwnBlock, Float editOwnOrder, int editAdmBlock,
			Float editAdmOrder, int editModBlock, Float editModOrder,
			int viewMembBlock, Float viewMembOrder, int viewAdmBlock,
			Float viewAdmOrder, int viewModBlock, Float viewModOrder,
			int viewVisBlock, Float viewVisOrder, String searchParams,
			int searchSimpleBlock, Float searchSimpleOrder,
			int searchQuickBlock, Float searchQuickOrder, int searchAdvBlock,
			Float searchAdvOrder, int matchField, byte matchPercent) {
		this.name = name;
		this.type = type;
		this.control = control;
		this.extra = extra;
		this.min = min;
		this.max = max;
		this.values = values;
		this.useLkey = useLkey;
		this.check = check;
		this.unique = unique;
		this.default_ = default_;
		this.mandatory = mandatory;
		this.deletable = deletable;
		this.joinPage = joinPage;
		this.joinBlock = joinBlock;
		this.joinOrder = joinOrder;
		this.editOwnBlock = editOwnBlock;
		this.editOwnOrder = editOwnOrder;
		this.editAdmBlock = editAdmBlock;
		this.editAdmOrder = editAdmOrder;
		this.editModBlock = editModBlock;
		this.editModOrder = editModOrder;
		this.viewMembBlock = viewMembBlock;
		this.viewMembOrder = viewMembOrder;
		this.viewAdmBlock = viewAdmBlock;
		this.viewAdmOrder = viewAdmOrder;
		this.viewModBlock = viewModBlock;
		this.viewModOrder = viewModOrder;
		this.viewVisBlock = viewVisBlock;
		this.viewVisOrder = viewVisOrder;
		this.searchParams = searchParams;
		this.searchSimpleBlock = searchSimpleBlock;
		this.searchSimpleOrder = searchSimpleOrder;
		this.searchQuickBlock = searchQuickBlock;
		this.searchQuickOrder = searchQuickOrder;
		this.searchAdvBlock = searchAdvBlock;
		this.searchAdvOrder = searchAdvOrder;
		this.matchField = matchField;
		this.matchPercent = matchPercent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Type", nullable = false, length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "Control", nullable = false, length = 8)
	public String getControl() {
		return this.control;
	}

	public void setControl(String control) {
		this.control = control;
	}

	@Column(name = "Extra", nullable = false, length = 65535)
	public String getExtra() {
		return this.extra;
	}

	public void setExtra(String extra) {
		this.extra = extra;
	}

	@Column(name = "Min", precision = 12, scale = 0)
	public Float getMin() {
		return this.min;
	}

	public void setMin(Float min) {
		this.min = min;
	}

	@Column(name = "Max", precision = 12, scale = 0)
	public Float getMax() {
		return this.max;
	}

	public void setMax(Float max) {
		this.max = max;
	}

	@Column(name = "Values", nullable = false, length = 65535)
	public String getValues() {
		return this.values;
	}

	public void setValues(String values) {
		this.values = values;
	}

	@Column(name = "UseLKey", nullable = false, length = 5)
	public String getUseLkey() {
		return this.useLkey;
	}

	public void setUseLkey(String useLkey) {
		this.useLkey = useLkey;
	}

	@Column(name = "Check", nullable = false, length = 65535)
	public String getCheck() {
		return this.check;
	}

	public void setCheck(String check) {
		this.check = check;
	}

	@Column(name = "Unique", nullable = false)
	public boolean isUnique() {
		return this.unique;
	}

	public void setUnique(boolean unique) {
		this.unique = unique;
	}

	@Column(name = "Default", nullable = false, length = 65535)
	public String getDefault_() {
		return this.default_;
	}

	public void setDefault_(String default_) {
		this.default_ = default_;
	}

	@Column(name = "Mandatory", nullable = false)
	public boolean isMandatory() {
		return this.mandatory;
	}

	public void setMandatory(boolean mandatory) {
		this.mandatory = mandatory;
	}

	@Column(name = "Deletable", nullable = false)
	public boolean isDeletable() {
		return this.deletable;
	}

	public void setDeletable(boolean deletable) {
		this.deletable = deletable;
	}

	@Column(name = "JoinPage", nullable = false)
	public int getJoinPage() {
		return this.joinPage;
	}

	public void setJoinPage(int joinPage) {
		this.joinPage = joinPage;
	}

	@Column(name = "JoinBlock", nullable = false)
	public int getJoinBlock() {
		return this.joinBlock;
	}

	public void setJoinBlock(int joinBlock) {
		this.joinBlock = joinBlock;
	}

	@Column(name = "JoinOrder", precision = 12, scale = 0)
	public Float getJoinOrder() {
		return this.joinOrder;
	}

	public void setJoinOrder(Float joinOrder) {
		this.joinOrder = joinOrder;
	}

	@Column(name = "EditOwnBlock", nullable = false)
	public int getEditOwnBlock() {
		return this.editOwnBlock;
	}

	public void setEditOwnBlock(int editOwnBlock) {
		this.editOwnBlock = editOwnBlock;
	}

	@Column(name = "EditOwnOrder", precision = 12, scale = 0)
	public Float getEditOwnOrder() {
		return this.editOwnOrder;
	}

	public void setEditOwnOrder(Float editOwnOrder) {
		this.editOwnOrder = editOwnOrder;
	}

	@Column(name = "EditAdmBlock", nullable = false)
	public int getEditAdmBlock() {
		return this.editAdmBlock;
	}

	public void setEditAdmBlock(int editAdmBlock) {
		this.editAdmBlock = editAdmBlock;
	}

	@Column(name = "EditAdmOrder", precision = 12, scale = 0)
	public Float getEditAdmOrder() {
		return this.editAdmOrder;
	}

	public void setEditAdmOrder(Float editAdmOrder) {
		this.editAdmOrder = editAdmOrder;
	}

	@Column(name = "EditModBlock", nullable = false)
	public int getEditModBlock() {
		return this.editModBlock;
	}

	public void setEditModBlock(int editModBlock) {
		this.editModBlock = editModBlock;
	}

	@Column(name = "EditModOrder", precision = 12, scale = 0)
	public Float getEditModOrder() {
		return this.editModOrder;
	}

	public void setEditModOrder(Float editModOrder) {
		this.editModOrder = editModOrder;
	}

	@Column(name = "ViewMembBlock", nullable = false)
	public int getViewMembBlock() {
		return this.viewMembBlock;
	}

	public void setViewMembBlock(int viewMembBlock) {
		this.viewMembBlock = viewMembBlock;
	}

	@Column(name = "ViewMembOrder", precision = 12, scale = 0)
	public Float getViewMembOrder() {
		return this.viewMembOrder;
	}

	public void setViewMembOrder(Float viewMembOrder) {
		this.viewMembOrder = viewMembOrder;
	}

	@Column(name = "ViewAdmBlock", nullable = false)
	public int getViewAdmBlock() {
		return this.viewAdmBlock;
	}

	public void setViewAdmBlock(int viewAdmBlock) {
		this.viewAdmBlock = viewAdmBlock;
	}

	@Column(name = "ViewAdmOrder", precision = 12, scale = 0)
	public Float getViewAdmOrder() {
		return this.viewAdmOrder;
	}

	public void setViewAdmOrder(Float viewAdmOrder) {
		this.viewAdmOrder = viewAdmOrder;
	}

	@Column(name = "ViewModBlock", nullable = false)
	public int getViewModBlock() {
		return this.viewModBlock;
	}

	public void setViewModBlock(int viewModBlock) {
		this.viewModBlock = viewModBlock;
	}

	@Column(name = "ViewModOrder", precision = 12, scale = 0)
	public Float getViewModOrder() {
		return this.viewModOrder;
	}

	public void setViewModOrder(Float viewModOrder) {
		this.viewModOrder = viewModOrder;
	}

	@Column(name = "ViewVisBlock", nullable = false)
	public int getViewVisBlock() {
		return this.viewVisBlock;
	}

	public void setViewVisBlock(int viewVisBlock) {
		this.viewVisBlock = viewVisBlock;
	}

	@Column(name = "ViewVisOrder", precision = 12, scale = 0)
	public Float getViewVisOrder() {
		return this.viewVisOrder;
	}

	public void setViewVisOrder(Float viewVisOrder) {
		this.viewVisOrder = viewVisOrder;
	}

	@Column(name = "SearchParams", nullable = false, length = 65535)
	public String getSearchParams() {
		return this.searchParams;
	}

	public void setSearchParams(String searchParams) {
		this.searchParams = searchParams;
	}

	@Column(name = "SearchSimpleBlock", nullable = false)
	public int getSearchSimpleBlock() {
		return this.searchSimpleBlock;
	}

	public void setSearchSimpleBlock(int searchSimpleBlock) {
		this.searchSimpleBlock = searchSimpleBlock;
	}

	@Column(name = "SearchSimpleOrder", precision = 12, scale = 0)
	public Float getSearchSimpleOrder() {
		return this.searchSimpleOrder;
	}

	public void setSearchSimpleOrder(Float searchSimpleOrder) {
		this.searchSimpleOrder = searchSimpleOrder;
	}

	@Column(name = "SearchQuickBlock", nullable = false)
	public int getSearchQuickBlock() {
		return this.searchQuickBlock;
	}

	public void setSearchQuickBlock(int searchQuickBlock) {
		this.searchQuickBlock = searchQuickBlock;
	}

	@Column(name = "SearchQuickOrder", precision = 12, scale = 0)
	public Float getSearchQuickOrder() {
		return this.searchQuickOrder;
	}

	public void setSearchQuickOrder(Float searchQuickOrder) {
		this.searchQuickOrder = searchQuickOrder;
	}

	@Column(name = "SearchAdvBlock", nullable = false)
	public int getSearchAdvBlock() {
		return this.searchAdvBlock;
	}

	public void setSearchAdvBlock(int searchAdvBlock) {
		this.searchAdvBlock = searchAdvBlock;
	}

	@Column(name = "SearchAdvOrder", precision = 12, scale = 0)
	public Float getSearchAdvOrder() {
		return this.searchAdvOrder;
	}

	public void setSearchAdvOrder(Float searchAdvOrder) {
		this.searchAdvOrder = searchAdvOrder;
	}

	@Column(name = "MatchField", nullable = false)
	public int getMatchField() {
		return this.matchField;
	}

	public void setMatchField(int matchField) {
		this.matchField = matchField;
	}

	@Column(name = "MatchPercent", nullable = false)
	public byte getMatchPercent() {
		return this.matchPercent;
	}

	public void setMatchPercent(byte matchPercent) {
		this.matchPercent = matchPercent;
	}

}
