package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RayGlobalTrackUsers generated by hbm2java
 */
@Entity
@Table(name = "RayGlobalTrackUsers", catalog = "dolphin")
public class RayGlobalTrackUsers implements java.io.Serializable {

	private int id;
	private long when;
	private String status;

	public RayGlobalTrackUsers() {
	}

	public RayGlobalTrackUsers(int id, long when, String status) {
		this.id = id;
		this.when = when;
		this.status = status;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "When", nullable = false)
	public long getWhen() {
		return this.when;
	}

	public void setWhen(long when) {
		this.when = when;
	}

	@Column(name = "Status", nullable = false, length = 7)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
