package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RayImPendings generated by hbm2java
 */
@Entity
@Table(name = "RayImPendings", catalog = "dolphin")
public class RayImPendings implements java.io.Serializable {

	private Integer id;
	private int senderId;
	private int recipientId;
	private String message;
	private int when;

	public RayImPendings() {
	}

	public RayImPendings(int senderId, int recipientId, String message, int when) {
		this.senderId = senderId;
		this.recipientId = recipientId;
		this.message = message;
		this.when = when;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "SenderID", nullable = false)
	public int getSenderId() {
		return this.senderId;
	}

	public void setSenderId(int senderId) {
		this.senderId = senderId;
	}

	@Column(name = "RecipientID", nullable = false)
	public int getRecipientId() {
		return this.recipientId;
	}

	public void setRecipientId(int recipientId) {
		this.recipientId = recipientId;
	}

	@Column(name = "Message", nullable = false)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "When", nullable = false)
	public int getWhen() {
		return this.when;
	}

	public void setWhen(int when) {
		this.when = when;
	}

}
