package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RayImProfiles generated by hbm2java
 */
@Entity
@Table(name = "RayImProfiles", catalog = "dolphin")
public class RayImProfiles implements java.io.Serializable {

	private int id;
	private String smileset;

	public RayImProfiles() {
	}

	public RayImProfiles(int id, String smileset) {
		this.id = id;
		this.smileset = smileset;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Smileset", nullable = false)
	public String getSmileset() {
		return this.smileset;
	}

	public void setSmileset(String smileset) {
		this.smileset = smileset;
	}

}
