package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RayVideoStats generated by hbm2java
 */
@Entity
@Table(name = "RayVideoStats", catalog = "dolphin")
public class RayVideoStats implements java.io.Serializable {

	private String user;
	private int approved;
	private int pending;

	public RayVideoStats() {
	}

	public RayVideoStats(String user, int approved, int pending) {
		this.user = user;
		this.approved = approved;
		this.pending = pending;
	}

	@Id
	@Column(name = "User", unique = true, nullable = false, length = 64)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "Approved", nullable = false)
	public int getApproved() {
		return this.approved;
	}

	public void setApproved(int approved) {
		this.approved = approved;
	}

	@Column(name = "Pending", nullable = false)
	public int getPending() {
		return this.pending;
	}

	public void setPending(int pending) {
		this.pending = pending;
	}

}
