package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SdatingParticipants generated by hbm2java
 */
@Entity
@Table(name = "SDatingParticipants", catalog = "dolphin", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "IDEvent", "IDMember" }),
		@UniqueConstraint(columnNames = { "IDEvent", "ParticipantUID" }) })
public class SdatingParticipants implements java.io.Serializable {

	private Long id;
	private int idevent;
	private long idmember;
	private String participantUid;
	private Long transactionId;

	public SdatingParticipants() {
	}

	public SdatingParticipants(int idevent, long idmember, String participantUid) {
		this.idevent = idevent;
		this.idmember = idmember;
		this.participantUid = participantUid;
	}

	public SdatingParticipants(int idevent, long idmember,
			String participantUid, Long transactionId) {
		this.idevent = idevent;
		this.idmember = idmember;
		this.participantUid = participantUid;
		this.transactionId = transactionId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "IDEvent", nullable = false)
	public int getIdevent() {
		return this.idevent;
	}

	public void setIdevent(int idevent) {
		this.idevent = idevent;
	}

	@Column(name = "IDMember", nullable = false)
	public long getIdmember() {
		return this.idmember;
	}

	public void setIdmember(long idmember) {
		this.idmember = idmember;
	}

	@Column(name = "ParticipantUID", nullable = false, length = 30)
	public String getParticipantUid() {
		return this.participantUid;
	}

	public void setParticipantUid(String participantUid) {
		this.participantUid = participantUid;
	}

	@Column(name = "TransactionID")
	public Long getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Long transactionId) {
		this.transactionId = transactionId;
	}

}
