package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * SdatingEvents generated by hbm2java
 */
@Entity
@Table(name = "SDatingEvents", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "EntryUri"))
public class SdatingEvents implements java.io.Serializable {

	private Integer id;
	private String title;
	private String entryUri;
	private String description;
	private String status;
	private String statusMessage;
	private String country;
	private String city;
	private String place;
	private String photoFilename;
	private Date eventStart;
	private Date eventEnd;
	private Date ticketSaleStart;
	private Date ticketSaleEnd;
	private long responsibleId;
	private String responsibleName;
	private String responsibleEmail;
	private String responsiblePhone;
	private String eventSexFilter;
	private byte eventAgeLowerFilter;
	private byte eventAgeUpperFilter;
	private String eventMembershipFilter;
	private short ticketCountFemale;
	private short ticketCountMale;
	private short ticketCountCouple;
	private float ticketPriceFemale;
	private float ticketPriceMale;
	private float ticketPriceCouple;
	private short choosePeriod;
	private boolean allowViewParticipants;
	private String tags;

	public SdatingEvents() {
	}

	public SdatingEvents(String title, String entryUri, String description,
			String status, String statusMessage, String country, String city,
			String place, String photoFilename, Date eventStart, Date eventEnd,
			Date ticketSaleStart, Date ticketSaleEnd, long responsibleId,
			String responsibleName, String responsibleEmail,
			String responsiblePhone, String eventSexFilter,
			byte eventAgeLowerFilter, byte eventAgeUpperFilter,
			String eventMembershipFilter, short ticketCountFemale,
			short ticketCountMale, short ticketCountCouple,
			float ticketPriceFemale, float ticketPriceMale,
			float ticketPriceCouple, short choosePeriod,
			boolean allowViewParticipants, String tags) {
		this.title = title;
		this.entryUri = entryUri;
		this.description = description;
		this.status = status;
		this.statusMessage = statusMessage;
		this.country = country;
		this.city = city;
		this.place = place;
		this.photoFilename = photoFilename;
		this.eventStart = eventStart;
		this.eventEnd = eventEnd;
		this.ticketSaleStart = ticketSaleStart;
		this.ticketSaleEnd = ticketSaleEnd;
		this.responsibleId = responsibleId;
		this.responsibleName = responsibleName;
		this.responsibleEmail = responsibleEmail;
		this.responsiblePhone = responsiblePhone;
		this.eventSexFilter = eventSexFilter;
		this.eventAgeLowerFilter = eventAgeLowerFilter;
		this.eventAgeUpperFilter = eventAgeUpperFilter;
		this.eventMembershipFilter = eventMembershipFilter;
		this.ticketCountFemale = ticketCountFemale;
		this.ticketCountMale = ticketCountMale;
		this.ticketCountCouple = ticketCountCouple;
		this.ticketPriceFemale = ticketPriceFemale;
		this.ticketPriceMale = ticketPriceMale;
		this.ticketPriceCouple = ticketPriceCouple;
		this.choosePeriod = choosePeriod;
		this.allowViewParticipants = allowViewParticipants;
		this.tags = tags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Title", nullable = false, length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "EntryUri", unique = true, nullable = false, length = 100)
	public String getEntryUri() {
		return this.entryUri;
	}

	public void setEntryUri(String entryUri) {
		this.entryUri = entryUri;
	}

	@Column(name = "Description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "StatusMessage", nullable = false)
	public String getStatusMessage() {
		return this.statusMessage;
	}

	public void setStatusMessage(String statusMessage) {
		this.statusMessage = statusMessage;
	}

	@Column(name = "Country", nullable = false, length = 2)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "City", nullable = false, length = 50)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "Place", nullable = false, length = 100)
	public String getPlace() {
		return this.place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "PhotoFilename", nullable = false)
	public String getPhotoFilename() {
		return this.photoFilename;
	}

	public void setPhotoFilename(String photoFilename) {
		this.photoFilename = photoFilename;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EventStart", nullable = false, length = 0)
	public Date getEventStart() {
		return this.eventStart;
	}

	public void setEventStart(Date eventStart) {
		this.eventStart = eventStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EventEnd", nullable = false, length = 0)
	public Date getEventEnd() {
		return this.eventEnd;
	}

	public void setEventEnd(Date eventEnd) {
		this.eventEnd = eventEnd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TicketSaleStart", nullable = false, length = 0)
	public Date getTicketSaleStart() {
		return this.ticketSaleStart;
	}

	public void setTicketSaleStart(Date ticketSaleStart) {
		this.ticketSaleStart = ticketSaleStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TicketSaleEnd", nullable = false, length = 0)
	public Date getTicketSaleEnd() {
		return this.ticketSaleEnd;
	}

	public void setTicketSaleEnd(Date ticketSaleEnd) {
		this.ticketSaleEnd = ticketSaleEnd;
	}

	@Column(name = "ResponsibleID", nullable = false)
	public long getResponsibleId() {
		return this.responsibleId;
	}

	public void setResponsibleId(long responsibleId) {
		this.responsibleId = responsibleId;
	}

	@Column(name = "ResponsibleName", nullable = false, length = 50)
	public String getResponsibleName() {
		return this.responsibleName;
	}

	public void setResponsibleName(String responsibleName) {
		this.responsibleName = responsibleName;
	}

	@Column(name = "ResponsibleEmail", nullable = false, length = 50)
	public String getResponsibleEmail() {
		return this.responsibleEmail;
	}

	public void setResponsibleEmail(String responsibleEmail) {
		this.responsibleEmail = responsibleEmail;
	}

	@Column(name = "ResponsiblePhone", nullable = false, length = 30)
	public String getResponsiblePhone() {
		return this.responsiblePhone;
	}

	public void setResponsiblePhone(String responsiblePhone) {
		this.responsiblePhone = responsiblePhone;
	}

	@Column(name = "EventSexFilter", nullable = false, length = 19)
	public String getEventSexFilter() {
		return this.eventSexFilter;
	}

	public void setEventSexFilter(String eventSexFilter) {
		this.eventSexFilter = eventSexFilter;
	}

	@Column(name = "EventAgeLowerFilter", nullable = false)
	public byte getEventAgeLowerFilter() {
		return this.eventAgeLowerFilter;
	}

	public void setEventAgeLowerFilter(byte eventAgeLowerFilter) {
		this.eventAgeLowerFilter = eventAgeLowerFilter;
	}

	@Column(name = "EventAgeUpperFilter", nullable = false)
	public byte getEventAgeUpperFilter() {
		return this.eventAgeUpperFilter;
	}

	public void setEventAgeUpperFilter(byte eventAgeUpperFilter) {
		this.eventAgeUpperFilter = eventAgeUpperFilter;
	}

	@Column(name = "EventMembershipFilter", nullable = false, length = 100)
	public String getEventMembershipFilter() {
		return this.eventMembershipFilter;
	}

	public void setEventMembershipFilter(String eventMembershipFilter) {
		this.eventMembershipFilter = eventMembershipFilter;
	}

	@Column(name = "TicketCountFemale", nullable = false)
	public short getTicketCountFemale() {
		return this.ticketCountFemale;
	}

	public void setTicketCountFemale(short ticketCountFemale) {
		this.ticketCountFemale = ticketCountFemale;
	}

	@Column(name = "TicketCountMale", nullable = false)
	public short getTicketCountMale() {
		return this.ticketCountMale;
	}

	public void setTicketCountMale(short ticketCountMale) {
		this.ticketCountMale = ticketCountMale;
	}

	@Column(name = "TicketCountCouple", nullable = false)
	public short getTicketCountCouple() {
		return this.ticketCountCouple;
	}

	public void setTicketCountCouple(short ticketCountCouple) {
		this.ticketCountCouple = ticketCountCouple;
	}

	@Column(name = "TicketPriceFemale", nullable = false, precision = 5)
	public float getTicketPriceFemale() {
		return this.ticketPriceFemale;
	}

	public void setTicketPriceFemale(float ticketPriceFemale) {
		this.ticketPriceFemale = ticketPriceFemale;
	}

	@Column(name = "TicketPriceMale", nullable = false, precision = 5)
	public float getTicketPriceMale() {
		return this.ticketPriceMale;
	}

	public void setTicketPriceMale(float ticketPriceMale) {
		this.ticketPriceMale = ticketPriceMale;
	}

	@Column(name = "TicketPriceCouple", nullable = false, precision = 5)
	public float getTicketPriceCouple() {
		return this.ticketPriceCouple;
	}

	public void setTicketPriceCouple(float ticketPriceCouple) {
		this.ticketPriceCouple = ticketPriceCouple;
	}

	@Column(name = "ChoosePeriod", nullable = false)
	public short getChoosePeriod() {
		return this.choosePeriod;
	}

	public void setChoosePeriod(short choosePeriod) {
		this.choosePeriod = choosePeriod;
	}

	@Column(name = "AllowViewParticipants", nullable = false)
	public boolean isAllowViewParticipants() {
		return this.allowViewParticipants;
	}

	public void setAllowViewParticipants(boolean allowViewParticipants) {
		this.allowViewParticipants = allowViewParticipants;
	}

	@Column(name = "Tags", nullable = false)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

}
