package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SharePhotoFiles generated by hbm2java
 */
@Entity
@Table(name = "sharePhotoFiles", catalog = "dolphin", uniqueConstraints = @UniqueConstraint(columnNames = "medUri"))
public class SharePhotoFiles implements java.io.Serializable {

	private Integer medId;
	private Integer medProfId;
	private String medExt;
	private String medTitle;
	private String medUri;
	private String medDesc;
	private String medTags;
	private int medDate;
	private Integer medViews;
	private String approved;

	public SharePhotoFiles() {
	}

	public SharePhotoFiles(String medUri, String medDesc, String medTags,
			int medDate, String approved) {
		this.medUri = medUri;
		this.medDesc = medDesc;
		this.medTags = medTags;
		this.medDate = medDate;
		this.approved = approved;
	}

	public SharePhotoFiles(Integer medProfId, String medExt, String medTitle,
			String medUri, String medDesc, String medTags, int medDate,
			Integer medViews, String approved) {
		this.medProfId = medProfId;
		this.medExt = medExt;
		this.medTitle = medTitle;
		this.medUri = medUri;
		this.medDesc = medDesc;
		this.medTags = medTags;
		this.medDate = medDate;
		this.medViews = medViews;
		this.approved = approved;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "medID", unique = true, nullable = false)
	public Integer getMedId() {
		return this.medId;
	}

	public void setMedId(Integer medId) {
		this.medId = medId;
	}

	@Column(name = "medProfId")
	public Integer getMedProfId() {
		return this.medProfId;
	}

	public void setMedProfId(Integer medProfId) {
		this.medProfId = medProfId;
	}

	@Column(name = "medExt", length = 4)
	public String getMedExt() {
		return this.medExt;
	}

	public void setMedExt(String medExt) {
		this.medExt = medExt;
	}

	@Column(name = "medTitle")
	public String getMedTitle() {
		return this.medTitle;
	}

	public void setMedTitle(String medTitle) {
		this.medTitle = medTitle;
	}

	@Column(name = "medUri", unique = true, nullable = false)
	public String getMedUri() {
		return this.medUri;
	}

	public void setMedUri(String medUri) {
		this.medUri = medUri;
	}

	@Column(name = "medDesc", nullable = false, length = 65535)
	public String getMedDesc() {
		return this.medDesc;
	}

	public void setMedDesc(String medDesc) {
		this.medDesc = medDesc;
	}

	@Column(name = "medTags", nullable = false)
	public String getMedTags() {
		return this.medTags;
	}

	public void setMedTags(String medTags) {
		this.medTags = medTags;
	}

	@Column(name = "medDate", nullable = false)
	public int getMedDate() {
		return this.medDate;
	}

	public void setMedDate(int medDate) {
		this.medDate = medDate;
	}

	@Column(name = "medViews")
	public Integer getMedViews() {
		return this.medViews;
	}

	public void setMedViews(Integer medViews) {
		this.medViews = medViews;
	}

	@Column(name = "Approved", nullable = false, length = 5)
	public String getApproved() {
		return this.approved;
	}

	public void setApproved(String approved) {
		this.approved = approved;
	}

}
