package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SharePhotoFavoritesId generated by hbm2java
 */
@Embeddable
public class SharePhotoFavoritesId implements java.io.Serializable {

	private int medId;
	private long userId;

	public SharePhotoFavoritesId() {
	}

	public SharePhotoFavoritesId(int medId, long userId) {
		this.medId = medId;
		this.userId = userId;
	}

	@Column(name = "medID", nullable = false)
	public int getMedId() {
		return this.medId;
	}

	public void setMedId(int medId) {
		this.medId = medId;
	}

	@Column(name = "userID", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SharePhotoFavoritesId))
			return false;
		SharePhotoFavoritesId castOther = (SharePhotoFavoritesId) other;

		return (this.getMedId() == castOther.getMedId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMedId();
		result = 37 * result + (int) this.getUserId();
		return result;
	}

}
