package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SiteStat generated by hbm2java
 */
@Entity
@Table(name = "SiteStat", catalog = "dolphin")
public class SiteStat implements java.io.Serializable {

	private Integer id;
	private String name;
	private String title;
	private String userLink;
	private String userQuery;
	private String adminLink;
	private String adminQuery;
	private String iconName;
	private int statOrder;

	public SiteStat() {
	}

	public SiteStat(String name, String title, String userLink,
			String userQuery, String adminLink, String adminQuery,
			String iconName, int statOrder) {
		this.name = name;
		this.title = title;
		this.userLink = userLink;
		this.userQuery = userQuery;
		this.adminLink = adminLink;
		this.adminQuery = adminQuery;
		this.iconName = iconName;
		this.statOrder = statOrder;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 3)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Title", nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "UserLink", nullable = false)
	public String getUserLink() {
		return this.userLink;
	}

	public void setUserLink(String userLink) {
		this.userLink = userLink;
	}

	@Column(name = "UserQuery", nullable = false, length = 150)
	public String getUserQuery() {
		return this.userQuery;
	}

	public void setUserQuery(String userQuery) {
		this.userQuery = userQuery;
	}

	@Column(name = "AdminLink", nullable = false)
	public String getAdminLink() {
		return this.adminLink;
	}

	public void setAdminLink(String adminLink) {
		this.adminLink = adminLink;
	}

	@Column(name = "AdminQuery", nullable = false)
	public String getAdminQuery() {
		return this.adminQuery;
	}

	public void setAdminQuery(String adminQuery) {
		this.adminQuery = adminQuery;
	}

	@Column(name = "IconName", nullable = false, length = 50)
	public String getIconName() {
		return this.iconName;
	}

	public void setIconName(String iconName) {
		this.iconName = iconName;
	}

	@Column(name = "StatOrder", nullable = false)
	public int getStatOrder() {
		return this.statOrder;
	}

	public void setStatOrder(int statOrder) {
		this.statOrder = statOrder;
	}

}
