package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "Tags", catalog = "dolphin")
public class Tags implements java.io.Serializable {

	private TagsId id;

	public Tags() {
	}

	public Tags(TagsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "tag", column = @Column(name = "Tag", nullable = false, length = 32)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "Type", nullable = false, length = 8)) })
	public TagsId getId() {
		return this.id;
	}

	public void setId(TagsId id) {
		this.id = id;
	}

}
