package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name = "Transactions", catalog = "dolphin")
public class Transactions implements java.io.Serializable {

	private Long id;
	private long idmember;
	private short idprovider;
	private String gtwTransactionId;
	private Date date;
	private float amount;
	private String currency;
	private String status;
	private String data;
	private String description;
	private String note;

	public Transactions() {
	}

	public Transactions(long idmember, short idprovider,
			String gtwTransactionId, Date date, float amount, String currency,
			String status, String data) {
		this.idmember = idmember;
		this.idprovider = idprovider;
		this.gtwTransactionId = gtwTransactionId;
		this.date = date;
		this.amount = amount;
		this.currency = currency;
		this.status = status;
		this.data = data;
	}

	public Transactions(long idmember, short idprovider,
			String gtwTransactionId, Date date, float amount, String currency,
			String status, String data, String description, String note) {
		this.idmember = idmember;
		this.idprovider = idprovider;
		this.gtwTransactionId = gtwTransactionId;
		this.date = date;
		this.amount = amount;
		this.currency = currency;
		this.status = status;
		this.data = data;
		this.description = description;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "IDMember", nullable = false)
	public long getIdmember() {
		return this.idmember;
	}

	public void setIdmember(long idmember) {
		this.idmember = idmember;
	}

	@Column(name = "IDProvider", nullable = false)
	public short getIdprovider() {
		return this.idprovider;
	}

	public void setIdprovider(short idprovider) {
		this.idprovider = idprovider;
	}

	@Column(name = "gtwTransactionID", nullable = false, length = 32)
	public String getGtwTransactionId() {
		return this.gtwTransactionId;
	}

	public void setGtwTransactionId(String gtwTransactionId) {
		this.gtwTransactionId = gtwTransactionId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Amount", nullable = false, precision = 12, scale = 0)
	public float getAmount() {
		return this.amount;
	}

	public void setAmount(float amount) {
		this.amount = amount;
	}

	@Column(name = "Currency", nullable = false, length = 3)
	public String getCurrency() {
		return this.currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "Status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "Data", nullable = false, length = 65535)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Note")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
