package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VkissesId generated by hbm2java
 */
@Embeddable
public class VkissesId implements java.io.Serializable {

	private long id;
	private long member;

	public VkissesId() {
	}

	public VkissesId(long id, long member) {
		this.id = id;
		this.member = member;
	}

	@Column(name = "ID", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "Member", nullable = false)
	public long getMember() {
		return this.member;
	}

	public void setMember(long member) {
		this.member = member;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VkissesId))
			return false;
		VkissesId castOther = (VkissesId) other;

		return (this.getId() == castOther.getId())
				&& (this.getMember() == castOther.getMember());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (int) this.getMember();
		return result;
	}

}
