package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ZipcodesId generated by hbm2java
 */
@Embeddable
public class ZipcodesId implements java.io.Serializable {

	private String zipcode;
	private Character zipcodeType;
	private String city;
	private Character cityType;
	private String county;
	private String countyFips;
	private String state;
	private String stateCode;
	private String stateFips;
	private String msa;
	private String areaCode;
	private String timeZone;
	private Integer gmtoffset;
	private Character dst;
	private Double latitude;
	private Double longitude;

	public ZipcodesId() {
	}

	public ZipcodesId(String zipcode, Character zipcodeType, String city,
			Character cityType, String county, String countyFips, String state,
			String stateCode, String stateFips, String msa, String areaCode,
			String timeZone, Integer gmtoffset, Character dst, Double latitude,
			Double longitude) {
		this.zipcode = zipcode;
		this.zipcodeType = zipcodeType;
		this.city = city;
		this.cityType = cityType;
		this.county = county;
		this.countyFips = countyFips;
		this.state = state;
		this.stateCode = stateCode;
		this.stateFips = stateFips;
		this.msa = msa;
		this.areaCode = areaCode;
		this.timeZone = timeZone;
		this.gmtoffset = gmtoffset;
		this.dst = dst;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	@Column(name = "ZIPCode", length = 8)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "ZIPCodeType", length = 1)
	public Character getZipcodeType() {
		return this.zipcodeType;
	}

	public void setZipcodeType(Character zipcodeType) {
		this.zipcodeType = zipcodeType;
	}

	@Column(name = "City", length = 28)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "CityType", length = 1)
	public Character getCityType() {
		return this.cityType;
	}

	public void setCityType(Character cityType) {
		this.cityType = cityType;
	}

	@Column(name = "County", length = 25)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "CountyFIPS", length = 5)
	public String getCountyFips() {
		return this.countyFips;
	}

	public void setCountyFips(String countyFips) {
		this.countyFips = countyFips;
	}

	@Column(name = "State", length = 30)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "StateCode", length = 2)
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "StateFIPS", length = 2)
	public String getStateFips() {
		return this.stateFips;
	}

	public void setStateFips(String stateFips) {
		this.stateFips = stateFips;
	}

	@Column(name = "MSA", length = 4)
	public String getMsa() {
		return this.msa;
	}

	public void setMsa(String msa) {
		this.msa = msa;
	}

	@Column(name = "AreaCode", length = 3)
	public String getAreaCode() {
		return this.areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	@Column(name = "TimeZone", length = 10)
	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	@Column(name = "GMTOffset")
	public Integer getGmtoffset() {
		return this.gmtoffset;
	}

	public void setGmtoffset(Integer gmtoffset) {
		this.gmtoffset = gmtoffset;
	}

	@Column(name = "DST", length = 1)
	public Character getDst() {
		return this.dst;
	}

	public void setDst(Character dst) {
		this.dst = dst;
	}

	@Column(name = "Latitude", precision = 22, scale = 0)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longitude", precision = 22, scale = 0)
	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZipcodesId))
			return false;
		ZipcodesId castOther = (ZipcodesId) other;

		return ((this.getZipcode() == castOther.getZipcode()) || (this
				.getZipcode() != null
				&& castOther.getZipcode() != null && this.getZipcode().equals(
				castOther.getZipcode())))
				&& ((this.getZipcodeType() == castOther.getZipcodeType()) || (this
						.getZipcodeType() != null
						&& castOther.getZipcodeType() != null && this
						.getZipcodeType().equals(castOther.getZipcodeType())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null
						&& castOther.getCity() != null && this.getCity()
						.equals(castOther.getCity())))
				&& ((this.getCityType() == castOther.getCityType()) || (this
						.getCityType() != null
						&& castOther.getCityType() != null && this
						.getCityType().equals(castOther.getCityType())))
				&& ((this.getCounty() == castOther.getCounty()) || (this
						.getCounty() != null
						&& castOther.getCounty() != null && this.getCounty()
						.equals(castOther.getCounty())))
				&& ((this.getCountyFips() == castOther.getCountyFips()) || (this
						.getCountyFips() != null
						&& castOther.getCountyFips() != null && this
						.getCountyFips().equals(castOther.getCountyFips())))
				&& ((this.getState() == castOther.getState()) || (this
						.getState() != null
						&& castOther.getState() != null && this.getState()
						.equals(castOther.getState())))
				&& ((this.getStateCode() == castOther.getStateCode()) || (this
						.getStateCode() != null
						&& castOther.getStateCode() != null && this
						.getStateCode().equals(castOther.getStateCode())))
				&& ((this.getStateFips() == castOther.getStateFips()) || (this
						.getStateFips() != null
						&& castOther.getStateFips() != null && this
						.getStateFips().equals(castOther.getStateFips())))
				&& ((this.getMsa() == castOther.getMsa()) || (this.getMsa() != null
						&& castOther.getMsa() != null && this.getMsa().equals(
						castOther.getMsa())))
				&& ((this.getAreaCode() == castOther.getAreaCode()) || (this
						.getAreaCode() != null
						&& castOther.getAreaCode() != null && this
						.getAreaCode().equals(castOther.getAreaCode())))
				&& ((this.getTimeZone() == castOther.getTimeZone()) || (this
						.getTimeZone() != null
						&& castOther.getTimeZone() != null && this
						.getTimeZone().equals(castOther.getTimeZone())))
				&& ((this.getGmtoffset() == castOther.getGmtoffset()) || (this
						.getGmtoffset() != null
						&& castOther.getGmtoffset() != null && this
						.getGmtoffset().equals(castOther.getGmtoffset())))
				&& ((this.getDst() == castOther.getDst()) || (this.getDst() != null
						&& castOther.getDst() != null && this.getDst().equals(
						castOther.getDst())))
				&& ((this.getLatitude() == castOther.getLatitude()) || (this
						.getLatitude() != null
						&& castOther.getLatitude() != null && this
						.getLatitude().equals(castOther.getLatitude())))
				&& ((this.getLongitude() == castOther.getLongitude()) || (this
						.getLongitude() != null
						&& castOther.getLongitude() != null && this
						.getLongitude().equals(castOther.getLongitude())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getZipcode() == null ? 0 : this.getZipcode().hashCode());
		result = 37
				* result
				+ (getZipcodeType() == null ? 0 : this.getZipcodeType()
						.hashCode());
		result = 37 * result
				+ (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result
				+ (getCityType() == null ? 0 : this.getCityType().hashCode());
		result = 37 * result
				+ (getCounty() == null ? 0 : this.getCounty().hashCode());
		result = 37
				* result
				+ (getCountyFips() == null ? 0 : this.getCountyFips()
						.hashCode());
		result = 37 * result
				+ (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result
				+ (getStateCode() == null ? 0 : this.getStateCode().hashCode());
		result = 37 * result
				+ (getStateFips() == null ? 0 : this.getStateFips().hashCode());
		result = 37 * result
				+ (getMsa() == null ? 0 : this.getMsa().hashCode());
		result = 37 * result
				+ (getAreaCode() == null ? 0 : this.getAreaCode().hashCode());
		result = 37 * result
				+ (getTimeZone() == null ? 0 : this.getTimeZone().hashCode());
		result = 37 * result
				+ (getGmtoffset() == null ? 0 : this.getGmtoffset().hashCode());
		result = 37 * result
				+ (getDst() == null ? 0 : this.getDst().hashCode());
		result = 37 * result
				+ (getLatitude() == null ? 0 : this.getLatitude().hashCode());
		result = 37 * result
				+ (getLongitude() == null ? 0 : this.getLongitude().hashCode());
		return result;
	}

}
