package org.dwbn.userreg.model.dolphin;

// Generated May 12, 2008 11:13:52 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Zipcodes generated by hbm2java
 */
@Entity
@Table(name = "ZIPCodes", catalog = "dolphin")
public class Zipcodes implements java.io.Serializable {

	private ZipcodesId id;

	public Zipcodes() {
	}

	public Zipcodes(ZipcodesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "zipcode", column = @Column(name = "ZIPCode", length = 8)),
			@AttributeOverride(name = "zipcodeType", column = @Column(name = "ZIPCodeType", length = 1)),
			@AttributeOverride(name = "city", column = @Column(name = "City", length = 28)),
			@AttributeOverride(name = "cityType", column = @Column(name = "CityType", length = 1)),
			@AttributeOverride(name = "county", column = @Column(name = "County", length = 25)),
			@AttributeOverride(name = "countyFips", column = @Column(name = "CountyFIPS", length = 5)),
			@AttributeOverride(name = "state", column = @Column(name = "State", length = 30)),
			@AttributeOverride(name = "stateCode", column = @Column(name = "StateCode", length = 2)),
			@AttributeOverride(name = "stateFips", column = @Column(name = "StateFIPS", length = 2)),
			@AttributeOverride(name = "msa", column = @Column(name = "MSA", length = 4)),
			@AttributeOverride(name = "areaCode", column = @Column(name = "AreaCode", length = 3)),
			@AttributeOverride(name = "timeZone", column = @Column(name = "TimeZone", length = 10)),
			@AttributeOverride(name = "gmtoffset", column = @Column(name = "GMTOffset")),
			@AttributeOverride(name = "dst", column = @Column(name = "DST", length = 1)),
			@AttributeOverride(name = "latitude", column = @Column(name = "Latitude", precision = 22, scale = 0)),
			@AttributeOverride(name = "longitude", column = @Column(name = "Longitude", precision = 22, scale = 0)) })
	public ZipcodesId getId() {
		return this.id;
	}

	public void setId(ZipcodesId id) {
		this.id = id;
	}

}
