// cache of Page View composer

return array(
  //pages
  'ads' => array(
    'Width' => '960px',
    'Columns' => array(
      1 => array(
        'Width'  => 50,
        'Blocks' => array(
          45 => array(
            'Func'      => 'AdPhotos',
            'Content'   => '',
            'Caption'   => '_Advertisement Photos',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          46 => array(
            'Func'      => 'ActionList',
            'Content'   => '',
            'Caption'   => '_Actions',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          47 => array(
            'Func'      => 'ViewComments',
            'Content'   => '',
            'Caption'   => '_Comments',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
      2 => array(
        'Width'  => 50,
        'Blocks' => array(
          48 => array(
            'Func'      => 'AdInfo',
            'Content'   => '',
            'Caption'   => '_Info',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          49 => array(
            'Func'      => 'Description',
            'Content'   => '',
            'Caption'   => '_Description',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          50 => array(
            'Func'      => 'UserOtherAds',
            'Content'   => '',
            'Caption'   => '_Users Other Listing',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
    )
  ),
  'index' => array(
    'Width' => '960px',
    'Columns' => array(
      1 => array(
        'Width'  => 60,
        'Blocks' => array(
          1 => array(
            'Func'      => 'SiteStats',
            'Content'   => '',
            'Caption'   => '_Site Stats',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          15 => array(
            'Func'      => 'RSS',
            'Content'   => 'http://www.boonex.com/unity/blog/featured_posts/?rss=1#4',
            'Caption'   => '_BoonEx News',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          10 => array(
            'Func'      => 'Members',
            'Content'   => '',
            'Caption'   => '_Members',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          5 => array(
            'Func'      => 'Leaders',
            'Content'   => '',
            'Caption'   => '_Leaders',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          11 => array(
            'Func'      => 'Blogs',
            'Content'   => '',
            'Caption'   => '_Blogs',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          7 => array(
            'Func'      => 'Featured',
            'Content'   => '',
            'Caption'   => '_featured members',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          21 => array(
            'Func'      => 'ShareVideos',
            'Content'   => '',
            'Caption'   => '_Video Gallery',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          20 => array(
            'Func'      => 'SharePhotos',
            'Content'   => '',
            'Caption'   => '_Photo Gallery',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          22 => array(
            'Func'      => 'ShareMusic',
            'Content'   => '',
            'Caption'   => '_Music Gallery',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          12 => array(
            'Func'      => 'ProfilePhotos',
            'Content'   => '',
            'Caption'   => '_Profile Photos',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          17 => array(
            'Func'      => 'Events',
            'Content'   => '',
            'Caption'   => '_Events',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          23 => array(
            'Func'      => 'Articles',
            'Content'   => '',
            'Caption'   => '_Articles',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          18 => array(
            'Func'      => 'Groups',
            'Content'   => '',
            'Caption'   => '_Groups',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          16 => array(
            'Func'      => 'Classifieds',
            'Content'   => '',
            'Caption'   => '_Classifieds',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
      2 => array(
        'Width'  => 40,
        'Blocks' => array(
          14 => array(
            'Func'      => 'LoginSection',
            'Content'   => '',
            'Caption'   => '_Member Login',
            'Visible'   => 'non',
            'DesignBox' => 1
          ),
          13 => array(
            'Func'      => 'Shoutbox',
            'Content'   => '',
            'Caption'   => '_Shoutbox',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          4 => array(
            'Func'      => 'QuickSearch',
            'Content'   => '',
            'Caption'   => '_Quick Search',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          9 => array(
            'Func'      => 'Tags',
            'Content'   => '',
            'Caption'   => '_Tags',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          2 => array(
            'Func'      => 'News',
            'Content'   => '',
            'Caption'   => '_latest news',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          19 => array(
            'Func'      => 'RSS',
            'Content'   => '{SiteUrl}orca/?action=rss_all#4',
            'Caption'   => '_Forum Posts',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          3 => array(
            'Func'      => 'Subscribe',
            'Content'   => '',
            'Caption'   => '_Subscribe',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          8 => array(
            'Func'      => 'ProfilePoll',
            'Content'   => '',
            'Caption'   => '_Polls',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          6 => array(
            'Func'      => 'Feedback',
            'Content'   => '',
            'Caption'   => '_Feedback',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
    )
  ),
  'member' => array(
    'Width' => '960px',
    'Columns' => array(
      1 => array(
        'Width'  => 50,
        'Blocks' => array(
          57 => array(
            'Func'      => 'Classifieds',
            'Content'   => '',
            'Caption'   => '_Classifieds',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          52 => array(
            'Func'      => 'SiteStats',
            'Content'   => '',
            'Caption'   => '_Site Stats',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          58 => array(
            'Func'      => 'Events',
            'Content'   => '',
            'Caption'   => '_Events',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          59 => array(
            'Func'      => 'Groups',
            'Content'   => '',
            'Caption'   => '_Groups',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          88 => array(
            'Func'      => 'Friends',
            'Content'   => '',
            'Caption'   => '_My Friends',
            'Visible'   => 'memb',
            'DesignBox' => 1
          ),
        )
      ),
      2 => array(
        'Width'  => 50,
        'Blocks' => array(
          53 => array(
            'Func'      => 'MemberInfo',
            'Content'   => '',
            'Caption'   => '_member info',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          54 => array(
            'Func'      => 'Contacts',
            'Content'   => '',
            'Caption'   => '_contacts',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          55 => array(
            'Func'      => 'News',
            'Content'   => '',
            'Caption'   => '_latest news',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          60 => array(
            'Func'      => 'RSS',
            'Content'   => '{SiteUrl}orca/?action=rss_user&user={NickName}#4',
            'Caption'   => '_Forum Posts',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          61 => array(
            'Func'      => 'ShareMusic',
            'Content'   => '',
            'Caption'   => '_My Music Gallery',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          62 => array(
            'Func'      => 'SharePhotos',
            'Content'   => '',
            'Caption'   => '_My Photo Gallery',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          63 => array(
            'Func'      => 'ShareVideos',
            'Content'   => '',
            'Caption'   => '_My Video Gallery',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
    )
  ),
  'music' => array(
    'Width' => '960px',
    'Columns' => array(
      1 => array(
        'Width'  => 50,
        'Blocks' => array(
          24 => array(
            'Func'      => 'ViewFile',
            'Content'   => '',
            'Caption'   => '_Music',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          26 => array(
            'Func'      => 'ActionList',
            'Content'   => '',
            'Caption'   => '_Actions',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          27 => array(
            'Func'      => 'ViewComments',
            'Content'   => '',
            'Caption'   => '_View Comments',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
      2 => array(
        'Width'  => 50,
        'Blocks' => array(
          28 => array(
            'Func'      => 'FileInfo',
            'Content'   => '',
            'Caption'   => '_Music File Info',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          25 => array(
            'Func'      => 'Rate',
            'Content'   => '',
            'Caption'   => '_Rate',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          29 => array(
            'Func'      => 'LastFiles',
            'Content'   => '',
            'Caption'   => '_Latest files from this user',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
    )
  ),
  'photo' => array(
    'Width' => '960px',
    'Columns' => array(
      1 => array(
        'Width'  => 50,
        'Blocks' => array(
          38 => array(
            'Func'      => 'ViewFile',
            'Content'   => '',
            'Caption'   => '_Photo',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          40 => array(
            'Func'      => 'ActionList',
            'Content'   => '',
            'Caption'   => '_Actions',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          41 => array(
            'Func'      => 'ViewComments',
            'Content'   => '',
            'Caption'   => '_View Comments',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
      2 => array(
        'Width'  => 50,
        'Blocks' => array(
          42 => array(
            'Func'      => 'FileInfo',
            'Content'   => '',
            'Caption'   => '_Photo Info',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          39 => array(
            'Func'      => 'Rate',
            'Content'   => '',
            'Caption'   => '_Rate',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          43 => array(
            'Func'      => 'LastFiles',
            'Content'   => '',
            'Caption'   => '_Latest files from this user',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
    )
  ),
  'profile' => array(
    'Width' => '960px',
    'Columns' => array(
      1 => array(
        'Width'  => 50,
        'Blocks' => array(
          65 => array(
            'Func'      => 'ActionsMenu',
            'Content'   => '',
            'Caption'   => '_Actions',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          73 => array(
            'Func'      => 'Classifieds',
            'Content'   => '',
            'Caption'   => '_Classifieds',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          74 => array(
            'Func'      => 'Events',
            'Content'   => '',
            'Caption'   => '_Events',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          75 => array(
            'Func'      => 'Groups',
            'Content'   => '',
            'Caption'   => '_Groups',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          64 => array(
            'Func'      => 'ProfilePolls',
            'Content'   => '',
            'Caption'   => '_Polls',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          76 => array(
            'Func'      => 'ShareMusic',
            'Content'   => '',
            'Caption'   => '_Music Gallery',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          77 => array(
            'Func'      => 'SharePhotos',
            'Content'   => '',
            'Caption'   => '_Photo Gallery',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          78 => array(
            'Func'      => 'ShareVideos',
            'Content'   => '',
            'Caption'   => '_Video Gallery',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
      2 => array(
        'Width'  => 50,
        'Blocks' => array(
          82 => array(
            'Func'      => 'PFBlock',
            'Content'   => '21',
            'Caption'   => '_FieldCaption_Admin Controls_View',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          80 => array(
            'Func'      => 'PFBlock',
            'Content'   => '17',
            'Caption'   => '_FieldCaption_General Info_View',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          81 => array(
            'Func'      => 'PFBlock',
            'Content'   => '20',
            'Caption'   => '_FieldCaption_Misc Info_View',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          83 => array(
            'Func'      => 'PFBlock',
            'Content'   => '22',
            'Caption'   => '_FieldCaption_Description_View',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          66 => array(
            'Func'      => 'RateProfile',
            'Content'   => '',
            'Caption'   => '_rate profile',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          69 => array(
            'Func'      => 'Blog',
            'Content'   => '',
            'Caption'   => '_Blog',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          67 => array(
            'Func'      => 'Friends',
            'Content'   => '',
            'Caption'   => '_Friends',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          79 => array(
            'Func'      => 'MutualFriends',
            'Content'   => '',
            'Caption'   => '_Mutual Friends',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          70 => array(
            'Func'      => 'Mp3',
            'Content'   => '',
            'Caption'   => '_ProfileMp3',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          71 => array(
            'Func'      => 'RSS',
            'Content'   => '{SiteUrl}orca/?action=rss_user&user={NickName}#4',
            'Caption'   => '_Forum Posts',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          68 => array(
            'Func'      => 'Cmts',
            'Content'   => '',
            'Caption'   => '_profile_comments',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
    )
  ),
  'video' => array(
    'Width' => '960px',
    'Columns' => array(
      1 => array(
        'Width'  => 50,
        'Blocks' => array(
          31 => array(
            'Func'      => 'ViewFile',
            'Content'   => '',
            'Caption'   => '_Video',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          33 => array(
            'Func'      => 'ActionList',
            'Content'   => '',
            'Caption'   => '_Actions',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          34 => array(
            'Func'      => 'ViewComments',
            'Content'   => '',
            'Caption'   => '_View Comments',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
      2 => array(
        'Width'  => 50,
        'Blocks' => array(
          35 => array(
            'Func'      => 'FileInfo',
            'Content'   => '',
            'Caption'   => '_Video Info',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          32 => array(
            'Func'      => 'Rate',
            'Content'   => '',
            'Caption'   => '_Rate',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
          36 => array(
            'Func'      => 'LastFiles',
            'Content'   => '',
            'Caption'   => '_Latest files from this user',
            'Visible'   => 'non,memb',
            'DesignBox' => 1
          ),
        )
      ),
    )
  ),
);
