INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Shows statistic information concerning your profiles database', '_Site Stats', 1, 0, 'SiteStats', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Show list of site news', '_latest news', 2, 4, 'News', '', 1, 40, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Display form to subscribe to newsletters', '_Subscribe', 2, 6, 'Subscribe', '', 1, 40, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Quick search form', '_Quick Search', 2, 2, 'QuickSearch', '', 1, 40, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Top rated profiles', '_Leaders', 1, 3, 'Leaders', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Feedback (Success Story) from your customers', '_Feedback', 2, 8, 'Feedback', '', 1, 40, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'List of featured profiles randomly selected from database', '_featured members', 1, 5, 'Featured', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Personal profile polls', '_Polls', 2, 7, 'ProfilePoll', '', 1, 40, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Site Tags', '_Tags', 2, 3, 'Tags', '', 1, 40, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Short list of top profiles selected by given criteria', '_Members', 1, 2, 'Members', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Recently posted blogs', '_Blogs', 1, 4, 'Blogs', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Top rated photos', '_Profile Photos', 1, 9, 'ProfilePhotos', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Shoutbox', '_Shoutbox', 2, 1, 'Shoutbox', '', 1, 40, 'non,memb', 330);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Shows Login Form', '_Member Login', 2, 0, 'LoginSection', '', 1, 40, 'non', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', '', '_BoonEx News', 1, 1, 'RSS', 'http://www.boonex.com/unity/blog/featured_posts/?rss=1#4', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Classifieds', '_Classifieds', 1, 13, 'Classifieds', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Events', '_Events', 1, 10, 'Events', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Groups', '_Groups', 1, 12, 'Groups', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', '', '_Forum Posts', 2, 5, 'RSS', '{SiteUrl}orca/?action=rss_all#4', 1, 40, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Photos Shared By Members', '_Photo Gallery', 1, 7, 'SharePhotos', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Videos Shared By Members', '_Video Gallery', 1, 6, 'ShareVideos', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Music Files Shared By Members', '_Music Gallery', 1, 8, 'ShareMusic', '', 1, 60, 'non,memb', 0);
INSERT INTO `PageCompose` VALUES(NULL, 'index', '960px', 'Articles', '_Articles', 1, 11, 'Articles', '', 1, 60, 'non,memb', 0);
