TRUNCATE TABLE `IndexCompose`;

INSERT INTO `IndexCompose` VALUES (1, 'Site Stats', 'Shows statistic information concerning your profiles database', '_Site Stats', 'non,memb', 'MemberStat', '', 2, 0);
INSERT INTO `IndexCompose` VALUES (3, 'News', 'Show list of site news', '_latest news', 'non,memb', 'News', '', 2, 1);
INSERT INTO `IndexCompose` VALUES (4, 'Subscribe', 'Display form to subscribe to newsletters', '_Subscribe', 'non,memb', 'Subscribe', '', 2, 2);
INSERT INTO `IndexCompose` VALUES (5, 'Quick Search', 'Quick search form', '_Quick Search', 'non,memb', 'QuickSearchIndex', '', 2, 3);
INSERT INTO `IndexCompose` VALUES (6, 'Leaders', 'Top rated profiles', '_Leaders', 'non,memb', 'TopRated', '', 1, 1);
INSERT INTO `IndexCompose` VALUES (7, 'Feedback', 'Feedback (Success Story) from your customers', '_Feedback', 'non,memb', 'Feedback', '', 1, 2);
INSERT INTO `IndexCompose` VALUES (8, 'Featured', 'List of featured profiles randomly selected from database', '_featured members', 'non,memb', 'Featured', '', 1, 3);
INSERT INTO `IndexCompose` VALUES (9, 'Polls', 'Personal profile polls', '_Polls', 'non,memb', 'ProfilePoll', '', 1, 4);
INSERT INTO `IndexCompose` VALUES (10, 'Tags', 'Site Tags', '_Tags', 'non,memb', 'Tags', '', 1, 5);
INSERT INTO `IndexCompose` VALUES (11, 'Top Members', 'Short list of top profiles selected by given criteria', '_Members', 'non,memb', 'TopMembers', '', 2, 4);
INSERT INTO `IndexCompose` VALUES (12, 'Blogs', 'Recently posted blogs', '_Blogs', 'non,memb', 'Blogs', '', 1, 6);
INSERT INTO `IndexCompose` VALUES (13, 'Profile Photos', 'Top rated photos', '_Profile Photos', 'non,memb', 'TopPhotos', '', 2, 5);
INSERT INTO `IndexCompose` VALUES (14, 'Shoutbox', 'Shoutbox', '_Shoutbox', 'non,memb', 'Shoutbox', '', 2, 8);
INSERT INTO `IndexCompose` VALUES (15, 'Login', 'Shows Login Form', '_Member Login', 'non', 'LoginSection', '', 1, 0);
INSERT INTO `IndexCompose` VALUES (16, 'RSS Feed', '', '_BoonEx News', 'non,memb', 'RSS', 'http://www.boonex.org/author/admin/feed#4', 2, 9);
INSERT INTO `IndexCompose` VALUES (17, 'Classifieds', 'Classifieds', '_Classifieds', 'non,memb', 'Classifieds', '', 1, 7);
INSERT INTO `IndexCompose` VALUES (18, 'Events', 'Events', '_Events', 'non,memb', 'Events', '', 1, 8);
INSERT INTO `IndexCompose` VALUES (19, 'Groups', 'Groups', '_Groups', 'non,memb', 'Groups', '', 1, 9);
INSERT INTO `IndexCompose` VALUES (20, 'Forum RSS Feed', '', '_Forum Posts', 'non,memb', 'RSS', '{SiteUrl}orca/?action=rss_all#4', 2, 6);
INSERT INTO `IndexCompose` VALUES (21, 'Photo Gallery', 'Photos Shared By Members', '_Photo Gallery', 'non,memb', 'SharePhotos', '', 1, 11);
INSERT INTO `IndexCompose` VALUES (22, 'Video Gallery', 'Videos Shared By Members', '_Video Gallery', 'non,memb', 'ShareVideos', '', 1, 10);
INSERT INTO `IndexCompose` VALUES (23, 'Music Gallery', 'Music Files Shared By Members', '_Music Gallery', 'non,memb', 'ShareMusic', '', 1, 12);
INSERT INTO `IndexCompose` VALUES (24, 'Articles', 'Articles', '_Articles', 'non,memb', 'Articles', '', 2, 7);
