<?
$aPreValues = array(
  'Country' => array(
    'SZ' => array( 'LKey' => '__Swaziland', ),
    'SY' => array( 'LKey' => '__Syria', ),
    'SV' => array( 'LKey' => '__El Salvador', ),
    'ST' => array( 'LKey' => '__Sao Tome and Principe', ),
    'SR' => array( 'LKey' => '__Suriname', ),
    'SO' => array( 'LKey' => '__Somalia', ),
    'SN' => array( 'LKey' => '__Senegal', ),
    'SM' => array( 'LKey' => '__San Marino', ),
    'SL' => array( 'LKey' => '__Sierra Leone', ),
    'SK' => array( 'LKey' => '__Slovakia', ),
    'SJ' => array( 'LKey' => '__Svalbard', ),
    'SI' => array( 'LKey' => '__Slovenia', ),
    'SH' => array( 'LKey' => '__Saint Helena', ),
    'SG' => array( 'LKey' => '__Singapore', ),
    'SE' => array( 'LKey' => '__Sweden', ),
    'SD' => array( 'LKey' => '__Sudan', ),
    'SC' => array( 'LKey' => '__Seychelles', ),
    'SB' => array( 'LKey' => '__Solomon Islands', ),
    'SA' => array( 'LKey' => '__Saudi Arabia', ),
    'RW' => array( 'LKey' => '__Rwanda', ),
    'RU' => array( 'LKey' => '__Russia', ),
    'RE' => array( 'LKey' => '__Reunion', ),
    'QA' => array( 'LKey' => '__Qatar', ),
    'PY' => array( 'LKey' => '__Paraguay', ),
    'PW' => array( 'LKey' => '__Palau', ),
    'PT' => array( 'LKey' => '__Portugal', ),
    'PS' => array( 'LKey' => '__Palestinian Territory, Occupied', ),
    'PR' => array( 'LKey' => '__Puerto Rico', ),
    'PN' => array( 'LKey' => '__Pitcairn Islands', ),
    'PM' => array( 'LKey' => '__Saint Pierre and Miquelon', ),
    'PK' => array( 'LKey' => '__Pakistan', ),
    'PL' => array( 'LKey' => '__Poland', ),
    'PH' => array( 'LKey' => '__Philippines', ),
    'PG' => array( 'LKey' => '__Papua New Guinea', ),
    'PF' => array( 'LKey' => '__French Polynesia', ),
    'PE' => array( 'LKey' => '__Peru', ),
    'PA' => array( 'LKey' => '__Panama', ),
    'NZ' => array( 'LKey' => '__New Zealand', ),
    'NR' => array( 'LKey' => '__Nauru', ),
    'NP' => array( 'LKey' => '__Nepal', ),
    'NO' => array( 'LKey' => '__Norway', ),
    'NL' => array( 'LKey' => '__Netherlands', ),
    'NI' => array( 'LKey' => '__Nicaragua', ),
    'NG' => array( 'LKey' => '__Nigeria', ),
    'NF' => array( 'LKey' => '__Norfolk Island', ),
    'NE' => array( 'LKey' => '__Niger', ),
    'NC' => array( 'LKey' => '__New Caledonia', ),
    'NA' => array( 'LKey' => '__Namibia', ),
    'MZ' => array( 'LKey' => '__Mozambique', ),
    'MX' => array( 'LKey' => '__Mexico', ),
    'MW' => array( 'LKey' => '__Malawi', ),
    'MU' => array( 'LKey' => '__Mauritius', ),
    'MT' => array( 'LKey' => '__Malta', ),
    'MS' => array( 'LKey' => '__Montserrat', ),
    'MQ' => array( 'LKey' => '__Martinique', ),
    'MR' => array( 'LKey' => '__Mauritania', ),
    'MP' => array( 'LKey' => '__Northern Mariana Islands', ),
    'MN' => array( 'LKey' => '__Mongolia', ),
    'MM' => array( 'LKey' => '__Burma', ),
    'ML' => array( 'LKey' => '__Mali', ),
    'MH' => array( 'LKey' => '__Marshall Islands', ),
    'MG' => array( 'LKey' => '__Madagascar', ),
    'MD' => array( 'LKey' => '__Moldova', ),
    'MC' => array( 'LKey' => '__Monaco', ),
    'MA' => array( 'LKey' => '__Morocco', ),
    'LY' => array( 'LKey' => '__Libya', ),
    'LU' => array( 'LKey' => '__Luxembourg', ),
    'LV' => array( 'LKey' => '__Latvia', ),
    'LT' => array( 'LKey' => '__Lithuania', ),
    'LS' => array( 'LKey' => '__Lesotho', ),
    'LR' => array( 'LKey' => '__Liberia', ),
    'LI' => array( 'LKey' => '__Liechtenstein', ),
    'LK' => array( 'LKey' => '__Sri Lanka', ),
    'LC' => array( 'LKey' => '__Saint Lucia', ),
    'LA' => array( 'LKey' => '__Laos', ),
    'KZ' => array( 'LKey' => '__Kazakhstan', ),
    'KY' => array( 'LKey' => '__Cayman Islands', ),
    'KR' => array( 'LKey' => '__Korea, South', ),
    'KP' => array( 'LKey' => '__Korea, North', ),
    'KN' => array( 'LKey' => '__Saint Kitts and Nevis', ),
    'KI' => array( 'LKey' => '__Kiribati', ),
    'KH' => array( 'LKey' => '__Cambodia', ),
    'JP' => array( 'LKey' => '__Japan', ),
    'JO' => array( 'LKey' => '__Jordan', ),
    'JM' => array( 'LKey' => '__Jamaica', ),
    'IT' => array( 'LKey' => '__Italy', ),
    'IS' => array( 'LKey' => '__Iceland', ),
    'IR' => array( 'LKey' => '__Iran', ),
    'IQ' => array( 'LKey' => '__Iraq', ),
    'IO' => array( 'LKey' => '__British Indian Ocean Territory', ),
    'IN' => array( 'LKey' => '__India', ),
    'IL' => array( 'LKey' => '__Israel', ),
    'IE' => array( 'LKey' => '__Ireland', ),
    'ID' => array( 'LKey' => '__Indonesia', ),
    'HU' => array( 'LKey' => '__Hungary', ),
    'HT' => array( 'LKey' => '__Haiti', ),
    'HR' => array( 'LKey' => '__Croatia', ),
    'HN' => array( 'LKey' => '__Honduras', ),
    'HK' => array( 'LKey' => '__Hong Kong (SAR)', ),
    'GY' => array( 'LKey' => '__Guyana', ),
    'GW' => array( 'LKey' => '__Guinea-Bissau', ),
    'GU' => array( 'LKey' => '__Guam', ),
    'GT' => array( 'LKey' => '__Guatemala', ),
    'GS' => array( 'LKey' => '__South Georgia and the South Sandwich Islands', ),
    'GP' => array( 'LKey' => '__Guadeloupe', ),
    'GN' => array( 'LKey' => '__Guinea', ),
    'GM' => array( 'LKey' => '__The Gambia', ),
    'GL' => array( 'LKey' => '__Greenland', ),
    'GH' => array( 'LKey' => '__Ghana', ),
    'GF' => array( 'LKey' => '__French Guiana', ),
    'GE' => array( 'LKey' => '__Georgia', ),
    'GD' => array( 'LKey' => '__Grenada', ),
    'GB' => array( 'LKey' => '__United Kingdom', ),
    'GA' => array( 'LKey' => '__Gabon', ),
    'FO' => array( 'LKey' => '__Faroe Islands', ),
    'FM' => array( 'LKey' => '__Micronesia, Federated States of', ),
    'FK' => array( 'LKey' => '__Falkland Islands (Islas Malvinas)', ),
    'FJ' => array( 'LKey' => '__Fiji', ),
    'FI' => array( 'LKey' => '__Finland', ),
    'ET' => array( 'LKey' => '__Ethiopia', ),
    'ES' => array( 'LKey' => '__Spain', ),
    'ER' => array( 'LKey' => '__Eritrea', ),
    'EH' => array( 'LKey' => '__Western Sahara', ),
    'EG' => array( 'LKey' => '__Egypt', ),
    'EE' => array( 'LKey' => '__Estonia', ),
    'EC' => array( 'LKey' => '__Ecuador', ),
    'DZ' => array( 'LKey' => '__Algeria', ),
    'DO' => array( 'LKey' => '__Dominican Republic', ),
    'DM' => array( 'LKey' => '__Dominica', ),
    'DK' => array( 'LKey' => '__Denmark', ),
    'DE' => array( 'LKey' => '__Germany', ),
    'DJ' => array( 'LKey' => '__Djibouti', ),
    'CY' => array( 'LKey' => '__Cyprus', ),
    'CX' => array( 'LKey' => '__Christmas Island', ),
    'CV' => array( 'LKey' => '__Cape Verde', ),
    'CU' => array( 'LKey' => '__Cuba', ),
    'CR' => array( 'LKey' => '__Costa Rica', ),
    'CO' => array( 'LKey' => '__Colombia', ),
    'CN' => array( 'LKey' => '__China', ),
    'CL' => array( 'LKey' => '__Chile', ),
    'CK' => array( 'LKey' => '__Cook Islands', ),
    'CI' => array( 'LKey' => '__Cote d\'Ivoire', ),
    'CH' => array( 'LKey' => '__Switzerland', ),
    'CG' => array( 'LKey' => '__Congo, Republic of the', ),
    'CF' => array( 'LKey' => '__Central African Republic', ),
    'CD' => array( 'LKey' => '__Congo, Democratic Republic of the', ),
    'CC' => array( 'LKey' => '__Cocos (Keeling) Islands', ),
    'CA' => array( 'LKey' => '__Canada', ),
    'BY' => array( 'LKey' => '__Belarus', ),
    'BW' => array( 'LKey' => '__Botswana', ),
    'BV' => array( 'LKey' => '__Bouvet Island', ),
    'BT' => array( 'LKey' => '__Bhutan', ),
    'BS' => array( 'LKey' => '__The Bahamas', ),
    'BR' => array( 'LKey' => '__Brazil', ),
    'BO' => array( 'LKey' => '__Bolivia', ),
    'BN' => array( 'LKey' => '__Brunei Darussalam', ),
    'BM' => array( 'LKey' => '__Bermuda', ),
    'BJ' => array( 'LKey' => '__Benin', ),
    'BH' => array( 'LKey' => '__Bahrain', ),
    'BG' => array( 'LKey' => '__Bulgaria', ),
    'BF' => array( 'LKey' => '__Burkina Faso', ),
    'BE' => array( 'LKey' => '__Belgium', ),
    'BD' => array( 'LKey' => '__Bangladesh', ),
    'BA' => array( 'LKey' => '__Bosnia and Herzegovina', ),
    'BB' => array( 'LKey' => '__Barbados', ),
    'AZ' => array( 'LKey' => '__Azerbaijan', ),
    'AW' => array( 'LKey' => '__Aruba', ),
    'AU' => array( 'LKey' => '__Australia', ),
    'AT' => array( 'LKey' => '__Austria', ),
    'AR' => array( 'LKey' => '__Argentina', ),
    'AS' => array( 'LKey' => '__American Samoa', ),
    'AQ' => array( 'LKey' => '__Antarctica', ),
    'AO' => array( 'LKey' => '__Angola', ),
    'AN' => array( 'LKey' => '__Netherlands Antilles', ),
    'AM' => array( 'LKey' => '__Armenia', ),
    'AL' => array( 'LKey' => '__Albania', ),
    'AG' => array( 'LKey' => '__Antigua and Barbuda', ),
    'AF' => array( 'LKey' => '__Afghanistan', ),
    'AE' => array( 'LKey' => '__United Arab Emirates', ),
    'AD' => array( 'LKey' => '__Andorra', ),
    'RO' => array( 'LKey' => '__Romania', ),
    'OM' => array( 'LKey' => '__Oman', ),
    'NU' => array( 'LKey' => '__Niue', ),
    'MY' => array( 'LKey' => '__Malaysia', ),
    'MV' => array( 'LKey' => '__Maldives', ),
    'MO' => array( 'LKey' => '__Macao', ),
    'MK' => array( 'LKey' => '__Macedonia, The Former Yugoslav Republic of', ),
    'LB' => array( 'LKey' => '__Lebanon', ),
    'KW' => array( 'LKey' => '__Kuwait', ),
    'KM' => array( 'LKey' => '__Comoros', ),
    'KG' => array( 'LKey' => '__Kyrgyzstan', ),
    'KE' => array( 'LKey' => '__Kenya', ),
    'HM' => array( 'LKey' => '__Heard Island and McDonald Islands', ),
    'GR' => array( 'LKey' => '__Greece', ),
    'GQ' => array( 'LKey' => '__Equatorial Guinea', ),
    'GI' => array( 'LKey' => '__Gibraltar', ),
    'FR' => array( 'LKey' => '__France', ),
    'CZ' => array( 'LKey' => '__Czech Republic', ),
    'CM' => array( 'LKey' => '__Cameroon', ),
    'BZ' => array( 'LKey' => '__Belize', ),
    'BI' => array( 'LKey' => '__Burundi', ),
    'AI' => array( 'LKey' => '__Anguilla', ),
    'TC' => array( 'LKey' => '__Turks and Caicos Islands', ),
    'TD' => array( 'LKey' => '__Chad', ),
    'TF' => array( 'LKey' => '__French Southern and Antarctic Lands', ),
    'TG' => array( 'LKey' => '__Togo', ),
    'TH' => array( 'LKey' => '__Thailand', ),
    'TJ' => array( 'LKey' => '__Tajikistan', ),
    'TK' => array( 'LKey' => '__Tokelau', ),
    'TL' => array( 'LKey' => '__East Timor', ),
    'TM' => array( 'LKey' => '__Turkmenistan', ),
    'TN' => array( 'LKey' => '__Tunisia', ),
    'TO' => array( 'LKey' => '__Tonga', ),
    'TR' => array( 'LKey' => '__Turkey', ),
    'TT' => array( 'LKey' => '__Trinidad and Tobago', ),
    'TV' => array( 'LKey' => '__Tuvalu', ),
    'TW' => array( 'LKey' => '__Taiwan', ),
    'TZ' => array( 'LKey' => '__Tanzania', ),
    'UA' => array( 'LKey' => '__Ukraine', ),
    'UG' => array( 'LKey' => '__Uganda', ),
    'UM' => array( 'LKey' => '__United States Minor Outlying Islands', ),
    'US' => array( 'LKey' => '__United States', ),
    'UY' => array( 'LKey' => '__Uruguay', ),
    'UZ' => array( 'LKey' => '__Uzbekistan', ),
    'VA' => array( 'LKey' => '__Holy See (Vatican City)', ),
    'VC' => array( 'LKey' => '__Saint Vincent and the Grenadines', ),
    'VE' => array( 'LKey' => '__Venezuela', ),
    'VG' => array( 'LKey' => '__British Virgin Islands', ),
    'VI' => array( 'LKey' => '__Virgin Islands', ),
    'VN' => array( 'LKey' => '__Vietnam', ),
    'VU' => array( 'LKey' => '__Vanuatu', ),
    'WF' => array( 'LKey' => '__Wallis and Futuna', ),
    'WS' => array( 'LKey' => '__Samoa', ),
    'YE' => array( 'LKey' => '__Yemen', ),
    'YT' => array( 'LKey' => '__Mayotte', ),
    'YU' => array( 'LKey' => '__Yugoslavia', ),
    'ZA' => array( 'LKey' => '__South Africa', ),
    'ZM' => array( 'LKey' => '__Zambia', ),
    'ZW' => array( 'LKey' => '__Zimbabwe', ),
  ),
  'Sex' => array(
    'male' => array( 'LKey' => '_Male', 'LKey2' => '_LookinMale', ),
    'female' => array( 'LKey' => '_Female', 'LKey2' => '_LookinFemale', ),
  ),
  'Height' => array(
    '1' => array( 'LKey' => '__4\'7\" (140cm) or below', ),
    '2' => array( 'LKey' => '__4\'8\" - 4\'11\" (141-150cm)', ),
    '3' => array( 'LKey' => '__5\'0\" - 5\'3\" (151-160cm)', ),
    '4' => array( 'LKey' => '__5\'4\" - 5\'7\" (161-170cm)', ),
    '5' => array( 'LKey' => '__5\'8\" - 5\'11\" (171-180cm)', ),
    '6' => array( 'LKey' => '__6\'0\" - 6\'3\" (181-190cm)', ),
    '7' => array( 'LKey' => '__6\'4\" (191cm) or above', ),
  ),
  'BodyType' => array(
    '1' => array( 'LKey' => '__Average', ),
    '2' => array( 'LKey' => '__Ample', ),
    '3' => array( 'LKey' => '__Athletic', ),
    '4' => array( 'LKey' => '__Cuddly', ),
    '5' => array( 'LKey' => '__Slim', ),
    '6' => array( 'LKey' => '__Very Cuddly', ),
  ),
  'Religion' => array(
    '1' => array( 'LKey' => '__Adventist', ),
    '2' => array( 'LKey' => '__Agnostic', ),
    '3' => array( 'LKey' => '__Atheist', ),
    '4' => array( 'LKey' => '__Baptist', ),
    '5' => array( 'LKey' => '__Buddhist', ),
    '6' => array( 'LKey' => '__Caodaism', ),
    '7' => array( 'LKey' => '__Catholic', ),
    '8' => array( 'LKey' => '__Christian', ),
    '9' => array( 'LKey' => '__Hindu', ),
    '10' => array( 'LKey' => '__Iskcon', ),
    '11' => array( 'LKey' => '__Jainism', ),
    '12' => array( 'LKey' => '__Jewish', ),
    '13' => array( 'LKey' => '__Methodist', ),
    '14' => array( 'LKey' => '__Mormon', ),
    '15' => array( 'LKey' => '__Moslem', ),
    '16' => array( 'LKey' => '__Orthodox', ),
    '17' => array( 'LKey' => '__Pentecostal', ),
    '18' => array( 'LKey' => '__Protestant', ),
    '19' => array( 'LKey' => '__Quaker', ),
    '20' => array( 'LKey' => '__Scientology', ),
    '21' => array( 'LKey' => '__Shinto', ),
    '22' => array( 'LKey' => '__Sikhism', ),
    '23' => array( 'LKey' => '__Spiritual', ),
    '24' => array( 'LKey' => '__Taoism', ),
    '25' => array( 'LKey' => '__Wiccan', ),
    '26' => array( 'LKey' => '__Other', ),
  ),
  'Ethnicity' => array(
    '1' => array( 'LKey' => '__African', ),
    '2' => array( 'LKey' => '__African American', ),
    '3' => array( 'LKey' => '__Asian', ),
    '4' => array( 'LKey' => '__Caucasian', ),
    '5' => array( 'LKey' => '__East Indian', ),
    '6' => array( 'LKey' => '__Hispanic', ),
    '7' => array( 'LKey' => '__Indian', ),
    '8' => array( 'LKey' => '__Latino', ),
    '9' => array( 'LKey' => '__Mediterranean', ),
    '10' => array( 'LKey' => '__Middle Eastern', ),
    '11' => array( 'LKey' => '__Mixed', ),
  ),
  'MaritalStatus' => array(
    '1' => array( 'LKey' => '__Single', ),
    '2' => array( 'LKey' => '__Attached', ),
    '3' => array( 'LKey' => '__Divorced', ),
    '4' => array( 'LKey' => '__Married', ),
    '5' => array( 'LKey' => '__Separated', ),
    '6' => array( 'LKey' => '__Widow', ),
  ),
  'Language' => array(
    '0' => array( 'LKey' => '__English', ),
    '1' => array( 'LKey' => '__Afrikaans', ),
    '2' => array( 'LKey' => '__Arabic', ),
    '3' => array( 'LKey' => '__Bulgarian', ),
    '4' => array( 'LKey' => '__Burmese', ),
    '5' => array( 'LKey' => '__Cantonese', ),
    '6' => array( 'LKey' => '__Croatian', ),
    '7' => array( 'LKey' => '__Danish', ),
    '8' => array( 'LKey' => '__Dutch', ),
    '9' => array( 'LKey' => '__Esperanto', ),
    '10' => array( 'LKey' => '__Estonian', ),
    '11' => array( 'LKey' => '__Finnish', ),
    '12' => array( 'LKey' => '__French', ),
    '13' => array( 'LKey' => '__German', ),
    '14' => array( 'LKey' => '__Greek', ),
    '15' => array( 'LKey' => '__Gujrati', ),
    '16' => array( 'LKey' => '__Hebrew', ),
    '17' => array( 'LKey' => '__Hindi', ),
    '18' => array( 'LKey' => '__Hungarian', ),
    '19' => array( 'LKey' => '__Icelandic', ),
    '20' => array( 'LKey' => '__Indian', ),
    '21' => array( 'LKey' => '__Indonesian', ),
    '22' => array( 'LKey' => '__Italian', ),
    '23' => array( 'LKey' => '__Japanese', ),
    '24' => array( 'LKey' => '__Korean', ),
    '25' => array( 'LKey' => '__Latvian', ),
    '26' => array( 'LKey' => '__Lithuanian', ),
    '27' => array( 'LKey' => '__Malay', ),
    '28' => array( 'LKey' => '__Mandarin', ),
    '29' => array( 'LKey' => '__Marathi', ),
    '30' => array( 'LKey' => '__Moldovian', ),
    '31' => array( 'LKey' => '__Nepalese', ),
    '32' => array( 'LKey' => '__Norwegian', ),
    '33' => array( 'LKey' => '__Persian', ),
    '34' => array( 'LKey' => '__Polish', ),
    '35' => array( 'LKey' => '__Portuguese', ),
    '36' => array( 'LKey' => '__Punjabi', ),
    '37' => array( 'LKey' => '__Romanian', ),
    '38' => array( 'LKey' => '__Russian', ),
    '39' => array( 'LKey' => '__Serbian', ),
    '40' => array( 'LKey' => '__Spanish', ),
    '41' => array( 'LKey' => '__Swedish', ),
    '42' => array( 'LKey' => '__Tagalog', ),
    '43' => array( 'LKey' => '__Taiwanese', ),
    '44' => array( 'LKey' => '__Tamil', ),
    '45' => array( 'LKey' => '__Telugu', ),
    '46' => array( 'LKey' => '__Thai', ),
    '47' => array( 'LKey' => '__Tongan', ),
    '48' => array( 'LKey' => '__Turkish', ),
    '49' => array( 'LKey' => '__Ukrainian', ),
    '50' => array( 'LKey' => '__Urdu', ),
    '51' => array( 'LKey' => '__Vietnamese', ),
    '52' => array( 'LKey' => '__Visayan', ),
  ),
  'Education' => array(
    '1' => array( 'LKey' => '__High School graduate', ),
    '2' => array( 'LKey' => '__Some college', ),
    '3' => array( 'LKey' => '__College student', ),
    '4' => array( 'LKey' => '__AA (2 years college)', ),
    '5' => array( 'LKey' => '__BA/BS (4 years college)', ),
    '6' => array( 'LKey' => '__Some grad school', ),
    '7' => array( 'LKey' => '__Grad school student', ),
    '8' => array( 'LKey' => '__MA/MS/MBA', ),
    '9' => array( 'LKey' => '__PhD/Post doctorate', ),
    '10' => array( 'LKey' => '__JD', ),
  ),
  'Income' => array(
    '1' => array( 'LKey' => '__$10,000/year and less', ),
    '2' => array( 'LKey' => '__$10,000-$30,000/year', ),
    '3' => array( 'LKey' => '__$30,000-$50,000/year', ),
    '4' => array( 'LKey' => '__$50,000-$70,000/year', ),
    '5' => array( 'LKey' => '__$70,000/year and more', ),
  ),
  'Smoker' => array(
    '1' => array( 'LKey' => '__No', ),
    '2' => array( 'LKey' => '__Rarely', ),
    '3' => array( 'LKey' => '__Often', ),
    '4' => array( 'LKey' => '__Very often', ),
  ),
  'Drinker' => array(
    '1' => array( 'LKey' => '__No', ),
    '2' => array( 'LKey' => '__Rarely', ),
    '3' => array( 'LKey' => '__Often', ),
    '4' => array( 'LKey' => '__Very often', ),
  ),
);

$aPreValues['Country'] = sortArrByLang( $aPreValues['Country'] );
//echoDbg( $aPreValues['Country'] );

function sortArrByLang( $aArr ) {
	if( !function_exists( '_t' ) )
		return $aArr;
	
	$aSortArr = array();
	foreach( $aArr as $sKey => $aValue )
		$aSortArr[$sKey] = _t( $aValue['LKey'] );
	
	asort( $aSortArr );
	
	$aNewArr = array();
	foreach( $aSortArr as $sKey => $sVal )
		$aNewArr[$sKey] = $aArr[$sKey];
	
	return $aNewArr;
}
	